import assert from 'node:assert/strict';import fs from 'node:fs';import {runCase,selection} from './run-case.mjs';
const report=[];const spec=(id,kind)=>({id,kind,q:0});const build=(x,y,x2,y2,kind)=>({op:'build',x,y,x2,y2,kind});
function conserve(r){const s=r.city.sim;assert.equal(r.conservation,0);assert.equal(s.population,r.agents.length);assert.equal(s.born-s.removed,s.population);assert.equal(new Set(r.agents.map(a=>a.id)).size,s.population);assert.equal(s.requested,s.arrived+s.cancelled+r.agents.filter(a=>[1,2,4,5,6].includes(a.state)).length);const tiles=new Map(r.city.world.tiles);for(const [key,n] of r.lanes){assert(n>=0);const kind=tiles.get(Math.floor(key/8));if(kind===1||kind===2)assert(n<=3,`lane ${key} has ${n} cars/reservations`)}for(const a of r.agents){assert(a.wait>=0);if(a.state===2){assert(tiles.has(a.cell));assert(Math.abs(a.from%128-a.to%128)+Math.abs(Math.floor(a.from/128)-Math.floor(a.to/128))<=1);assert(a.elapsed<=a.duration)}}}
function run(name,input,check=()=>{}){if(input.rows===-1){input={...input};for(const field of ['commands','after'])if(input[field])input[field]=input[field].map(c=>({...c,x:c.x+50,x2:c.x2+50,y:c.y+54,y2:c.y2+54}))}const x=runCase({rows:0,ticks:1,tiles:[],commands:[],after:[],...input},name);conserve(x.result);check(x.result);report.push({name,passed:true,wall_ms:x.wall_ms});console.log('PASS',name);return x.result}
const simple=[spec(0,3),spec(1,1),spec(2,4)];
run('nearby-work-is-walkable',{tiles:simple,ticks:24},r=>{assert.equal(r.city.sim.population,8);assert(r.city.sim.workVisits>0);assert.equal(r.city.sim.carTrips,0);assert(r.agents.some(a=>a.purpose===4));});
run('missing-destination-retains-residents',{tiles:[spec(0,3)],ticks:50},r=>{assert.equal(r.city.sim.requested,8);assert.equal(r.city.sim.disconnected,8);assert.equal(r.city.sim.arrived,0)});
run('row-boundary-never-wraps',{tiles:[spec(127,3),spec(128,4)],ticks:30},r=>assert.equal(r.city.sim.arrived,0));
run('occupied-edit-is-atomic',{tiles:simple,ticks:5,after:[build(1,0,3,0,0)]},r=>{assert.equal(r.city.world.version,1);assert.equal(r.city.cash,10000);assert.equal(r.city.world.tiles.length,3)});
run('unchanged-edit-keeps-topology',{tiles:simple,ticks:0,commands:[build(1,0,1,0,1)]},r=>assert.equal(r.city.world.version,1));
run('disconnected-edit-reroutes',{tiles:simple,ticks:24,commands:[build(1,0,1,0,0)]},r=>{assert.equal(r.city.sim.arrived,0);assert.equal(r.city.sim.disconnected,8);assert.equal(r.city.world.version,2)});
run('invalid-edit-no-charge',{tiles:simple,ticks:0,commands:[build(-1,0,127,0,2),build(4,4,7,7,2),build(4,4,4,4,99)]},r=>{assert.equal(r.city.world.version,1);assert.equal(r.city.cash,10000)});
run('walking-only-shortcut',{tiles:[spec(0,3),spec(1,7),spec(2,4)],ticks:24},r=>{assert(r.city.sim.workVisits>0);assert.equal(r.city.sim.carTrips,0);assert(r.routes.some(({value})=>value?.mode===2&&value.cost<0)||r.routes.some(([k,v])=>v.mode===2&&v.cost<0))});
const first=run('native-journeys-long-run',{rows:-1,ticks:600},r=>{assert(r.city.sim.workVisits>0);assert(r.city.sim.shopVisits>0);assert(r.city.sim.leisureVisits>0);assert(r.city.sim.walkTrips>0);assert(r.city.sim.carTrips>0);assert(r.agents.some(a=>a.journeys>=4));});
run('deterministic-replay',{rows:-1,ticks:600},r=>assert.deepEqual(r,first));
const improved=run('nearby-employment-changes-travel',{rows:-1,ticks:600,commands:[build(6,9,6,9,4),build(9,9,9,9,4)]},r=>{assert.equal(r.city.sim.disconnected,0);assert(r.city.sim.walkTrips>first.city.sim.walkTrips);assert(r.city.sim.visits>first.city.sim.visits);assert(r.city.sim.totalDuration/r.city.sim.arrived<first.city.sim.totalDuration/first.city.sim.arrived)});
run('long-route-cache-is-bounded',{rows:-1,ticks:1800},r=>assert(r.city.sim.routes.length<200));
fs.writeFileSync('evidence/correctness.json',JSON.stringify({passed:true,artifact_sha256:selection.artifact_sha256,report,comparison:{baseline:first.city.sim,nearbyEmployment:improved.city.sim}},null,2));
