import assert from 'node:assert/strict';import fs from 'node:fs';import {runCase,selection} from './run-case.mjs';
const checks=[],command=(op,x=0,y=0,x2=0,y2=0,kind=0)=>({op,x,y,x2,y2,kind}),id=(x,y)=>x+128*y;
function invariant(r){const c=r.city,s=c.sim,e=c.economy;assert.equal(r.conservation,0);assert.equal(s.population,s.born-s.removed);assert.equal(s.population,r.agents.length);assert(c.cash>=0);assert.equal(c.cash+e.households+e.businesses,e.opening+e.grants+e.exports+e.salvage-e.construction-e.operating-e.withdrawn,'money conservation');assert.equal(e.households,e.wallets.reduce((n,[,v])=>n+v,0));assert.equal(e.businesses,e.firms.reduce((n,[,v])=>n+v,0));assert(e.wallets.every(([,v])=>v>=0));assert(e.firms.every(([,v])=>v>=0));const people=new Map(s.agents),plans=new Map(s.transit.plans),seen=new Set();for(const[,l]of s.transit.lines){assert(l.passengers.length<=16);for(const rider of l.passengers){assert(!seen.has(rider));seen.add(rider);assert.equal(people.get(rider).state,6);assert.equal(plans.get(rider).line,l.id)}for(const[key,q]of l.queues){assert.equal(new Set(q).size,q.length);for(const rider of q){assert.equal(people.get(rider).state,5);assert.equal(plans.get(rider).board,Math.floor(key/2));assert.equal(plans.get(rider).line,l.id)}}for(let i=1;i<l.path.length;i++)assert.equal(Math.abs(l.path[i]%128-l.path[i-1]%128)+Math.abs(Math.floor(l.path[i]/128)-Math.floor(l.path[i-1]/128)),1)}for(const[k,n]of r.lanes)if([1,2].includes(new Map(c.world.tiles).get(Math.floor(k/8))))assert(n<=3)}
function advance(city,ticks=0,commands=[],name='probe'){const result=runCase({city,ticks,commands,after:[]},'expansion-'+name,'continuation');invariant(result.result);return result}
const seeds=['garden','crossing','metro'].map((name,i)=>{const r=runCase(i+1,'scenario-seed-'+name,'scenario-seed');fs.writeFileSync('runtime/'+name+'-seed.json',JSON.stringify(r.result));assert.equal(r.result.sim.population,[384,256,512][i]);invariant(advance(r.result).result);return r.result});
const metro=seeds[2];assert.equal(metro.sim.transit.ids.length,2);for(const[,l]of metro.sim.transit.lines){assert.equal(l.stops.length,3);assert(l.path.length>20);assert(l.enabled);assert.notEqual(l.a%128,l.b%128);assert.notEqual(Math.floor(l.a/128),Math.floor(l.b/128));}checks.push('owned 256/384/512 cities and two curved three-stop services construct with exact accounting');
const malformed=[command('build-track',-1,3,6,3),command('build-track',1,1,127,127),command('build-track',1,1,3,3,2),command('build-station',-1,0),command('create-service',Number.MAX_SAFE_INTEGER,0,1,1),command('rail-stop',1,-100),command('rail-stop',1,metro.sim.transit.lines[0][1].a),command('build',59,61,59,61,3)];for(const c of malformed)assert.deepEqual(advance(metro,0,[c]).result.city,metro);checks.push('malformed coordinates, oversized track, duplicate stops and protected station edits reject atomically');
for(let i=0;i<seeds.length;i++){const name=['garden','crossing','metro'][i],r=advance(seeds[i],256,[],name+'-warm'),city=r.result.city;assert(city.sim.visits>0);assert.equal(city.economy.upkeepDue,0);assert(city.economy.exports>0);assert(city.economy.wages>0);assert(city.economy.taxes>0);if(i===2){assert(city.sim.transit.boardings>0);assert(city.sim.transit.completed>0)}fs.writeFileSync('runtime/'+name+'-warm.json',JSON.stringify(city));checks.push({name:name+' sustained 256 cycles',wall_ms:r.wall_ms,cash:city.cash,arrived:city.sim.arrived,visits:city.sim.visits,waiting:city.sim.waiting,disconnected:city.sim.disconnected,healthy:city.sim.healthy,economy:city.economy,exports:city.economy.exports,boardings:city.sim.transit.boardings});}
const before=JSON.parse(fs.readFileSync('runtime/crossing-warm.json'));const fix=[command('build',63,59,67,59,2),command('build',63,42,63,70,2),command('build',67,42,67,70,2)];const baseline=advance(before,320,[],'challenge-before'),improved=advance(before,320,fix,'challenge-after');assert(improved.result.city.sim.arrived>baseline.result.city.sim.arrived);assert(improved.result.city.cash>=0);checks.push({name:'crossing challenge has a reachable useful recovery',baseline:baseline.result.city.sim.arrived,improved:improved.result.city.sim.arrived,cash:improved.result.city.cash});
const replay=advance(seeds[0],64,[],'replay-a').result;assert.deepEqual(advance(seeds[0],64,[],'replay-b').result,replay);checks.push('exact native economy/traffic replay');
const report={passed:true,artifact_sha256:selection.artifact_sha256,checks};fs.writeFileSync('evidence/expansion.json',JSON.stringify(report,null,2));console.log(JSON.stringify({passed:true,checks:checks.map(x=>typeof x==='string'?x:{...x,economy:undefined})},null,2));
