import {selectTool,districtPoint} from './ui-driver.mjs';
// Real browser touch input via Chromium's input dispatcher; no synthetic pointer events for primary gestures.
import {createRequire} from 'node:module';const {chromium}=createRequire(import.meta.url)('playwright');import assert from 'node:assert/strict';import fs from 'node:fs';
const selectedArtifact=JSON.parse(fs.readFileSync(process.env.CITY_SELECTION||'.build/selection.json')).artifact_sha256;
const url=process.env.PREVIEW_URL||'http://127.0.0.1:19140/?session_port=19141',prefix=process.env.GESTURE_EVIDENCE||'evidence/gestures';
const browser=await chromium.launch({executablePath:process.env.CHROMIUM||undefined,headless:true,args:['--no-sandbox']});const checks=[],errors=[];
const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));const cdp=await context.newCDPSession(page);
const state=()=>page.evaluate(()=>({camera:window.__flowgarden.camera,cash:window.__flowgarden.stats.cash,version:window.__flowgarden.stats.version,pointers:window.__flowgarden.pointerCount,gesture:window.__flowgarden.gesture,draft:window.__flowgarden.draft,builds:window.__flowgarden.sentCommands.filter(c=>['build','build-rail'].includes(c.op)).length}));
const point=(x,y)=>districtPoint(page,x,y);
async function touch(type,points=[]){await cdp.send('Input.dispatchTouchEvent',{type,touchPoints:points.map(p=>({...p,radiusX:6,radiusY:6,force:1}))});await page.waitForTimeout(25)}
async function fit(){await page.tap('#fit');await page.waitForTimeout(180)}
async function stroke(a,b){await touch('touchStart',[{id:1,...a}]);for(let i=1;i<=7;i++)await touch('touchMove',[{id:1,x:a.x+(b.x-a.x)*i/7,y:a.y+(b.y-a.y)*i/7}]);await touch('touchEnd')}
try{
 await page.goto(url);await page.waitForFunction(()=>window.__flowgarden?.sessionStatus===1);await page.waitForTimeout(350);assert.equal(await page.evaluate(()=>window.__flowgarden.tool),-2);
 const gestureStarted=Date.now();const initial=await state();await stroke({x:185,y:370},{x:237,y:404});let f=await state();assert(Math.hypot(f.camera.x-initial.camera.x,f.camera.y-initial.camera.y)>1);assert.equal(f.cash,900);assert.equal(f.builds,0);assert.equal(f.pointers,0);checks.push('one-finger pan is the default; no road command');
 await fit();const mid={x:194,y:390};const anchor=await page.evaluate(p=>window.__flowgarden.screenToWorld(p),mid);const before=(await state()).camera.scale;await touch('touchStart',[{id:1,x:159,y:390},{id:2,x:229,y:390}]);for(let i=1;i<=8;i++)await touch('touchMove',[{id:1,x:159-i*5,y:390},{id:2,x:229+i*5,y:390}]);await touch('touchEnd');const after=await page.evaluate(p=>window.__flowgarden.screenToWorld(p),mid);assert((await state()).camera.scale>before*1.9);assert(Math.hypot(anchor.x-after.x,anchor.y-after.y)<.03);checks.push('pinch zoom preserves the world point under the fingers');
 for(let pass=0;pass<3;pass++){await touch('touchStart',[{id:1,x:140,y:370},{id:2,x:240,y:370}]);await touch('touchMove',[{id:1,x:130,y:390},{id:2,x:250,y:390}]);await touch('touchEnd');assert.equal((await state()).pointers,0)}checks.push('repeated pinch and two-finger translation finish cleanly');
 for(const tool of [2,0,8]){await selectTool(page,tool);await fit();const a=await point(14,10),b=await point(15,10),start=await state();await touch('touchStart',[{id:1,...a}]);await touch('touchMove',[{id:1,...b}]);assert((await state()).draft);await touch('touchStart',[{id:1,...b},{id:2,x:b.x+70,y:b.y+40}]);assert.equal((await state()).draft,null);await touch('touchMove',[{id:1,x:b.x+5,y:b.y+10},{id:2,x:b.x+90,y:b.y+50}]);
 // CDP touchEnd with one contact releases that contact; omitting it from touchMove does not.
 await touch('touchEnd',[{id:2,x:b.x+90,y:b.y+50}]);assert.equal((await state()).pointers,1);await touch('touchMove',[{id:1,x:b.x+30,y:b.y+20}]);await touch('touchEnd');f=await state();assert.equal(f.builds,start.builds);assert.equal(f.cash,start.cash);assert.equal(f.pointers,0);assert.equal(f.draft,null);checks.push((tool===0?'erase':tool===8?'rail':'road')+' preview cancelled by second finger; remaining finger cannot build');}
 await selectTool(page,2);await fit();let a=await point(14,10),b=await point(15,10);const start=await state();await touch('touchStart',[{id:1,...a}]);await touch('touchMove',[{id:1,...b}]);await touch('touchCancel');assert.equal((await state()).pointers,0);assert.equal((await state()).draft,null);assert.equal((await state()).builds,start.builds);checks.push('touchcancel discards construction and clears captured pointers');
 await touch('touchStart',[{id:1,...a}]);await page.setViewportSize({width:844,height:390});await page.waitForTimeout(120);assert.equal((await state()).pointers,0);assert.equal((await state()).draft,null);await touch('touchEnd');await page.setViewportSize({width:390,height:844});await page.waitForTimeout(160);await fit();assert.equal((await state()).builds,start.builds);checks.push('orientation/resize cancels an active stroke without a stuck gesture');
 a=await point(14,10);b=await point(15,10);await stroke(a,b);await page.waitForFunction(()=>window.__flowgarden.stats.cash===756);assert.equal((await state()).builds,start.builds+1);checks.push('fresh one-finger road stroke after interruptions upgrades both bridge tiles at their new $72-per-water-tile price ($144 total)');
 await selectTool(page,3);await fit();a=await point(4,10);await touch('touchStart',[{id:1,...a}]);await touch('touchEnd');await page.waitForFunction(()=>window.__flowgarden.stats.cash===686);assert.equal(await page.evaluate(()=>window.__flowgarden.cells.find(c=>c.id===4+window.__flowgarden.stats.originX+(10+window.__flowgarden.stats.originY)*128)?.kind),3);checks.push('touch placement selects the correct native grid tile after camera transforms');
 for(let i=0;i<12;i++)await page.tap('#zoom-in');f=await state();assert(f.camera.scale<=f.camera.max+.001);for(let i=0;i<18;i++)await page.tap('#zoom-out');f=await state();assert(f.camera.scale>=f.camera.min-.001);assert.equal(f.cash,686);checks.push('zoom limits remain bounded and never submit construction');await fit();await selectTool(page,-2);await page.screenshot({path:prefix+'-mobile.png'});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);assert((await page.locator('#map').boundingBox()).height>=830);
 const cameraCommands=await page.evaluate(()=>window.__flowgarden.sentCommands.filter(c=>c.op==='view'));assert(cameraCommands.every(c=>c.x2>=1&&c.y2>=1&&c.x2<=128&&c.y2<=128));assert(cameraCommands.length<=(Date.now()-gestureStarted)/160+2);checks.push('camera requests are coalesced and viewports cover up to the full 128×128 city; server chooses detail');
 const desktop=await browser.newPage({viewport:{width:1440,height:1000}});desktop.on('pageerror',e=>errors.push(e.message));await desktop.goto(url);await desktop.waitForFunction(()=>window.__flowgarden?.sessionStatus===1);await desktop.waitForTimeout(250);const dp=(x,y)=>districtPoint(desktop,x,y);
 await desktop.mouse.move(650,400);const mouseAnchor=await desktop.evaluate(()=>window.__flowgarden.screenToWorld({x:650,y:400}));await desktop.mouse.wheel(0,-250);await desktop.waitForTimeout(100);const mouseAfter=await desktop.evaluate(()=>window.__flowgarden.screenToWorld({x:650,y:400}));assert(Math.hypot(mouseAnchor.x-mouseAfter.x,mouseAnchor.y-mouseAfter.y)<.03);checks.push('mouse wheel zoom is anchored at the cursor');
 await selectTool(desktop,2);await desktop.locator('#fit').click();let p=await dp(14,10);await desktop.mouse.move(p.x,p.y);await desktop.mouse.down();await desktop.mouse.move(-12,p.y,{steps:6});await desktop.mouse.up();assert.equal(await desktop.evaluate(()=>window.__flowgarden.sentCommands.filter(c=>['build','build-rail'].includes(c.op)).length),0);checks.push('leaving the canvas while drawing cancels the stroke');
 await desktop.locator('#fit').click();p=await dp(14,10);await desktop.mouse.move(p.x,p.y);await desktop.keyboard.down('Shift');await desktop.mouse.down();await desktop.mouse.move(p.x+70,p.y+40,{steps:6});await desktop.mouse.up();await desktop.keyboard.up('Shift');assert.equal(await desktop.evaluate(()=>window.__flowgarden.sentCommands.filter(c=>['build','build-rail'].includes(c.op)).length),0);checks.push('Shift-drag pans even with a road tool selected');
 await desktop.locator('#fit').click();p=await dp(14,10);await desktop.mouse.move(p.x,p.y);await desktop.mouse.down();await desktop.keyboard.press('Escape');await desktop.mouse.up();assert.equal(await desktop.evaluate(()=>window.__flowgarden.pointerCount),0);assert.equal(await desktop.evaluate(()=>window.__flowgarden.sentCommands.filter(c=>['build','build-rail'].includes(c.op)).length),0);checks.push('Escape clears captured drawing state');
 // Capture loss and focus loss are real browser lifecycle operations; primary gestures above use native input dispatch.
 await selectTool(desktop,2);await desktop.locator('#fit').click();p=await dp(14,10);await desktop.evaluate(()=>document.getElementById('map').addEventListener('pointerdown',e=>window.__capturedTestPointer=e.pointerId,{once:true}));await desktop.mouse.move(p.x,p.y);await desktop.mouse.down();await desktop.mouse.move(p.x+1,p.y);await desktop.evaluate(()=>document.getElementById('map').releasePointerCapture(window.__capturedTestPointer));await desktop.mouse.move(p.x+4,p.y);await desktop.mouse.up();assert.equal(await desktop.evaluate(()=>window.__flowgarden.pointerCount),0);assert.equal(await desktop.evaluate(()=>window.__flowgarden.sentCommands.filter(c=>['build','build-rail'].includes(c.op)).length),0);checks.push('lost pointer capture cancels the draft without a build');
 await desktop.mouse.move(p.x,p.y);await desktop.mouse.down();await desktop.mouse.wheel(0,-120);await desktop.mouse.up();assert.equal(await desktop.evaluate(()=>window.__flowgarden.pointerCount),0);assert.equal(await desktop.evaluate(()=>window.__flowgarden.sentCommands.filter(c=>['build','build-rail'].includes(c.op)).length),0);checks.push('wheel zoom during a road stroke discards the draft');
 await desktop.locator('#fit').click();p=await dp(14,10);await desktop.mouse.move(p.x,p.y);await desktop.mouse.down({button:'right'});await desktop.mouse.move(p.x+60,p.y+20,{steps:4});await desktop.mouse.up({button:'right'});assert.equal(await desktop.evaluate(()=>window.__flowgarden.sentCommands.filter(c=>['build','build-rail'].includes(c.op)).length),0);checks.push('right-button drag pans in a construction tool');
 await desktop.locator('#fit').click();await selectTool(desktop,2);p=await dp(14,10);const q=await dp(15,10);await desktop.mouse.move(p.x,p.y);await desktop.mouse.down();await desktop.mouse.move(q.x,q.y,{steps:6});await desktop.mouse.up();await desktop.waitForFunction(()=>window.__flowgarden.stats.cash===756);checks.push('mouse road drawing still commits after cancelled gestures');await desktop.screenshot({path:prefix+'-desktop.png'});assert.deepEqual(errors,[]);
 const report={passed:true,url,artifact_sha256:selectedArtifact,input:'Chromium Input.dispatchTouchEvent (real browser touch/pointer dispatch), mouse and keyboard',checks,errors,mobile_camera:(await state()).camera,render_ms:await page.evaluate(()=>{const a=window.__flowgarden.frameTimes.slice().sort((a,b)=>a-b);return{samples:a.length,median:a[Math.floor(a.length/2)],p95:a[Math.floor(a.length*.95)]}}),limitations:['Browser touch emulation is not a physical iPhone hardware test.']};fs.writeFileSync(prefix+'.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));await desktop.close();
}finally{await browser.close()}
