import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {randomBytes} from 'node:crypto';import {spawn,spawnSync} from 'node:child_process';import {once} from 'node:events';import {startNative,connect,root} from './native.mjs';
let n=await startNative({name:'maintenance-seed',tick:30}),c,supervisor;const key=randomBytes(32).toString('hex'),checks=[];let seq=0;
async function command(op,fields={}){const id=++seq;c.socket.send(JSON.stringify({id,token:op==='resume'?key:'',owner:op==='resume'?randomBytes(16).toString('hex'):'',action:{op,x:0,y:0,x2:0,y2:0,kind:0,...fields}}));return c.wait(f=>f.ack===id)}
async function poll(test,ms=20000){const until=Date.now()+ms;while(Date.now()<until){if(test())return;await new Promise(r=>setTimeout(r,100))}throw Error('Maintenance timed out')}
function run(cwd,...args){return spawnSync(args[0],args.slice(1),{cwd,encoding:'utf8'})}
try{
 c=connect(n.address);await c.wait(f=>f.seq===1);await command('resume');const saved=(await command('build',{x:20,y:18,x2:20,y2:18,kind:1})).stats;for(let i=0;i<20;i++)await command('save');await c.close();await n.stop();
 const sandbox=fs.mkdtempSync(root+'/runtime/maintenance-supervisor-');for(const p of ['scripts','tools/lkjscript','runtime/data-v4'])fs.mkdirSync(sandbox+'/'+p,{recursive:true});for(const f of ['serve-native.sh','maintain-saves.sh'])fs.copyFileSync(root+'/scripts/'+f,sandbox+'/scripts/'+f);fs.symlinkSync(n.selection.bin,sandbox+'/tools/lkjscript/lkjscript');fs.renameSync(n.dir+'/data',sandbox+'/runtime/data-v4/store');fs.writeFileSync(sandbox+'/runtime/data-v4/INITIALIZED','');fs.copyFileSync(n.selection.artifact,sandbox+'/runtime/app.lkja');
 const session={...n.config,artifact:'app.lkja'};session.grants.find(g=>g.requirement==='data').adapter.root='data-v4/store';fs.writeFileSync(sandbox+'/runtime/session.deployment.json',JSON.stringify(session));const http=JSON.parse(fs.readFileSync(root+'/runtime/http.deployment.json'));http.artifact='app.lkja';http.listen='127.0.0.1:0';fs.writeFileSync(sandbox+'/runtime/http.deployment.json',JSON.stringify(http));
 const before=Number(run(sandbox,'du','-sk','runtime/data-v4/store').stdout.split(/\s/)[0]),watermark=16;supervisor=spawn('bash',['scripts/serve-native.sh'],{cwd:sandbox,env:{...process.env,SAVE_HISTORY_KIB:String(watermark)}});let output='';supervisor.stdout.on('data',b=>{output+=b});supervisor.stderr.on('data',b=>{output+=b});const log=sandbox+'/runtime/logs/maintenance.log';await poll(()=>fs.existsSync(log)&&fs.readFileSync(log,'utf8').includes('native save history compacted'));
 const ready=()=>fs.readFileSync(sandbox+'/runtime/logs/session.log','utf8').trim().split('\n').filter(l=>l.includes('"event":"ready"'));await poll(()=>ready().length>=2);const address=JSON.parse(ready().at(-1)).local_address;seq=0;c=connect(address);await c.wait(f=>f.seq===1);assert.deepEqual((await command('resume')).stats,saved);await c.close();const after=Number(run(sandbox,'du','-sk','runtime/data-v4/store').stdout.split(/\s/)[0]);assert(after<before);assert(after>watermark);await new Promise(resolve=>setTimeout(resolve,2500));assert.equal(ready().length,2,'compacted values above the base watermark must not cause a restart loop');checks.push('supervisor compacts history, preserves city, and avoids restart loops when retained values exceed the base watermark');const ended=once(supervisor,'exit');supervisor.kill('SIGTERM');await ended;supervisor=null;
 fs.renameSync(sandbox+'/runtime/data-v4/store',sandbox+'/runtime/data-v4/retired');let r=run(sandbox,'bash','scripts/maintain-saves.sh');assert.equal(r.status,0,r.stdout+r.stderr);assert(fs.existsSync(sandbox+'/runtime/data-v4/store/HEAD'));checks.push('interrupted rename recovers retained original store');
 fs.renameSync(sandbox+'/runtime/data-v4/store',sandbox+'/runtime/data-v4/held');r=run(sandbox,'bash','scripts/maintain-saves.sh');assert.notEqual(r.status,0);assert(r.stderr.includes('refusing to reset'));assert(!fs.existsSync(sandbox+'/runtime/data-v4/store'));fs.renameSync(sandbox+'/runtime/data-v4/held',sandbox+'/runtime/data-v4/store');checks.push('missing initialized store is refused without silent reset');
 const report={passed:true,artifact_sha256:n.selection.artifact_sha256,checks,before_kib:before,watermark_kib:watermark,after_kib:after};fs.writeFileSync(root+'/evidence/maintenance.json',JSON.stringify(report,null,2));console.log(report);
}finally{if(c)await c.close().catch(()=>{});if(supervisor){const ended=once(supervisor,'exit');supervisor.kill('SIGTERM');await ended}if(n.child.exitCode===null&&n.child.signalCode===null)await n.stop()}
