import fs from 'node:fs';import assert from 'node:assert/strict';import {randomBytes} from 'node:crypto';import {startNative,connect,root} from './native.mjs';
let n,c,seq=0;const key=randomBytes(32).toString('hex'),checks=[];
async function command(op,fields={}){const id=++seq;c.socket.send(JSON.stringify({id,token:op==='resume'?key:'',owner:op==='resume'?randomBytes(16).toString('hex'):'',action:{op,x:0,y:0,x2:0,y2:0,kind:0,...fields}}));return c.wait(f=>f.ack===id)}
async function open(){seq=0;c=connect(n.address);await c.wait(f=>f.seq===1);return command('resume')}
const build=(x,y,x2,y2,kind=1)=>command('build',{x,y,x2,y2,kind});
const sameCity=(a,b)=>assert.deepEqual(a.stats,b.stats);
try{
 n=await startNative({name:'management',tick:20});let current=await open();assert.equal(current.status,1);assert.equal(current.stats.originX,50);assert.equal(current.stats.originY,54);const initial=current;const kinds=new Map(current.overview.map(v=>[Math.floor(v/16),v%16]));assert(kinds.has(55+60*128));assert(kinds.has(73+67*128));assert(!kinds.has(5+6*128));checks.push('new city occupies the actual center, with terrain origin in native state');
 for(let y=48;y<=50;y++)current=await build(45,y,47,y);const beforeArea=current;
 const quote=await command('review-remove',{x:47,y:50,x2:45,y2:48});assert(quote.quote.valid);assert.equal(quote.quote.tiles,9);assert.equal(quote.quote.refund,36);sameCity(quote,beforeArea);
 current=await command('apply-remove',{x:quote.quote.id+1});sameCity(current,beforeArea);assert(!current.quote.valid);checks.push('reverse rectangle selection counts all nine cells; wrong quote cannot apply');
 let q=await command('review-remove',{x:45,y:48,x2:47,y2:50});await command('cancel-review');current=await command('apply-remove',{x:q.quote.id});sameCity(current,beforeArea);checks.push('cancelled review is not reusable');
 q=await command('review-remove',{x:45,y:48,x2:47,y2:50});current=await command('apply-remove',{x:q.quote.id});assert.equal(current.stats.tiles,beforeArea.stats.tiles-9);assert.equal(current.stats.cash,beforeArea.stats.cash+36);assert.equal(current.stats.version,beforeArea.stats.version+1);const afterArea=current;current=await command('apply-remove',{x:q.quote.id});sameCity(current,afterArea);checks.push('rectangle commits once, refunds exactly, and replay does not refund twice');
 for(const fields of [{x:-1,y:0,x2:0,y2:0},{x:0,y:0,x2:128,y2:1},{x:0,y:0,x2:127,y2:127},{x:0,y:0,x2:0,y2:0}]){current=await command('review-remove',fields);assert(!current.quote.valid);sameCity(current,afterArea)}checks.push('invalid, excessive and empty rectangles cannot mutate or charge');
 current=await command('reset-city');sameCity(current,afterArea);let reset=await command('review-reset');assert.equal(reset.management,1);await command('cancel-review');current=await command('reset-city',{x:reset.confirmation});sameCity(current,afterArea);checks.push('reset requires a current confirmation; cancel retains city');
 reset=await command('review-reset');current=await command('reset-city',{x:reset.confirmation});assert.equal(current.stats.tick,0);assert.equal(current.stats.cash,900);assert(current.undo);const fresh=current;await c.close();current=await open();sameCity(current,fresh);assert(current.undo);checks.push('reset reuses the private city slot and previous-city backup survives reconnect');
 const restore=await command('review-restore');current=await command('restore-city',{x:restore.confirmation});sameCity(current,afterArea);assert(!current.undo);current=await command('restore-city',{x:restore.confirmation});sameCity(current,afterArea);checks.push('one native restore recovers exact previous city; repeated restore cannot replay');
 await command('set-running',{kind:1});await c.wait(f=>f.stats.tick>=22,60000);current=await command('set-running',{kind:0});const trafficBefore=current;const residents=[];for(let id=1;id<=32;id++)residents.push((await command('inspect',{kind:id})).inspect);const activeBefore=residents.filter(r=>[1,2,4].includes(r.state)).length;
 q=await command('review-remove',{x:55,y:60,x2:55,y2:60});assert.equal(q.quote.homes,1);assert.equal(q.quote.moveouts,8);current=await command('apply-remove',{x:q.quote.id});assert.equal(current.stats.population,24);assert.equal(current.stats.cash,trafficBefore.stats.cash+35);assert.equal(current.stats.permits,trafficBefore.stats.permits+1);assert.equal(current.stats.cancelled,trafficBefore.stats.cancelled+q.quote.cancelled);assert.equal(current.stats.arrived,trafficBefore.stats.arrived);const remaining=[];for(let id=1;id<=32;id++){const r=(await command('inspect',{kind:id})).inspect;if(r.id>0)remaining.push(r)}assert.equal(remaining.length,24);assert(remaining.every(r=>r.home!==55+60*128));assert.equal(current.stats.requested,current.stats.arrived+current.stats.cancelled+remaining.filter(r=>[1,2,4].includes(r.state)).length);checks.push('occupied home demolition accounts for eight moveouts, cancelled journeys and returned permit without visit income');
 await command('set-running',{kind:1});await c.wait(f=>f.stats.tick>=trafficBefore.stats.tick+120,90000);current=await command('set-running',{kind:0});assert(current.stats.arrived>trafficBefore.stats.arrived);await c.close();current=await open();assert.equal(current.stats.population,24);assert(current.stats.cancelled>=q.quote.cancelled);checks.push('remaining residents continue and the cancellation ledger survives reload');
 const report={passed:true,artifact_sha256:n.selection.artifact_sha256,checks,stats:current.stats};fs.writeFileSync(root+'/evidence/management.json',JSON.stringify(report,null,2));console.log(report);
}finally{if(c)await c.close().catch(()=>{});if(n)await n.stop().catch(()=>{})}
