import fs from 'node:fs';import assert from 'node:assert/strict';import {randomBytes} from 'node:crypto';import {startNative,connect,root} from './native.mjs';
const latest=process.env.CITY_SELECTION||root+'/.build/selection.json',old=process.env.OLD_CITY_SELECTION||root+'/.build/deployed-before-management.json',key=randomBytes(32).toString('hex');let n,c,seq=0;const checks=[];
async function open(){seq=0;c=connect(n.address);await c.wait(f=>f.seq===1);return command('resume')}
async function command(op,fields={}){const id=++seq;c.socket.send(JSON.stringify({id,token:op==='resume'?key:'',owner:op==='resume'?randomBytes(16).toString('hex'):'',action:{op,x:0,y:0,x2:0,y2:0,kind:0,...fields}}));return c.wait(f=>f.ack===id)}
async function people(){const all=[];for(let id=1;id<=32;id++)all.push((await command('inspect',{kind:id})).inspect);return all}
try{
 process.env.CITY_SELECTION=old;n=await startNative({name:'migration-v4',tick:15});await open();if(process.env.MIGRATION_WITH_RAIL==='1'){const f=await command('build-rail',{x:56,y:65,x2:72,y2:65});assert.equal(f.rails.length,1,f.notice);assert.equal(f.rails[0].enabled,true)}const topology=(await command('build',{x:14,y:10,x2:15,y2:10,kind:2})).overview;await command('pause');await c.wait(f=>f.stats.tick>=120,60000);await command('pause');const oldFrame=await command('save'),saved=oldFrame.stats,oldRails=oldFrame.rails;if(process.env.MIGRATION_WITH_RAIL==='1')assert(oldRails[0].departures>0);const before=await people();await c.close();const dir=n.dir;await n.stop();
 process.env.CITY_SELECTION=latest;n=await startNative({name:'migration-v5',tick:15,directory:dir});const restored=await open();assert.equal(restored.status,1);assert.deepEqual(restored.overview,topology);for(const [k,v] of Object.entries(saved))assert.deepEqual(restored.stats[k],v,k);assert.equal(restored.stats.originX,saved.originX||0);assert.equal(restored.stats.originY,saved.originY||0);assert.equal(restored.stats.cancelled,saved.cancelled||0);assert.deepEqual(await people(),before);assert.equal(restored.rails.length,oldRails.length);for(let i=0;i<oldRails.length;i++){for(const [k,v] of Object.entries(oldRails[i]))assert.deepEqual(restored.rails[i][k],v,'legacy rail '+k);if(!Object.hasOwn(oldRails[i],'stops'))assert.equal(restored.rails[i].stops.length,2);if(!Object.hasOwn(oldRails[i],'path'))assert(restored.rails[i].path.length>1)}checks.push('actual predecessor typed save migrates with every resident field, coordinate, static tile, route ID and prior statistic unchanged');
 await command('set-running',{kind:1});await c.wait(f=>f.stats.tick>=saved.tick+180,90000);let current=await command('set-running',{kind:0});assert(current.stats.arrived>saved.arrived);const afterPeople=await people();const after=current.stats;await c.close();await n.stop();n=await startNative({name:'migration-restart',tick:15,directory:dir});current=await open();assert.deepEqual(current.stats,after);assert.deepEqual(await people(),afterPeople);checks.push('migrated city continues, checkpoints in current format and survives process restart with exact residents');
 const reset=await command('review-reset');current=await command('reset-city',{x:reset.confirmation});assert.equal(current.stats.originX,50);const restore=await command('review-restore');current=await command('restore-city',{x:restore.confirmation});assert.deepEqual(current.stats,after);assert.deepEqual(await people(),afterPeople);checks.push('reset from an old coordinate system and undo restores the old terrain and every resident exactly');
 const report={passed:true,old_artifact_sha256:JSON.parse(fs.readFileSync(old)).artifact_sha256,new_artifact_sha256:JSON.parse(fs.readFileSync(latest)).artifact_sha256,checks,before:saved,after};fs.writeFileSync(root+'/'+(process.env.MIGRATION_EVIDENCE||'evidence/migration.json'),JSON.stringify(report,null,2));console.log(report);
}finally{process.env.CITY_SELECTION=latest;if(c)await c.close().catch(()=>{});if(n)await n.stop().catch(()=>{})}
