// Synthetic arrival schedules exercise only presentation of committed snapshots.
// No native city is advanced, no path/route is invented, no player store is read.
import fs from 'node:fs';import assert from 'node:assert/strict';import{TrafficMotion,PresentationClock,transitionPose}from'../web/motion.js';
const center=50+50*128,cells=new Map(Array.from({length:105},(_,i)=>[center-25+i,{kind:2}])),checks=[];
const actor=(tick,id=1)=>({id,mode:2,from:center+tick,to:center+tick+1,dir:0,out:0,lane:0,rank:0,elapsed:0,duration:1});
const frame=(tick,extras={})=>({stats:{tick,version:1,paused:false},view:{layer:0},mapChanged:false,actors:[actor(tick)],rails:[{id:1,elapsed:tick,duration:100}],...extras});
function schedule(gaps){const m=new TrafficMotion(),samples=[];let at=0,old,stall=0,maxStall=0;
 gaps.forEach((gap,tick)=>{m.receive(frame(tick),at,cells);for(let ms=0;ms<gap-1e-5;ms+=1000/60){const now=at+ms,p=m.sample(now)[0];assert(m.time<=tick);assert(m.time>=0);if(old&&tick>=8){assert(m.time>=old.time-1e-12);const dt=now-old.now;if(dt>8){const moved=Math.hypot(p.x-old.x,p.y-old.y)>1e-7;samples.push(moved);stall=moved?0:stall+dt;maxStall=Math.max(maxStall,stall)}}old={...p,now,time:m.time}}at+=gap});
 assert(m.frames.size<=8);assert(m.railFrames.size<=8);return{samples:samples.length,stationaryFraction:samples.filter(x=>!x).length/samples.length,maxStallMs:maxStall,periodMs:m.diagnostics.periodMs};}
const measurements={};for(const gap of[500,1000,2000]){const r=schedule(Array(48).fill(gap));assert(r.stationaryFraction<.015,JSON.stringify(r));assert(r.maxStallMs<35);measurements['fixed'+gap]=r}
measurements.jitter=schedule(Array.from({length:60},(_,i)=>[500,700,550,1050,450,800][i%6]));assert(measurements.jitter.stationaryFraction<.05);assert(measurements.jitter.maxStallMs<120,JSON.stringify(measurements.jitter));checks.push('500/1,000/2,000 ms cadences and bounded arrival jitter remain smooth without extrapolating beyond received ticks');
const a=new PresentationClock(),b=new PresentationClock();a.receive(0,0);b.receive(0,0);
for(let tick=1;tick<=16;tick++){for(let sub=0;sub<8;sub++){const now=(tick-1)*800+sub*100;a.sample(now);b.sample(now);b.receive(tick-1,now);assert.equal(a.time,b.time)}a.receive(tick,tick*800);b.receive(tick,tick*800);assert.deepEqual(a.diagnostics,b.diagnostics)}checks.push('Repeated same-tick save/inspect/view replies do not contaminate cadence or reset playback');
const paused=new TrafficMotion();paused.receive(frame(0),0,cells);paused.receive(frame(1),1000,cells);const before=paused.sample(1100)[0];paused.receive(frame(1,{stats:{tick:1,version:1,paused:true}}),1100,cells);const after=paused.sample(1100)[0];assert.deepEqual(after,before);paused.sample(1450);assert.equal(paused.time,1);paused.receive(frame(2),10000,cells);assert(paused.diagnostics.periodMs<2000);assert.equal(paused.sample(10001,true).length,1);assert.equal(paused.time,2);checks.push('Pause settles continuously, resume excludes the paused interval, and reduced-motion still shows the exact committed snapshot');
const cache=new TrafficMotion();cache.receive(frame(4),0,cells);cache.receive(frame(5),500,cells);for(let i=0;i<300;i++){const now=500+i;const pose=cache.sample(now)[0],pair=cache.pair(cache.frames,cache.time),lo=cache.frames.get(pair.lo).get(1),hi=cache.frames.get(pair.hi).get(1),expected=transitionPose(lo,hi,pair.t,cells);assert(Math.hypot(pose.x-expected.x,pose.y-expected.y)<1e-12);const rail=cache.sampleRails(now)[0];assert.equal(rail.mix,pair.t);assert.equal(rail.current.elapsed,pair.hi);assert.equal(rail.previous.elapsed,pair.lo)}assert(cache.preparations<=2);const compiledFor300Frames=cache.preparations;checks.push('Cached geometry matches the reference interpolation exactly across 300 redraws; cars and trains share one timeline');
const settled=cache.sample(900)[0];cache.receive(frame(5),900,cells);assert.deepEqual(cache.sample(900)[0],settled);cache.sample(1e7);assert.equal(cache.time,cache.latest);checks.push('Same-tick replies preserve visible position and a missing network update can never extrapolate an unreceived journey');
cache.receive(frame(5,{view:{layer:1},actors:[]}),1e7+1,cells);assert.deepEqual(cache.sample(1e7+1),[]);assert.equal(cache.frames.size,1);cache.receive(frame(0,{stats:{tick:0,version:2,paused:true}}),1e7+2,cells);assert.equal(cache.time,0);assert.equal(cache.railFrames.size,1);checks.push('Layer changes and topology/time resets clear old geometry and ghost snapshots');
const report={passed:true,checks,measurements,geometryPreparationsFor300Frames:compiledFor300Frames};fs.mkdirSync('evidence',{recursive:true});fs.writeFileSync('evidence/motion-timing.json',JSON.stringify(report,null,2));console.log(report);
