import fs from 'node:fs';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {startNative,connect,WS,root} from './native.mjs';
const base=process.env.HTTP_URL||(process.env.PREVIEW_URL?new URL(process.env.PREVIEW_URL).origin:'http://127.0.0.1:19140');
const assets=[['/','index.html','text/html'],['/app.js','app.js','text/javascript'],['/lab.js','lab.js','text/javascript'],['/atlas.js','atlas.js','text/javascript'],['/motion.js','motion.js','text/javascript'],['/style.css','style.css','text/css'],['/favicon.svg','favicon.svg','image/svg+xml'],['/favicon.ico','favicon.svg','image/svg+xml']];
const report={artifact_sha256:JSON.parse(fs.readFileSync(process.env.CITY_SELECTION||root+'/.build/selection.json')).artifact_sha256,assets:[],checks:[]};
for(const [url,file,mime]of assets){const response=await fetch(base+url),bytes=Buffer.from(await response.arrayBuffer()),expected=fs.readFileSync(root+'/web/'+file);assert.equal(response.status,200);assert(response.headers.get('content-type').startsWith(mime));assert.equal(response.headers.get('x-content-type-options'),'nosniff');assert.equal(response.headers.get('cache-control'),'no-store');assert.deepEqual(bytes,expected);report.assets.push({url,bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')});}
assert.equal(await (await fetch(base+'/healthz')).text(),'Traffic City native HTTP ready\n');
for(const [path,method]of [['/absent','GET'],['/app.js','POST'],['/healthz','HEAD'],['/live','GET'],['/.git/HEAD','GET'],['/src/session.lkjc','GET'],['/runtime/session.deployment.json','GET'],['/debug','GET'],['/benchmark-live','GET'],['/atlas-probe','GET']])assert.equal((await fetch(base+path,{method})).status,404);
report.checks.push('native HTTP byte-exact assets, MIME, headers, health, absent path and wrong methods');
const n=await startNative({name:'native-origin'});
async function handshake(headers,expected){const socket=new WS('ws://'+n.address+'/live',{headers});socket.on('error',()=>{});const result=await new Promise((resolve,reject)=>{const t=setTimeout(()=>reject(Error('Handshake timeout')),5000);socket.once('message',()=>{clearTimeout(t);resolve(101)});socket.once('unexpected-response',(_,response)=>{clearTimeout(t);response.resume();resolve(response.statusCode);socket.terminate()});});assert.equal(result,expected);if(result===101)await new Promise(resolve=>{socket.once('close',resolve);socket.close()});}
try{await handshake({Origin:'https://foreign.invalid'},403);await handshake({Origin:'http://127.0.0.1:19140'},101);await handshake({Origin:'https://city.example.test',Host:'city.example.test'},101);const c=connect(n.address);await c.wait(f=>f.seq===1);await c.close();report.checks.push('foreign Origin rejected; configured direct origin, forwarded public Host/HTTPS Origin and originless test client accepted');}finally{await n.stop();}
report.passed=true;fs.writeFileSync(root+'/evidence/native-host.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
