import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import {randomBytes} from 'node:crypto';import {spawnSync} from 'node:child_process';import {once} from 'node:events';import {startNative,connect,root} from './native.mjs';
const report=[];let n=await startNative({name:'persistence',tick:30});const keys=Array.from({length:9},()=>randomBytes(32).toString('hex')),saved=[];let c;
async function open(key){c=connect(n.address);await c.wait(f=>f.seq===1);let id=0;const owner=randomBytes(16).toString('hex');c.command=async(op,fields={})=>{const next=++id;c.socket.send(JSON.stringify({id:next,token:op==='resume'?key:'',owner:op==='resume'?owner:'',action:{op,x:0,y:0,x2:0,y2:0,kind:0,...fields}}));return c.wait(f=>f.ack===next)};return c.command('resume')}
const size=p=>fs.statSync(p).isDirectory()?fs.readdirSync(p).reduce((s,f)=>s+size(path.join(p,f)),0):fs.statSync(p).size;
function cli(...args){const r=spawnSync(n.selection.bin,args,{encoding:'utf8'});assert.equal(r.status,0,r.stdout+r.stderr);return r.stdout}
try{
 for(let i=0;i<8;i++){assert.equal((await open(keys[i])).status,1);const f=await c.command('build',{x:20+i,y:18,x2:20+i,y2:18,kind:1});saved.push(f.stats);await c.close()}
 assert.equal((await open(keys[8])).status,4);await c.close();report.push('eight durable slots; ninth refused without eviction');
 for(let i=0;i<8;i++){await open(keys[i]);const review=await c.command('review-reset');const fresh=await c.command('reset-city',{x:review.confirmation});assert(fresh.undo);assert.equal(fresh.stats.cash,900);await c.close()}
 assert.equal((await open(keys[8])).status,4);await c.close();report.push('resetting all eight cities keeps exactly eight slots and one recoverable backup each');
 await open(keys[0]);for(let i=0;i<20;i++)await c.command('save');await c.close();const dir=n.dir;await n.stop();const before=size(dir+'/data');cli('data','backup','--root',dir+'/data','--output',dir+'/city.backup');cli('data','restore','--backup',dir+'/city.backup','--root',dir+'/compacted');cli('data','verify','--root',dir+'/compacted');const after=size(dir+'/compacted');assert(after<before);fs.renameSync(dir+'/data',dir+'/retained-before-compaction');fs.renameSync(dir+'/compacted',dir+'/data');n=await startNative({directory:dir,name:'persistence-compacted',tick:30});
 for(let i=0;i<8;i++){const fresh=await open(keys[i]);assert(fresh.undo);const q=await c.command('review-restore');const f=await c.command('restore-city',{x:q.confirmation});assert.deepEqual(f.stats,saved[i]);assert(!f.undo);await c.close()}report.push('native backup/restore drops physical history and preserves all eight cities plus their reset backups');
 await open(keys[0]);await c.command('pause');const f=await c.wait(f=>f.saved>=10);const committed=f.saved;const exit=once(n.child,'exit');n.child.kill('SIGKILL');await exit;await c.close().catch(()=>{});n=await startNative({directory:dir,name:'persistence-crash',tick:30});const recovered=await open(keys[0]);assert(recovered.stats.tick>=committed);assert.equal(recovered.stats.cash,saved[0].cash);await c.command('pause');await c.close();report.push('acknowledged autosave survives forced process death');await n.stop();
 const head=fs.readFileSync(dir+'/data/HEAD');fs.writeFileSync(dir+'/data/HEAD','deliberately corrupt test HEAD\n');let failed=false;try{n=await startNative({directory:dir,name:'persistence-corrupt',tick:30});await open(keys[0])}catch(e){failed=true}assert(failed);assert.equal(fs.readFileSync(dir+'/data/HEAD','utf8'),'deliberately corrupt test HEAD\n');fs.writeFileSync(dir+'/data/HEAD',head);report.push('corrupt store is not replaced with a new city');
 const result={passed:true,artifact_sha256:n.selection.artifact_sha256,checks:report,history_bytes_before:before,compacted_bytes:after,logical_limit_cities:8,logical_limit_bytes_per_value:4194304,logical_values_per_city:2,history_policy:'Native supervisor checks every second and compacts at the greater of 64 MiB or twice the last compacted size; in-flight writes may overshoot. No TTL or silent eviction.'};fs.writeFileSync(root+'/evidence/persistence.json',JSON.stringify(result,null,2));console.log(result)
}finally{if(c)await c.close().catch(()=>{});if(n.child.exitCode===null&&n.child.signalCode===null)await n.stop().catch(()=>{})}
