// Accelerated real native session, legal player commands only. No fixture money,
// population, routes or agents are injected. Browser manipulation is tested separately.
import fs from 'node:fs';import assert from 'node:assert/strict';import {randomBytes} from 'node:crypto';import {startNative,connect,root} from './native.mjs';
let n,c,seq=0,current;const key=randomBytes(32).toString('hex'),events=[],checks=[],started=performance.now();
async function command(op,fields={}){const id=++seq;c.socket.send(JSON.stringify({id,token:op==='resume'?key:'',owner:op==='resume'?randomBytes(16).toString('hex'):'',action:{op,x:0,y:0,x2:0,y2:0,kind:0,...fields}}));const f=await c.wait(f=>f.ack===id,60000);assert.equal(f.status,1);current=f;events.push({op,...fields,tick:f.stats.tick,cash:f.stats.cash,population:f.stats.population,waiting:f.stats.waiting,disconnected:f.stats.disconnected,notice:f.notice});console.log(op,f.stats.tick,f.stats.cash,f.stats.population,f.stats.waiting);return f}
async function open(){seq=0;c=connect(n.address);await c.wait(f=>f.seq===1);const frame=await command('resume');fs.writeFileSync(n.dir+'/test-recovery.json',JSON.stringify({key,address:n.address}));return frame}
async function pause(){await command('set-running',{kind:0})}
async function earn(minimum,label){if(current.stats.cash>=minimum)return;await command('set-running',{kind:1});const start=current.stats.tick;current=await c.wait(f=>f.stats.tick>start&&(f.stats.cash>=minimum||f.stats.tick>=start+2400),180000);await pause();assert(current.stats.cash>=minimum,label+' did not earn enough money');events.push({milestone:label,tick:current.stats.tick,cash:current.stats.cash})}
async function build(x,y,x2,y2,kind){const before=current.stats,ox=before.originX,oy=before.originY,f=await command('build',{x:x+ox,y:y+oy,x2:x2+ox,y2:y2+oy,kind});assert.equal(f.stats.version,before.version+1,'legal build rejected: '+f.notice);assert(f.stats.cash>=0);return f}
async function place(x,y,kind){return build(x,y,x,y,kind)}
async function observe(limit=640){await command('set-running',{kind:1});const tick=current.stats.tick;current=await c.wait(f=>f.stats.tick>tick&&(f.stats.growth||f.stats.tick>=tick+limit),180000);await pause()}
async function diagnose(label){const residents=[];for(let id=1;id<=current.stats.population;id++){const f=await command('inspect',{kind:id});residents.push(f.inspect)}const reasons={};for(const r of residents)if(r.wait>=8){const key=[r.mode,r.reason,r.cell,r.dest].join(':');reasons[key]=(reasons[key]||0)+1}events.push({diagnosis:label,stats:current.stats,reasons,residents});fs.writeFileSync(root+'/evidence/player-diagnosis.json',JSON.stringify({label,stats:current.stats,reasons,residents},null,2));console.log('DIAGNOSIS',label,reasons)}
async function grow(){const target=current.stats.level+1;await observe();if(!current.stats.growth&&current.stats.level===2){await diagnose('64 residents before recovery');await earn(100,'fund junction recovery');for(const x of [5,8])await command('signal',{x:x+current.stats.originX,y:10+current.stats.originY,kind:3});await build(6,11,7,11,7);await observe(900);if(!current.stats.growth)await diagnose('64 residents after priority and footpath');checks.push('observe congestion and use paid junction controls plus a walking shortcut to recover')}assert(current.stats.growth,'district growth stalled: '+JSON.stringify(current.stats));const before=current.stats;await command('grow');assert.equal(current.stats.level,target);assert.equal(current.stats.cash,before.cash-before.growthCost);events.push({milestone:'district '+target,tick:current.stats.tick,stats:current.stats})}

try{
 n=await startNative({name:'player-journey',tick:1});await open();assert.equal(current.stats.cash,900);await build(14,10,15,10,2);await place(6,9,4);await place(9,9,4);await grow();checks.push('initial legal road/employment choices earn the first expansion');
 await earn(760,'fund 64 residents');await place(6,13,4);await place(9,13,4);for(const [x,y]of [[4,7],[7,7],[4,13],[7,13]])await place(x,y,3);await place(7,8,5);await place(4,12,6);await grow();assert.equal(current.stats.population,64);checks.push('jobs, four homes and nearby amenities earn district 3 with 64 residents');
 await earn(1400,'fund 128 residents');await build(3,10,4,10,1);await build(3,11,3,19,1);await build(12,11,12,19,1);await build(4,16,11,16,1);await place(2,16,4);await place(13,16,4);for(const [x,y]of [[2,15],[4,15],[2,17],[4,17],[11,15],[13,15],[11,17],[13,17]])await place(x,y,3);await place(4,18,5);await place(11,18,6);await grow();assert.equal(current.stats.population,128);checks.push('legal street extension and eight further homes earn district 4 with 128 residents');
 const beforeSave=current.stats;await command('save');await c.close();await open();assert.deepEqual(current.stats,beforeSave);checks.push('mature played city saves and reloads exact economy and traffic statistics');
 const report={passed:true,artifact_sha256:n.selection.artifact_sha256,method:'legal WebSocket commands against native persistence with 1ms requested timer; no state injection',wall_ms:performance.now()-started,checks,stats:current.stats,events};fs.writeFileSync(root+'/evidence/player-journey.json',JSON.stringify(report,null,2));console.log(report);
}catch(error){fs.writeFileSync(root+'/evidence/player-journey-attempt.json',JSON.stringify({passed:false,error:String(error),wall_ms:performance.now()-started,stats:c?.frames.at(-1)?.stats||current?.stats,actors:c?.frames.at(-1)?.actors,events},null,2));throw error}finally{if(c)await c.close().catch(()=>{});if(n)await n.stop().catch(()=>{})}
