import {createRequire} from 'node:module';const {chromium}=createRequire(import.meta.url)('playwright');import assert from 'node:assert/strict';import fs from 'node:fs';import {selectTool} from './ui-driver.mjs';
const recovery=JSON.parse(fs.readFileSync(process.env.PLAYER_UI_KEY_FILE)),prefix=process.env.PLAYER_UI_EVIDENCE||'evidence/player-ui',checks=[],errors=[];
async function detailView(page){
 // ResizeObserver and the native viewport response are asynchronous. Check
 // coverage of the current camera, rather than accepting an old detail frame.
 await page.waitForFunction(()=>{const r=document.querySelector('canvas').getBoundingClientRect();return window.__flowgarden.camera.angle===(r.height>r.width*1.15?-Math.PI/2:0)});
 const viewport=()=>{const g=window.__flowgarden,r=document.querySelector('canvas').getBoundingClientRect(),w=r.width,h=r.height,top=h<500?104:w<=680?180:150,bottom=Math.max(top+90,Math.min(h-25,document.querySelector('.bottom-ui').getBoundingClientRect().top-18)),corners=[{x:0,y:top},{x:w,y:top},{x:0,y:bottom},{x:w,y:bottom}].map(g.screenToWorld),clamp=(n,a,b)=>Math.max(a,Math.min(b,n)),x=clamp(Math.floor(Math.min(...corners.map(p=>p.x)))-1,0,127),y=clamp(Math.floor(Math.min(...corners.map(p=>p.y)))-1,0,127),width=clamp(Math.ceil(Math.max(...corners.map(p=>p.x)))+1-x,1,128-x),height=clamp(Math.ceil(Math.max(...corners.map(p=>p.y)))+1-y,1,128-y);return{x,y,w:width,h:height}};
 for(let i=0;i<12;i++){const r=await page.evaluate(viewport);if(r.w*r.h<=1024)break;const scale=await page.evaluate(()=>window.__flowgarden.camera.scale);await page.locator('#zoom-in').click();await page.waitForFunction(s=>window.__flowgarden.camera.scale>s,scale)}
 const r=await page.evaluate(viewport);assert(r.w*r.h<=1024,'zoom must request a native detail viewport');
 await page.waitForFunction(r=>{const g=window.__flowgarden,v=g.view;return g.detail&&g.actors.length>0&&v.w*v.h<=1024&&r.x>=v.x&&r.y>=v.y&&r.x+r.w<=v.x+v.w&&r.y+r.h<=v.y+v.h},r);
}
const browser=await chromium.launch({executablePath:process.env.CHROMIUM||undefined,headless:true,args:['--no-sandbox']});
try{const context=await browser.newContext({viewport:{width:1440,height:1000}});await context.addInitScript(key=>localStorage.setItem('flowgarden-city-v4',key),recovery.key);const page=await context.newPage();page.setDefaultTimeout(90000);page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.PREVIEW_URL);await page.waitForFunction(()=>window.__flowgarden?.sessionStatus===1&&window.__flowgarden.cells.some(c=>c.q>0));const stats=()=>page.evaluate(()=>window.__flowgarden.stats);const population=(await stats()).population;assert([128,256,512].includes(population));assert((await stats()).level>=(population===128?4:5));await page.locator('#fit').click();await detailView(page);await page.screenshot({path:prefix+`-${population}-residents.png`});const target=await page.evaluate(()=>{const g=window.__flowgarden;return g.cells.filter(c=>[1,2].includes(c.kind)&&c.q>0).map(c=>({...c,p:g.worldToScreen(c.id%128+.5,Math.floor(c.id/128)+.5)})).filter(c=>c.p.y>190&&c.p.y<700&&c.p.x>180&&c.p.x<1200).sort((a,b)=>b.q-a.q)[0]});assert(target);await selectTool(page,0);const position=()=>page.evaluate(id=>window.__flowgarden.worldToScreen(id%128+.5,Math.floor(id/128)+.5),target.id);let p=await position();await page.mouse.click(p.x,p.y);await page.waitForFunction(()=>document.querySelector('#removal').open);const quote=await page.evaluate(()=>window.__flowgarden.review);assert(quote.relocated>0);assert(quote.cancelled>0);assert.equal(quote.moveouts,0);const before=await stats();await page.screenshot({path:prefix+'-occupied-review.png'});await page.locator('#remove-confirm').click();await page.waitForFunction(v=>window.__flowgarden.stats.version===v+1,before.version);const removed=await stats();assert.equal(removed.population,population);assert.equal(removed.cancelled,before.cancelled+quote.cancelled);assert.equal(removed.arrived,before.arrived);checks.push('mature city from legal player run opens in actual browser; occupied-road review explicitly counts affected residents and cancelled trips');
 await selectTool(page,target.kind);p=await position();await page.mouse.click(p.x,p.y);await page.waitForFunction(v=>window.__flowgarden.stats.version===v+1,removed.version);await selectTool(page,-2);await page.locator('#fit').click();await page.locator('#play').click();await page.waitForFunction(({tick,population})=>window.__flowgarden.stats.tick>=tick+85&&(population!==512||window.__flowgarden.stats.growth),{tick:before.tick,population},{timeout:600000});await page.locator('#play').click();await page.waitForFunction(()=>window.__flowgarden.stats.paused);let after=await stats();assert(after.arrived>before.arrived);assert.equal(after.population,population);checks.push('rebuild the removed road through UI and remaining residents complete further real journeys');if(population===512){assert(after.growth);const ready=after;await page.locator('#grow').click();await page.waitForFunction(level=>window.__flowgarden.stats.level===level+1,ready.level);after=await stats();assert.equal(after.cash,ready.cash-ready.growthCost);assert.equal(after.population,512);checks.push('after the occupied-road edit, the512-person city recovers reliable travel and actually expands its district through the visible Grow control without adding population');}
 await page.locator('#menu-open').click();await page.locator('#save').click();await page.waitForFunction(()=>document.querySelector('#notice').textContent==='City saved.');await page.reload();await page.waitForFunction(()=>window.__flowgarden?.sessionStatus===1);assert.deepEqual(await stats(),after);await page.setViewportSize({width:390,height:844});await page.locator('#fit').click();await detailView(page);await page.screenshot({path:prefix+`-${population}-mobile.png`});assert(await page.evaluate(()=>window.__flowgarden.actors.length>0));assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));checks.push('mature city retains exact save on reload and shows actual native journeys in mobile detail view');assert.deepEqual(errors,[]);const report={passed:true,artifact_sha256:JSON.parse(fs.readFileSync(process.env.CITY_SELECTION||'.build/selection.json')).artifact_sha256,source:`Copy of the legally played ${population}-resident native city; recovery key only, no state injection`,checks,errors,before,quote,after};fs.writeFileSync(prefix+'.json',JSON.stringify(report,null,2));console.log(report);
}finally{await browser.close()}
