import {assertMoney,assertRailAccountingStep,withoutTreasury} from './rail-accounting.mjs';
import assert from 'node:assert/strict';import fs from 'node:fs';import {runCase,selection} from './run-case.mjs';
const checks=[],id=(x,y)=>x+128*y,command=(op,x=0,y=0,x2=0,y2=0,kind=0)=>({op,x,y,x2,y2,kind});
const tiles=[];for(let x=2;x<=61;x++)tiles.push({id:id(x,20),kind:2,q:0});for(const x of [2,3,4])tiles.push({id:id(x,19),kind:3,q:0});for(const x of [59,60,61])tiles.push({id:id(x,19),kind:4,q:0});tiles.push({id:id(5,19),kind:5,q:0},{id:id(6,19),kind:6,q:0});
const input={rows:0,ticks:0,tiles,commands:[],after:[]};
function run(name,arg,target='workload'){const r=runCase(arg,'rail-'+name,target).result;invariants(r);return r}
function advance(city,ticks,commands=[]){return run('continuation',{city,ticks,commands,after:[]},'continuation')}
function invariants(r){assertMoney(r.city);const s=r.city.sim,t=s.transit;assert.equal(r.conservation,0);assert.equal(s.population,r.agents.length);assert.equal(s.population,s.born-s.removed);assert.equal(s.requested,s.arrived+s.cancelled+r.agents.filter(a=>[1,2,4,5,6].includes(a.state)).length);assert.equal(new Set(s.ids).size,s.ids.length);assert(r.city.cash>=0);const agents=new Map(r.city.sim.agents),plans=new Map(t.plans);for(const [key,n]of r.lanes){if([1,2].includes(new Map(r.city.world.tiles).get(Math.floor(key/8))))assert(n>=0&&n<=3)}for(const[,l]of t.lines){assert(l.passengers.length<=l.capacity);assert.equal(new Set(l.passengers).size,l.passengers.length);for(const rider of l.passengers){assert.equal(agents.get(rider).state,6);assert.equal(plans.get(rider).line,l.id)}assert(l.elapsed<=l.duration);for(const [station,queue]of [[l.a,l.queueA],[l.b,l.queueB]]){assert.equal(new Set(queue).size,queue.length);for(const resident of queue){assert.equal(agents.get(resident).state,5);assert.equal(plans.get(resident).board,station)}}}}
const before=run('surface-start',input);const built=run('built',{...input,commands:[command('build-rail',3,21,60,21)]});assert.equal(built.city.sim.transit.ids.length,1);const line=built.city.sim.transit.lines[0][1];assert.equal(line.capacity,16);assert.equal(line.rideTicks,15);assert.equal(line.cost,924);assert.equal(built.city.cash,before.city.cash-924);checks.push({name:'atomic construction includes both stations and river surcharge',passed:true,cost:line.cost});
const baseline=advance(before.city,150),served=advance(built.city,150);assert(served.city.sim.transit.boardings>0);assert(served.city.sim.transit.completed>0);assert(served.city.sim.carTrips<baseline.city.sim.carTrips);assert.deepEqual(advance(built.city,150),served);checks.push({name:'connected access plus scheduled ride and egress attract actual residents; replay is deterministic',passed:true,baseline:{arrived:baseline.city.sim.arrived,cars:baseline.city.sim.carTrips,waiting:baseline.city.sim.waiting},rail:{arrived:served.city.sim.arrived,cars:served.city.sim.carTrips,waiting:served.city.sim.waiting,...Object.fromEntries(['boardings','completed','spent'].map(k=>[k,served.city.sim.transit[k]]))}});
let city=built.city,maxOnboard=0,maxQueue=0,riding=null,queued=null;const samples=[];
for(let i=0;i<100;i++){const old=city,l0=old.sim.transit.lines[0][1],r=advance(city,1),l=r.city.sim.transit.lines[0][1];maxOnboard=Math.max(maxOnboard,l.passengers.length);maxQueue=Math.max(maxQueue,l.queueA.length,l.queueB.length);if(l.departures>l0.departures){const q=l0.from===l0.a?l0.queueA:l0.queueB;assert.deepEqual(l.passengers,q.slice(0,16),'FIFO boarding');assert.equal(l.spent-l0.spent,6);assert.equal(l.departures-l0.departures,1)}const oldAgents=new Map(old.sim.agents);assert.equal(r.city.sim.arrived-old.sim.arrived,r.agents.reduce((sum,a)=>sum+a.journeys-oldAgents.get(a.id).journeys,0));assertRailAccountingStep(old,r.city);if(l.passengers.length&&!riding)riding=structuredClone(r.city);if(l.queueA.length&&!queued)queued=structuredClone(r.city);samples.push({tick:r.city.sim.tick,arrived:r.city.sim.arrived,onboard:l.passengers.length,queueA:l.queueA.length,queueB:l.queueB.length,cash:r.city.cash,spent:l.spent});city=r.city}
assert.equal(maxOnboard,16);assert(maxQueue>16);assert(riding);checks.push({name:'100 every-tick snapshots conserve people, requests, finite seats, FIFO order, fares and exact operating expenses; boarding never earns destination revenue',passed:true,maxOnboard,maxQueue,samples});
assert(queued);const poor=withoutTreasury(queued),waitingId=poor.sim.transit.lines[0][1].queueA[0],spentBefore=poor.sim.transit.spent;const fallback=advance(poor,37);const walker=fallback.agents.find(a=>a.id===waitingId);assert.equal(fallback.city.sim.transit.spent,spentBefore);assert(![5,6].includes(walker.state));assert.equal(walker.mode,1);assert.equal(fallback.city.sim.cancelled,0);checks.push({name:'unfunded service waits at a station; a waiting passenger falls back to connected walking without cancellation or teleport',passed:true});
const unfundedRide=withoutTreasury(riding);const landed=advance(unfundedRide,16);assert(landed.agents.every(a=>a.state!==6));assert.equal(landed.city.sim.cancelled,0);assert.equal(landed.city.sim.transit.spent,unfundedRide.sim.transit.spent);checks.push({name:'a paid leg finishes with zero remaining funds and preserves every rider',passed:true});
const suspended=advance(riding,25,[command('rail-service',1,0,0,0,0)]);assert(suspended.agents.every(a=>![5,6].includes(a.state)));assert.equal(suspended.city.sim.transit.lines[0][1].enabled,false);const resumed=advance(suspended.city,80,[command('rail-service',1,0,0,0,1)]);assert(resumed.city.sim.transit.lines[0][1].departures>suspended.city.sim.transit.lines[0][1].departures);checks.push({name:'suspending and resuming service keeps paid riders safe and releases platform queues',passed:true});
for(const c of [command('build-rail',-1,21,60,21),command('build-rail',3,21,60,22),command('build-rail',3,21,4,21),command('build-rail',3,21,100,21),command('build-rail',3,21,60,21),command('build',10,21,10,21,3),command('build',3,21,3,21,0),command('rail-service',99,0,0,0,1),command('rail-service',1,0,0,0,2)]){const r=advance(built.city,0,[c]);assert.deepEqual(r.city,built.city)}
const under=advance(built.city,0,[command('build',10,21,10,21,1)]);assert.equal(under.city.sim.transit.ids.length,1);assert.equal(new Map(under.city.world.tiles).get(id(10,21)),1);checks.push({name:'malformed, overlapping, oversized and destructive legacy commands reject atomically; roads can be added below elevated rail',passed:true});
const isolatedTiles=[];for(let x=2;x<=61;x++)isolatedTiles.push({id:id(x,18),kind:2,q:0});isolatedTiles.push({id:id(2,17),kind:3,q:0},{id:id(61,17),kind:4,q:0},{id:id(3,20),kind:7,q:0},{id:id(60,20),kind:7,q:0});const isolated=run('disconnected-station-access',{...input,tiles:isolatedTiles,ticks:180,commands:[command('build-rail',3,21,60,21)]});assert.equal(isolated.city.sim.transit.boardings,0);assert.equal(isolated.city.sim.transit.completed,0);assert(isolated.city.sim.carTrips>0);checks.push({name:'nearby but disconnected station access cannot attract or teleport residents',passed:true});
const fullTiles=tiles.slice();for(let y=30;fullTiles.length<8191;y++)for(let x=0;x<128&&fullTiles.length<8191;x++)fullTiles.push({id:id(x,y),kind:1,q:0});
const limitBefore=run('tile-limit-before',{...input,tiles:fullTiles}),limitRefused=advance(limitBefore.city,0,[command('build-rail',3,21,60,21)]);assert.deepEqual(limitRefused.city,limitBefore.city);
const limitAllowed=run('tile-limit-exact',{...input,tiles:fullTiles.slice(0,8190),commands:[command('build-rail',3,21,60,21)]});assert.equal(limitAllowed.city.world.tiles.length,8192);assert.equal(limitAllowed.city.sim.transit.ids.length,1);checks.push({name:'two station tiles fit exactly at 8,192 tiles; exceeding the city limit rejects the complete line atomically',passed:true});
fs.writeFileSync('evidence/rail.json',JSON.stringify({passed:true,artifact_sha256:selection.artifact_sha256,checks},null,2));fs.writeFileSync('runtime/rail-riding-fixture.json',JSON.stringify(riding));console.log(JSON.stringify({passed:true,checks:checks.map(c=>c.name),baseline:checks[1].baseline,rail:checks[1].rail},null,2));
