import assert from 'node:assert/strict';import fs from 'node:fs';import {randomBytes} from 'node:crypto';import {startNative,connect,root} from './native.mjs';
let n=await startNative({name:'socket',tick:25});const report=[],clients=[];const token=randomBytes(32).toString('hex');
async function client(key=token){const c=connect(n.address);clients.push(c);await c.wait(f=>f.seq===1);let id=0;const owner=randomBytes(16).toString('hex');c.command=async(op,fields={})=>{const next=++id;c.socket.send(JSON.stringify({id:next,token:op==='resume'?key:'',owner:op==='resume'?owner:'',action:{op,x:0,y:0,x2:0,y2:0,kind:0,...fields}}));return c.wait(f=>f.ack===next)};c.resumed=await c.command('resume');assert.equal(c.resumed.status,1);return c}
try{
 const a=await client();assert.equal(a.resumed.stats.population,32);assert(a.resumed.mapChanged);report.push('native claim creates saved private city');
 let f=await a.command('build',{x:14,y:10,x2:15,y2:10,kind:2});assert.equal(f.stats.cash,852);assert.equal(f.saved,0);
 const independent=await client(randomBytes(32).toString('hex'));assert.equal(independent.resumed.stats.cash,900);await independent.close();report.push('different browser keys isolate city data');
 await a.command('pause');f=await a.wait(f=>f.saved>=10);assert(f.stats.tick>=10);await a.command('pause');const paused=await a.command('save');assert.equal(paused.saved,paused.stats.tick);await a.close();
 const b=await client();assert.deepEqual(b.resumed.stats,paused.stats);report.push('autosave and reconnect preserve authoritative city');
 const other=await client();const stale=await b.command('build',{x:17,y:9,x2:17,y2:9,kind:2});assert.equal(stale.status,2);await b.close();const valid=await other.command('save');assert.deepEqual(valid.stats,paused.stats);report.push('stale tab cannot overwrite current owner');
 let last=other.frames.at(-1);other.socket.send('{');f=await other.wait(x=>x.seq>last.seq&&x.notice.includes('sequence'));assert.equal(f.stats.cash,paused.stats.cash);report.push('malformed JSON does not mutate city');
 const overview=await other.command('view',{x:0,y:0,x2:128,y2:128});assert.equal(overview.detail,false);assert.equal(overview.actors.length,0);assert(overview.cells.length===0);report.push('whole-city overview without full dynamic city every frame');
 const saved=await other.command('save');await other.close();const dir=n.dir;await n.stop();n=await startNative({directory:dir,name:'socket-restart',tick:25});const restarted=await client();assert.deepEqual(restarted.resumed.stats,saved.stats);await restarted.close();report.push('save survives native process restart');
 const racers=await Promise.all([client(),client()]);const attempts=await Promise.all(racers.map(c=>c.command('save')));assert.equal(attempts.filter(f=>f.status===1).length,1);assert.equal(attempts.filter(f=>f.status===2).length,1);for(const r of racers)await r.close();report.push('concurrent claims converge to one writable owner');
 const bytes=Math.max(...clients.flatMap(c=>c.frames.map(f=>f.bytes||JSON.stringify(f).length)));assert(bytes<131072);const result={passed:true,artifact_sha256:n.selection.artifact_sha256,checks:report,maximum_frame_bytes:bytes,checkpoint:saved.stats};fs.writeFileSync(root+'/evidence/socket.json',JSON.stringify(result,null,2));console.log(result);
}finally{for(const c of clients)await c.close().catch(()=>{});await n.stop()}
