// Visible controls and a disposable profile; no injected residents or simulation.
import fs from 'node:fs';import assert from 'node:assert/strict';import{createRequire}from'node:module';
const{chromium}=createRequire(import.meta.url)('playwright');
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM||undefined,args:['--no-sandbox']});
const checks=[],errors=[];let page;
try{
 const context=await browser.newContext({viewport:{width:1440,height:960}});page=await context.newPage();page.setDefaultTimeout(90000);page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.PREVIEW_URL);await page.waitForFunction(()=>window.__flowgarden?.sessionStatus===1);
 await page.locator('#menu-open').click();await page.locator('#examples-open').click();await page.locator('[data-scenario="4"]').click();await page.waitForFunction(()=>!document.querySelector('#city-confirm').disabled);await page.locator('#city-confirm').click();await page.waitForFunction(()=>window.__flowgarden.stats.population===1024&&window.__flowgarden.menuPage==='home');await page.locator('#continue').click();await page.locator('#fit').click();
 await page.waitForFunction(()=>!window.__flowgarden.detail);await page.locator('#play').click();await page.waitForFunction(()=>window.__flowgarden.stats.tick>=32&&window.__flowgarden.renderedActors.some(a=>a.mode!==2),null,{timeout:240000});await page.locator('#play').click();await page.waitForFunction(()=>window.__flowgarden.stats.paused);await page.waitForTimeout(900);
 const state=()=>page.evaluate(()=>{const g=window.__flowgarden;return{stats:g.stats,street:g.street,actors:g.actors,rendered:g.renderedActors,view:g.view,detail:g.detail,camera:g.camera}});
 let s=await state();assert(!s.detail);assert(s.street.walking>0);assert(s.actors.some(a=>a.mode!==2));assert.equal(s.actors.length,Math.min(128,s.street.walking+s.street.driving));assert(s.actors.filter(a=>a.mode!==2).length>=Math.min(64,s.street.walking));assert(s.actors.filter(a=>a.mode===2).length>=Math.min(64,s.street.driving));
 assert.deepEqual(new Set(s.rendered.map(a=>a.id)),new Set(s.actors.map(a=>a.id)),'Only received native identities may settle on the map');
 assert.equal(await page.locator('#street-counts').textContent(),`In view · ${s.street.walking.toLocaleString('en-US')} on foot · ${s.street.driving.toLocaleString('en-US')} in cars`);if(s.street.walking+s.street.driving>128)assert.match(await page.locator('#street-sample').textContent(),/128 of/);
 await page.screenshot({path:'evidence/street-overview.png'});checks.push('River Boroughs shows real native pedestrians in overview, reserves both modes, and labels full viewport counts separately from the sample.');
 const overview=s,target=s.rendered.find(a=>a.mode!==2);for(let i=0;i<8;i++){if(await page.evaluate(()=>window.__flowgarden.detail))break;const p=await page.evaluate(({x,y})=>window.__flowgarden.worldToScreen(x,y),target);await page.mouse.move(Math.max(10,Math.min(1430,p.x)),Math.max(180,Math.min(730,p.y)));await page.mouse.wheel(0,-250);await page.waitForTimeout(350)}
 await page.waitForFunction(()=>window.__flowgarden.detail);await page.waitForTimeout(800);s=await state();assert.equal(s.stats.tick,overview.stats.tick);assert(s.rendered.some(a=>a.mode!==2));assert.deepEqual(s.stats,overview.stats,'Camera changes must not advance or alter the city');
 const glyph=await page.evaluate(async()=>{const{pedestrianSize}=await import('/motion.js');const g=window.__flowgarden,metrics=pedestrianSize(g.camera.scale),canvas=document.querySelector('#map'),ctx=canvas.getContext('2d'),ratio=canvas.width/innerWidth;let colored=0;
  for(const a of g.renderedActors.filter(a=>a.mode!==2)){const p=g.worldToScreen(a.x,a.y);if(p.x<5||p.y<180||p.x>innerWidth-5||p.y>innerHeight-240)continue;const x=Math.floor(p.x*ratio)-4,y=Math.floor(p.y*ratio)-4,data=ctx.getImageData(x,y,9,9).data;for(let i=0;i<data.length;i+=4)if([[55,93,75],[174,99,66],[108,84,138]].some(c=>c.every((v,k)=>Math.abs(v-data[i+k])<5))){colored++;break}}
  return{minimumDiameter:2*metrics.radius*g.camera.scale,coloredPedestrians:colored,scale:g.camera.scale};});assert(glyph.minimumDiameter>=3);assert(glyph.coloredPedestrians>0,'A pedestrian jacket must actually reach the rendered canvas pixels');
 await page.screenshot({path:'evidence/street-detail.png'});checks.push('Zooming preserves exact native city state; pedestrians have a minimum three-CSS-pixel body and visible rendered jacket pixels.');
 await page.setViewportSize({width:390,height:844});await page.locator('#fit').click();await page.waitForFunction(()=>!window.__flowgarden.detail&&window.__flowgarden.renderedActors.some(a=>a.mode!==2));await page.waitForTimeout(750);
 const mobile=await state();assert.deepEqual(mobile.stats,overview.stats);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));const caption=await page.locator('.map-caption').boundingBox(),camera=await page.locator('.camera-tools').boundingBox();assert(caption.x+caption.width<=camera.x,'Street counts must not overlap the mobile camera controls');await page.screenshot({path:'evidence/street-mobile.png'});
 checks.push('The 390×844 viewport retains visible pedestrians and legible nonoverlapping street counts without changing the city.');
 await page.locator('#menu-open').click();await page.locator('#save').click();await page.waitForFunction(()=>document.querySelector('#notice').textContent==='City saved.');const saved=(await state()).stats;await page.reload();await page.waitForFunction(()=>window.__flowgarden?.sessionStatus===1);assert.deepEqual((await state()).stats,saved);assert.deepEqual(errors,[]);
 fs.writeFileSync('evidence/street-ui.json',JSON.stringify({passed:true,artifact_sha256:JSON.parse(fs.readFileSync(process.env.CITY_SELECTION||'.build/selection.json')).artifact_sha256,checks,overview:{stats:overview.stats,street:overview.street,view:overview.view,renderedWalking:overview.rendered.filter(a=>a.mode!==2).length},glyph,mobile:{view:mobile.view,street:mobile.street},errors,physicalDevice:false},null,2));console.log({passed:true,checks,glyph});
}catch(error){if(page)await page.screenshot({path:'evidence/street-ui-failure.png'}).catch(()=>{});throw error}finally{await browser.close()}
