import {createRequire} from 'node:module';const {chromium}=createRequire(import.meta.url)('playwright');import assert from 'node:assert/strict';import fs from 'node:fs';import {selectTool,districtPoint} from './ui-driver.mjs';
const browser=await chromium.launch({executablePath:process.env.CHROMIUM||undefined,headless:true,args:['--no-sandbox']}),checks=[],errors=[],prefix=process.env.TOUCH_REMOVE_EVIDENCE||'evidence/touch-removal';
try{const context=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true}),page=await context.newPage(),cdp=await context.newCDPSession(page);page.on('pageerror',e=>errors.push(e.message));await page.goto(process.env.PREVIEW_URL);await page.waitForFunction(()=>window.__flowgarden?.sessionStatus===1);const state=()=>page.evaluate(()=>({stats:window.__flowgarden.stats,draft:window.__flowgarden.draft,pointers:window.__flowgarden.pointerCount,reviews:window.__flowgarden.sentCommands.filter(c=>c.op==='review-remove').length}));async function touch(type,points=[]){await cdp.send('Input.dispatchTouchEvent',{type,touchPoints:points.map(p=>({...p,radiusX:6,radiusY:6,force:1}))});await page.waitForTimeout(25)}async function stroke(x,y,x2,y2){const a=await districtPoint(page,x,y),b=await districtPoint(page,x2,y2);await touch('touchStart',[{id:1,...a}]);for(let i=1;i<=8;i++)await touch('touchMove',[{id:1,x:a.x+(b.x-a.x)*i/8,y:a.y+(b.y-a.y)*i/8}]);await touch('touchEnd')}
 await selectTool(page,1);await page.locator('#fit').click();for(let y=7;y<=9;y++){const v=(await state()).stats.version;await stroke(10,y,12,y);await page.waitForFunction(v=>window.__flowgarden.stats.version>v,v)}await selectTool(page,0);await page.locator('#fit').click();const before=await state(),a=await districtPoint(page,12,9),b=await districtPoint(page,10,7);
 for(const interruption of ['second finger','touchcancel']){await touch('touchStart',[{id:1,...a}]);await touch('touchMove',[{id:1,...b}]);const d=(await state()).draft;assert.equal(Math.abs(d.end.x-d.start.x),2);assert.equal(Math.abs(d.end.y-d.start.y),2);if(interruption==='second finger'){await touch('touchStart',[{id:1,...b},{id:2,x:b.x+65,y:b.y+30}]);await touch('touchEnd')}else await touch('touchCancel');const after=await state();assert.equal(after.draft,null);assert.equal(after.pointers,0);assert.equal(after.reviews,before.reviews);assert.deepEqual(after.stats,before.stats);checks.push(interruption+' cancels a genuine touch rectangle without requesting removal')}
 await stroke(12,9,10,7);await page.waitForFunction(()=>document.querySelector('#removal').open);assert.equal(await page.evaluate(()=>window.__flowgarden.review.tiles),9);await page.screenshot({path:prefix+'-review.png'});await page.tap('#remove-cancel');assert.deepEqual((await state()).stats,before.stats);await stroke(10,7,12,9);await page.waitForFunction(()=>document.querySelector('#removal').open);await page.tap('#remove-confirm');await page.waitForFunction(v=>window.__flowgarden.stats.version===v+1,before.stats.version);assert.equal((await state()).stats.cash,before.stats.cash+36);checks.push('both touch drag directions select all nine tiles; cancel and confirm have exact native effects');
 const after=await state();await stroke(10,7,12,9);await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('non-empty rectangle'));assert.equal(await page.locator('#removal').isVisible(),false);assert.deepEqual((await state()).stats,after.stats);checks.push('repeated removal of an empty area cannot refund or change state');
 const home=await districtPoint(page,8,6);await page.touchscreen.tap(home.x,home.y);await page.waitForFunction(()=>document.querySelector('#removal').open);assert.equal(await page.evaluate(()=>window.__flowgarden.review.moveouts),8);await page.tap('#remove-confirm');await page.waitForFunction(()=>window.__flowgarden.stats.population===24);assert.equal((await state()).stats.cash,after.stats.cash+35);await selectTool(page,-2);await page.screenshot({path:prefix+'-after.png'});checks.push('single-touch building removal is reachable and explicitly accounts for its eight residents');assert.deepEqual(errors,[]);const report={passed:true,artifact_sha256:JSON.parse(fs.readFileSync(process.env.CITY_SELECTION||'.build/selection.json')).artifact_sha256,input:'Chromium native touch dispatcher and touchscreen taps; emulated mobile hardware',checks,errors};fs.writeFileSync(prefix+'.json',JSON.stringify(report,null,2));console.log(report);
}finally{await browser.close()}
