// Play through visible controls in a disposable native city and browser profile.
import fs from 'node:fs';import assert from 'node:assert/strict';import{createRequire}from'node:module';
const {chromium}=createRequire(import.meta.url)('playwright');
const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM||undefined,args:['--no-sandbox']});
const checks=[],errors=[];let page;
function mark(note){checks.push(note);console.log(note)}
const state=()=>page.evaluate(()=>{const g=window.__flowgarden;return{stats:g.stats,cells:g.cells.map(c=>({id:c.id,kind:c.kind})),view:g.view,layer:g.layer,tunnel:g.tunnelMode,tool:g.tool}});
const ground=s=>s.cells.filter(c=>c.id<16384).sort((a,b)=>a.id-b.id);
async function settle(version){await page.waitForFunction(v=>window.__flowgarden.stats.version===v,version);await page.waitForTimeout(450)}
async function point(x,y){return page.evaluate(({x,y})=>window.__flowgarden.worldToScreen(x+.5,y+.5),{x,y})}
async function drag(a,b){const p=await point(a.x,a.y),q=await point(b.x,b.y);await page.mouse.move(p.x,p.y);await page.mouse.down();await page.mouse.move(q.x,q.y,{steps:8});await page.mouse.up()}
async function line(length=5){return page.evaluate(async len=>{
 const {waterAt}=await import('/geometry.js'),g=window.__flowgarden,cells=new Map(g.cells.map(c=>[c.id,c.kind])),bottom=document.querySelector('.bottom-ui').getBoundingClientRect().top-20,top=document.querySelector('.hud').getBoundingClientRect().bottom+85;
 for(let y=Math.max(1,g.view.y);y<Math.min(125,g.view.y+g.view.h);y++)for(let x=Math.max(3,g.view.x);x<Math.min(125-len,g.view.x+g.view.w-len);x++){
  const a=g.worldToScreen(x+.5,y+.5),b=g.worldToScreen(x+len-.5,y+.5);if(a.x-2*g.camera.scale<65||b.x>innerWidth-245||a.y<top||a.y>bottom||b.y<top||b.y>bottom)continue;
  if([...Array(len+2)].some((_,j)=>{const i=j-2;return cells.has(x+i+y*128)||waterAt(g.river,g.riverWidth,x+i+y*128)||cells.has(16384+x+i+y*128)}))continue;return{a:{x,y},b:{x:x+len-1,y}};
 }throw Error('No visible dry construction line in this isolated city');
 },length)}
try{
 const context=await browser.newContext({viewport:{width:1440,height:960}});page=await context.newPage();page.setDefaultTimeout(120000);page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.PREVIEW_URL);await page.waitForFunction(()=>window.__flowgarden?.sessionStatus===1);const start=await state();assert(start.stats.paused);
 await page.locator('#map').focus();for(let i=0;i<5;i++)await page.keyboard.press('ArrowUp');await page.locator('[data-palette="roads"]').click();await page.locator('#roads-palette [data-tool="1"]').click();await page.locator('#tunnel-mode').click();await page.waitForTimeout(400);
 console.log('construction-view',await page.evaluate(()=>({view:window.__flowgarden.view,camera:window.__flowgarden.camera,hud:document.querySelector('.hud').getBoundingClientRect().toJSON(),bottom:document.querySelector('.bottom-ui').getBoundingClientRect().toJSON()})));const span=await line(),before=await state();await drag(span.b,span.a);await settle(before.stats.version+1);let current=await state();
 assert.equal(current.stats.cash,before.stats.cash-5*48-120);assert.equal(current.cells.filter(c=>c.id>=16384).length,5);assert.equal(current.cells.find(c=>c.id===span.a.x+span.a.y*128).kind,13);assert.deepEqual(ground(current).filter(c=>![span.a.x+span.a.y*128,span.b.x+span.b.y*128].includes(c.id)),ground(before));
 await page.screenshot({path:'evidence/tunnel-ground.png'});mark('Reverse drag constructs and charges a complete native tunnel through the visible tool, preserving all existing ground tiles');
 await page.locator('[data-layer="1"]').click();await page.waitForFunction(()=>window.__flowgarden.view.layer===1);await page.waitForTimeout(450);assert.equal((await state()).stats.tick,before.stats.tick);assert.equal((await state()).layer,1);assert(await page.locator('#tunnel-mode').isDisabled());await page.screenshot({path:'evidence/tunnel-underground.png'});mark('Underground toggle changes projection, not the native city or its clock');
 await page.locator('#roads-palette [data-tool="20"]').click();await page.locator('#oneway-direction').selectOption('2');current=await state();const extension={a:{x:span.a.x-2,y:span.a.y},b:{x:span.a.x-1,y:span.a.y}};await drag(extension.a,extension.b);await settle(current.stats.version+1);current=await state();for(const p of [extension.a,extension.b])assert.equal(current.cells.find(c=>c.id===16384+p.x+p.y*128).kind,11);assert.equal(current.cells.filter(c=>c.kind===13).length,2);mark('Direction selector writes westbound underground tiles without implicit surface entrances');
 await page.locator('#roads-palette [data-tool="22"]').click();await page.waitForFunction(()=>window.__flowgarden.view.layer===0);const version=current.stats.version;await drag(extension.a,extension.a);await settle(version+1);current=await state();assert.equal(current.cells.find(c=>c.id===extension.a.x+extension.a.y*128).kind,13);mark('Portal tool returns to the ground and connects an existing underground road');
 await page.locator('#roads-palette [data-tool="20"]').click();await page.locator('#oneway-direction').selectOption('2');await page.locator('#map').focus();await page.keyboard.press('r');assert.equal(await page.locator('#oneway-direction').inputValue(),'3');if((await state()).tunnel)await page.locator('#tunnel-mode').click();const surface=await line(2),v=(await state()).stats.version;await drag(surface.a,surface.b);await settle(v+1);current=await state();for(const p of [surface.a,surface.b])assert.equal(current.cells.find(c=>c.id===p.x+p.y*128).kind,12);mark('R rotates the one-way arrow, and surface construction does not edit the underground layer');
 const surfaceBefore=ground(current);await page.locator('[data-layer="1"]').click();await page.waitForFunction(()=>window.__flowgarden.view.layer===1);await page.locator('[data-tool="0"]').click();await page.waitForTimeout(350);await drag(span.b,span.b);await page.waitForFunction(()=>window.__flowgarden.review?.valid);const quote=await page.evaluate(()=>window.__flowgarden.review);assert.equal(quote.layer,1);assert.equal(quote.tiles,1);assert.equal(quote.refund,24);assert.equal(quote.homes,0);assert.match(await page.locator('#removal-size').textContent(),/Underground/);await page.locator('#remove-confirm').click();await settle(current.stats.version+1);current=await state();assert.deepEqual(ground(current),surfaceBefore);mark('The review explicitly names Underground, quotes the correct refund, and leaves all surface objects intact');
 await page.setViewportSize({width:390,height:844});await page.locator('#fit').click();await page.locator('[data-palette="roads"]').click();await page.waitForTimeout(700);assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 for(const selector of ['.layer-switch','#roads-palette','#road-options']){const r=await page.locator(selector).boundingBox();assert(r&&r.x>=0&&r.y>=0&&r.x+r.width<=390&&r.y+r.height<=844,selector+' clipped')}
 const a=await page.locator('.camera-tools').boundingBox(),b=await page.locator('.layer-switch').boundingBox();assert(a.y+a.height<=b.y||b.y+b.height<=a.y||a.x+a.width<=b.x||b.x+b.width<=a.x,'Layer and camera controls overlap');await page.screenshot({path:'evidence/tunnel-mobile.png'});mark('390×844 layout keeps construction, direction and layer controls visible and separate from camera controls');
 const saved=(await state()).stats;await page.reload();await page.waitForFunction(()=>window.__flowgarden?.sessionStatus===1);assert.deepEqual((await state()).stats,saved);assert.deepEqual(errors,[]);mark('Reload reclaims the same native city with exact saved statistics and no browser errors');
 fs.writeFileSync('evidence/tunnel-ui.json',JSON.stringify({passed:true,artifact_sha256:JSON.parse(fs.readFileSync(process.env.CITY_SELECTION||'.build/selection.json')).artifact_sha256,checks,span,errors,physicalDevice:false},null,2));console.log({passed:true,checks});
}catch(error){fs.writeFileSync('evidence/tunnel-ui-failure.json',JSON.stringify({passed:false,checks,errors,error:String(error)},null,2));if(page)await page.screenshot({path:'evidence/tunnel-ui-failure.png'}).catch(()=>{});throw error}finally{await browser.close()}
