// Native synthetic River Boroughs; no player store and no demand substitution.
import fs from 'node:fs';import path from 'node:path';import assert from 'node:assert/strict';import{createHash}from'node:crypto';import{runCase,selection}from'./run-case.mjs';import{assertMoney}from'./rail-accounting.mjs';
const hash=x=>createHash('sha256').update(JSON.stringify(x)).digest('hex'),reference=process.env.WALK_REFERENCE_DIR;
let ref=null;if(reference){const s=JSON.parse(fs.readFileSync(path.join(reference,'.build/selection.json'))),e=JSON.parse(fs.readFileSync(path.join(reference,'evidence/candidate-final-compact-profile.json')));assert(e.passed);assert.equal(s.artifact_sha256,e.artifact_sha256);assert.equal(s.compiler_sha256,selection.compiler_sha256);ref={artifact_sha256:s.artifact_sha256,evidence:e};}
const seed=runCase(4,'walk-profile-seed','scenario-seed').result;let city=seed;const ids=seed.sim.ids,samples=[];
function observation(c){const people=c.sim.agents.map(([,a])=>a),tiles=new Map(c.world.tiles),street=people.filter(a=>a.state===2&&(a.from!==a.to||![3,4,5,6,8].includes(tiles.get(a.to))));return{tick:c.sim.tick,population:c.sim.population,walkTrips:c.sim.walkTrips,carTrips:c.sim.carTrips,walkingStreet:street.filter(a=>a.mode!==2).length,drivingStreet:street.filter(a=>a.mode===2).length,arrived:c.sim.arrived,visits:c.sim.visits,railBoardings:c.sim.transit.boardings,railCompleted:c.sim.transit.completed,planning:people.filter(a=>a.state===1&&a.reason===8).length,waiting:c.sim.waiting,neverArrived:people.filter(a=>a.journeys===0).length};}
function conserve(c){const s=c.sim;assert.deepEqual(s.ids,ids);assert.equal(s.population,1024);assert.equal(s.born-s.removed,1024);assert.equal(s.cancelled,0);assert.equal(s.requested,s.arrived+s.cancelled+s.agents.filter(([,a])=>[1,2,4,5,6].includes(a.state)).length);assertMoney(c);for(const[,line]of s.transit.lines){assert(line.passengers.length<=line.capacity);assert.equal(new Set(line.passengers).size,line.passengers.length)}}
for(let i=0;i<8;i++){
 const beforeTick=city.sim.tick,r=runCase({city,ticks:64,resident:1},'walk-profile-'+i,'walk-trace').result;assert.equal(r.frames.length,64);assert(r.frames.every((f,j)=>f.tick===beforeTick+j+1));city=r.city;conserve(city);
 const sample={after:observation(city),snapshot_sha256:hash(city)},street=runCase({city,view:{x:0,y:0,w:128,h:128}},'walk-profile-projection-'+i,'street-probe').result;
 assert.equal(street.walking,sample.after.walkingStreet);assert.equal(street.driving,sample.after.drivingStreet);assert.equal(street.actors.length,Math.min(128,street.walking+street.driving));sample.shownWalking=street.actors.filter(a=>a.mode!==2).length;
 if(ref){const raw=JSON.parse(fs.readFileSync(path.join(reference,'runtime/candidate-final-'+city.sim.tick+'.json'))),logged=ref.evidence.samples.find(s=>s.tick===city.sim.tick);assert(logged);assert.equal(raw.sim.arrived,logged.arrived);assert.equal(raw.sim.visits,logged.visits);assert.equal(raw.sim.transit.completed,logged.completed);conserve(raw);sample.before=observation(raw);sample.reference_snapshot_sha256=hash(raw);}
 samples.push(sample);fs.writeFileSync('runtime/walkable-profile-'+city.sim.tick+'.json',JSON.stringify(city));console.log(JSON.stringify(sample));
 fs.writeFileSync('evidence/walking-profile.json',JSON.stringify({passed:i===7,artifact_sha256:selection.artifact_sha256,compiler_sha256:selection.compiler_sha256,reference_artifact_sha256:ref?.artifact_sha256,method:'512 native cycles in eight uninterrupted 64-cycle command runs; invariant observations at every 64-cycle boundary and exact single-resident timelines. Optional reference uses retained native synthetic snapshots checked against their original source-bound profile; no claim of an equal wall-clock benchmark.',seed_sha256:hash(seed),samples},null,2));
}
assert(city.sim.walkTrips>0);assert(city.sim.carTrips>0);assert(city.sim.transit.completed>0);
