// Native cache refresh fixtures exercise semantic validity and hard cache bounds.
import fs from 'node:fs';import assert from 'node:assert/strict';import {runCase,selection} from './run-case.mjs';
const id=(x,y)=>x+128*y,signature=(a,b,m)=>a*32768+b*2+m-1;
const input={rows:0,ticks:0,commands:[],after:[],tiles:[]};for(let y=1;y<=12;y++)for(let x=0;x<128;x++)input.tiles.push({id:id(x,y),kind:2,q:0});
const seed=runCase(input,'walking-cache-seed').result.city;assert.equal(seed.sim.population,0);
function cityWith(routes,active=null){const city=structuredClone(seed);city.sim.tick=127;city.sim.routes=routes.map(r=>[r.id,r.route]);city.sim.lookup=[...new Map(routes.map(r=>[signature(r.route.origin,r.route.dest,r.route.mode),r.id]))];city.sim.nextRoute=Math.max(...routes.map(r=>r.id))+1;if(active){const resident={id:1,home:active.origin,job:active.dest,dest:active.dest,purpose:1,cycle:0,state:2,cell:active.origin,from:active.origin,to:active.origin,step:0,route:active.id,mode:2,prior:0,dir:0,lane:0,slot:0,elapsed:0,duration:1000,wait:0,ready:0,departed:0,etaWalk:100,etaCar:20,eta:20,journeys:0,lastTime:0,reason:0,exitKey:0,zone:0,mask:0};Object.assign(city.sim,{agents:[[1,resident]],ids:[1],population:1,born:1,nextId:2,requested:1});}return city;}
function route(idn,mode,x=0,y=1,length=8){const path=Array.from({length},(_,i)=>id(x+i,y));return{id:idn,route:{path,cost:(length-1)*(mode===1?4:1),version:seed.world.version,origin:path[0],dest:path.at(-1),mode}};}
const walk=route(1,1),car=route(2,2,16,1),base=cityWith([walk,car],{...car.route,id:car.id});
const advance=(city,name,commands=[])=>runCase({city,ticks:1,commands,after:[]},name,'continuation').result;
const refreshed=advance(base,'walking-cache-refresh'),lookup=new Map(refreshed.city.sim.lookup),routes=new Map(refreshed.city.sim.routes);
const retained=lookup.get(signature(walk.route.origin,walk.route.dest,1))===1;
if(process.env.EXPECT_BASELINE==='1'){assert(!retained);fs.writeFileSync('evidence/walking-cache-before.json',JSON.stringify({passed:false,expected_baseline_limitation:true,artifact_sha256:selection.artifact_sha256,check:'a still-valid topology-only walking route is discarded at cycle128',before_routes:base.sim.routes.length,after_routes:routes.size,walking_lookup_retained:retained},null,2));console.log('Reproduced avoidable walking-route recomputation at cycle128');process.exit(0);}
assert(retained);assert(!lookup.has(signature(car.route.origin,car.route.dest,2)));assert(routes.has(2),'An active driving route must remain usable even after its cached choice expires');assert.equal(refreshed.conservation,0);assert.deepEqual(advance(base,'walking-cache-replay'),refreshed);
const changed=advance(base,'walking-cache-topology',[{op:'build',x:0,y:13,x2:1,y2:13,kind:2}]);assert.equal(changed.city.world.version,base.world.version+1);assert.equal(changed.city.sim.lookup.length,0,'Topology changes invalidate walking choices as well');
const many=[];for(let i=0;i<600;i++)many.push(route(i+1,1,i%58,1+Math.floor(i/58),70));const bounded=advance(cityWith(many),'walking-cache-bounds'),cached=new Map(bounded.city.sim.routes),ids=bounded.city.sim.lookup.map(([,n])=>n),steps=ids.reduce((n,id)=>n+cached.get(id).path.length,0);assert(ids.length<=512);assert(steps<=32768);assert(ids.includes(600));assert(!ids.includes(1));assert.equal(new Set(ids).size,ids.length);
const duplicate=route(3,1);const newest=advance(cityWith([walk,duplicate]),'walking-cache-duplicate');assert.equal(new Map(newest.city.sim.lookup).get(signature(walk.route.origin,walk.route.dest,1)),3);assert.equal(newest.city.sim.lookup.length,1);
const result={passed:true,artifact_sha256:selection.artifact_sha256,checks:['valid topology-only walking route survives refresh without changing its exact path','driving lookup expires while active driving path remains usable','a real native road edit invalidates retained walking choices','native replay is byte-for-byte deterministic','retained walking choices are bounded to512 entries and32768 path cells','duplicate signatures keep their newest-created valid route'],bounded_entries:ids.length,bounded_path_cells:steps};fs.writeFileSync('evidence/walking-cache.json',JSON.stringify(result,null,2));console.log(result);
