import {selectTool,districtPoint} from './ui-driver.mjs';
// WebKit engine compatibility and genuine touchscreen taps; multi-touch is tested separately in gestures.mjs.
import {createRequire} from 'node:module';const {webkit}=createRequire(import.meta.url)('playwright');import assert from 'node:assert/strict';import fs from 'node:fs';
const selectedArtifact=JSON.parse(fs.readFileSync(process.env.CITY_SELECTION||'.build/selection.json')).artifact_sha256;
const url=process.env.PREVIEW_URL||'http://127.0.0.1:19140/?session_port=19141',prefix=process.env.WEBKIT_EVIDENCE||'evidence/webkit';
const browser=await webkit.launch({headless:true,...(process.env.WEBKIT?{executablePath:process.env.WEBKIT}:{})}),errors=[],sockets=[],checks=[];
try{const context=await browser.newContext({viewport:{width:390,height:844},deviceScaleFactor:2,isMobile:true,hasTouch:true});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));page.on('websocket',s=>sockets.push(s.url()));await page.goto(url);await page.waitForFunction(()=>window.__flowgarden?.sessionStatus===1);await page.waitForTimeout(250);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth),390);assert.equal(await page.evaluate(()=>window.__flowgarden.tool),-2);checks.push('WebKit mobile page, native socket and full-height canvas');
await page.tap('#zoom-in');await page.tap('#zoom-out');await page.tap('#fit');await selectTool(page,2);for(const x of [14,15]){const p=await districtPoint(page,x,10);await page.touchscreen.tap(p.x,p.y)}await page.waitForFunction(()=>window.__flowgarden.stats.cash===756);assert.equal(await page.evaluate(()=>window.__flowgarden.pointerCount),0);checks.push('genuine touchscreen taps upgrade both bridge cells at $72 each and release capture');
await selectTool(page,-2);const p=await districtPoint(page,14,10);await page.touchscreen.tap(p.x,p.y);await page.waitForFunction(()=>!document.getElementById('inspector').hidden);assert.match(await page.locator('#inspect-title').textContent(),/Avenue/);await page.tap('#inspect-close');await page.tap('#menu-open');await page.tap('#help-open');assert(await page.locator('#help').isVisible());await page.tap('[data-close="help"]');await page.tap('#menu-close');checks.push('contextual inspection, help dialog and dismissal remain tappable');
await page.tap('#play');await page.waitForFunction(()=>window.__flowgarden.stats.tick>=4);await page.tap('#play');await page.waitForFunction(()=>window.__flowgarden.stats.paused);assert.equal(await page.evaluate(()=>window.__flowgarden.stats.requested>=window.__flowgarden.stats.arrived&&window.__flowgarden.stats.population===32),true);checks.push('native traffic starts and pauses with the same permanent population in WebKit');await page.screenshot({path:prefix+'-mobile.png'});
await page.setViewportSize({width:844,height:390});await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await page.tap('#fit');assert.equal(await page.evaluate(()=>window.__flowgarden.pointerCount),0);checks.push('landscape resizing preserves usable controls');await page.screenshot({path:prefix+'-landscape.png'});assert.deepEqual(errors,[]);if(process.env.EXPECTED_WSS)assert(sockets.every(s=>s===process.env.EXPECTED_WSS));const report={passed:true,url,browser:browser.version(),engine:'Playwright WebKit on Linux, mobile viewport and touchscreen enabled',artifact_sha256:selectedArtifact,checks,sockets,errors,limitations:['This is a WebKit engine test, not physical iPhone Safari.','Multi-touch gesture sequences are verified separately using Chromium input dispatch.']};fs.writeFileSync(prefix+'.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));}finally{await browser.close()}
