# Build one ephemeral first-occurrence index per service search. Keep station
# traversal order, candidate estimates and strict ties identical to linear search.
# Index + 1 reserves zero for missing cells, matching railpath::index's -1.
fn('pair-positions',[('path','(list I64)'),('i','I64'),('out','Numbers')],'Numbers',IF(lt(V('i'),llen('I64',V('path'))),LET([('id',at('I64',V('path'),V('i')))],C('pair-positions',V('path'),add(V('i'),I(1)),IF(eq(get(V('out'),V('id')),I(0)),put(V('out'),V('id'),add(V('i'),I(1))),V('out')))),V('out')))
fn('pair-scan',[('stops','(list I64)'),('positions','Numbers'),('origin','I64'),('dest','I64'),('i','I64'),('j','I64'),('best','RailPair')],'RailPair',LET([('n',llen('I64',V('stops')))],
 IF(le(V('n'),V('i')),V('best'),IF(le(V('n'),V('j')),C('pair-scan',V('stops'),V('positions'),V('origin'),V('dest'),add(V('i'),I(1)),I(0),V('best')),
 LET([('a',at('I64',V('stops'),V('i'))),('b',at('I64',V('stops'),V('j'))),('walkA',C('game::manhattan',V('origin'),V('a'))),('walkB',C('game::manhattan',V('b'),V('dest'))),('apart',mx(sub(V('i'),V('j')),sub(V('j'),V('i')))),('a0',get(V('positions'),V('a'))),('b0',get(V('positions'),V('b'))),('distance',mx(sub(V('a0'),V('b0')),sub(V('b0'),V('a0')))),('ride',mx(I(1),div(add(V('distance'),I(3)),I(4)))),('estimate',add(mul(add(V('walkA'),V('walkB')),I(3)),add(V('ride'),mul(mx(I(0),sub(V('apart'),I(1))),I(3)))))],
 C('pair-scan',V('stops'),V('positions'),V('origin'),V('dest'),V('i'),add(V('j'),I(1)),IF(AND(NOT(eq(V('i'),V('j'))),le(V('walkA'),I(12)),le(V('walkB'),I(12)),lt(V('estimate'),V('best.estimate'))),R(board=V('a'),alight=V('b'),estimate=V('estimate')),V('best'))))))))
fn('pair',[('l','RailLine'),('origin','I64'),('dest','I64'),('i','I64'),('j','I64'),('best','RailPair')],'RailPair',LET([('stops',C('stops',V('l')))],IF(le(llen('I64',V('stops')),V('i')),V('best'),C('pair-scan',V('stops'),C('pair-positions',C('path',V('l')),I(0),MP()),V('origin'),V('dest'),V('i'),V('j'),V('best')))))
fn('ride-between',[('l','RailLine'),('a','I64'),('b','I64')],'I64',LET([('stops',C('stops',V('l'))),('a0',C('index',V('stops'),V('a'),I(0))),('b0',C('index',V('stops'),V('b'),I(0)))],add(C('ride',V('l'),V('a'),V('b')),mul(mx(I(0),sub(mx(sub(V('a0'),V('b0')),sub(V('b0'),V('a0'))),I(1))),I(3)))))
