# Rail lines are indivisible objects. Rectangle review highlights their full extent.
fn('intersects-path',[('path','(list I64)'),('q','EditQuote'),('i','I64')],'Bool',IF(lt(V('i'),llen('I64',V('path'))),LET([('id',at('I64',V('path'),V('i')))],OR(AND(le(V('q.x'),C('game::x',V('id'))),le(C('game::x',V('id')),V('q.x2')),le(V('q.y'),C('game::y',V('id'))),le(C('game::y',V('id')),V('q.y2'))),C('intersects-path',V('path'),V('q'),add(V('i'),I(1))))),B(False)))
fn('intersects',[('l','RailLine'),('q','EditQuote')],'Bool',C('intersects-path',C('path',V('l')),V('q'),I(0)))
fn('selection',[('t','Transit'),('q','EditQuote'),('index','I64'),('out','Removal')],'Removal',IF(lt(V('index'),llen('I64',V('t.ids'))),LET([('l',line(V('t'),at('I64',V('t.ids'),V('index'))))],C('selection',V('t'),V('q'),add(V('index'),I(1)),IF(C('intersects',V('l'),V('q')),PATCH('Removal',V('out'),railIds=put(V('out.railIds'),V('l.id'),I(1)),rails=add(V('out.rails'),I(1)),refund=add(V('out.refund'),IF(eq(V('l.cost'),I(120)),I(60),I(0))),selected=V('out.selected')),V('out')))),V('out')))
fn('clean-queue',[('t','Transit'),('agents','Residents'),('l','RailLine'),('items','(list I64)'),('state','I64'),('station','I64'),('index','I64'),('out','(list I64)')],'(list I64)',IF(lt(V('index'),llen('I64',V('items'))),LET([
 ('id',at('I64',V('items'),V('index'))),('r',C('game::agent',V('agents'),V('id'))),('p',plan(V('t'),V('id')))],
 C('clean-queue',V('t'),V('agents'),V('l'),V('items'),V('state'),V('station'),add(V('index'),I(1)),IF(AND(eq(V('r.state'),V('state')),eq(V('p.line'),V('l.id')),OR(eq(V('state'),I(6)),eq(V('p.board'),V('station')))),append('I64',V('out'),V('id')),V('out')))),V('out')))
fn('clean-platforms',[('t','Transit'),('agents','Residents'),('l','RailLine'),('stops','(list I64)'),('i','I64')],'RailLine',IF(lt(V('i'),llen('I64',V('stops'))),LET([('station',at('I64',V('stops'),V('i'))),('a',IF(eq(V('station'),V('l.b')),V('l'),C('set-platform',V('l'),V('station'),I(1),C('clean-queue',V('t'),V('agents'),V('l'),C('platform',V('l'),V('station'),I(1)),I(5),V('station'),I(0),LS('I64'))))),('b',IF(eq(V('station'),V('l.a')),V('a'),C('set-platform',V('a'),V('station'),I(-1),C('clean-queue',V('t'),V('agents'),V('a'),C('platform',V('a'),V('station'),I(-1)),I(5),V('station'),I(0),LS('I64')))))],C('clean-platforms',V('t'),V('agents'),V('b'),V('stops'),add(V('i'),I(1)))),V('l')))
fn('keep-lines',[('t','Transit'),('removed','Numbers'),('agents','Residents'),('index','I64'),('out','Transit')],'Transit',IF(lt(V('index'),llen('I64',V('t.ids'))),LET([('l',line(V('t'),at('I64',V('t.ids'),V('index')))),('cleaned',PATCH('RailLine',V('l'),queueA=C('clean-queue',V('t'),V('agents'),V('l'),V('l.queueA'),I(5),V('l.a'),I(0),LS('I64')),queueB=C('clean-queue',V('t'),V('agents'),V('l'),V('l.queueB'),I(5),V('l.b'),I(0),LS('I64')),passengers=C('clean-queue',V('t'),V('agents'),V('l'),V('l.passengers'),I(6),I(0),I(0),LS('I64'))))],C('keep-lines',V('t'),V('removed'),V('agents'),add(V('index'),I(1)),IF(eq(get(V('removed'),V('l.id')),I(0)),PATCH('Transit',setline(V('out'),C('clean-platforms',V('t'),V('agents'),V('cleaned'),C('stops',V('l')),I(0))),ids=append('I64',V('out.ids'),V('l.id'))),V('out')))),V('out')))
fn('keep-plans',[('t','Transit'),('agents','Residents'),('ids','(list I64)'),('index','I64'),('out','Transit')],'Transit',IF(lt(V('index'),llen('I64',V('ids'))),LET([('id',at('I64',V('ids'),V('index'))),('r',C('game::agent',V('agents'),V('id'))),('p',plan(V('t'),V('id'))),('l',line(V('out'),V('p.line'))),('active',OR(eq(V('r.state'),I(1)),eq(V('r.state'),I(2)),eq(V('r.state'),I(5)),eq(V('r.state'),I(6))))],C('keep-plans',V('t'),V('agents'),V('ids'),add(V('index'),I(1)),PATCH('Transit',V('out'),plans=IF(AND(V('active'),lt(I(0),V('l.id'))),mput('I64 RailPlan',V('out.plans'),V('id'),V('p')),V('out.plans')),choices=IF(lt(I(0),get(V('t.choices'),V('id'))),put(V('out.choices'),V('id'),get(V('t.choices'),V('id'))),V('out.choices'))))),V('out')))
fn('remove-transit',[('t','Transit'),('removed','Numbers'),('agents','Residents'),('ids','(list I64)')],'Transit',C('keep-plans',V('t'),V('agents'),V('ids'),I(0),C('keep-lines',V('t'),V('removed'),V('agents'),I(0),PATCH('Transit',V('t'),lines=MP('I64 RailLine'),ids=LS('I64'),plans=MP('I64 RailPlan'),choices=MP()))))
