# Reusable track geometry, stations and ordered services. All construction is native.
fn('append-path',[('source','(list I64)'),('index','I64'),('out','(list I64)')],'(list I64)',IF(lt(V('index'),llen('I64',V('source'))),C('append-path',V('source'),add(V('index'),I(1)),append('I64',V('out'),at('I64',V('source'),V('index')))),V('out')))
fn('segment',[('a','I64'),('b','I64'),('out','(list I64)')],'(list I64)',LET([('next',append('I64',V('out'),V('a')))],IF(eq(V('a'),V('b')),V('next'),C('segment',C('game::neighbor',V('a'),IF(NOT(eq(C('game::x',V('a')),C('game::x',V('b')))),IF(lt(C('game::x',V('a')),C('game::x',V('b'))),I(0),I(2)),IF(lt(V('a'),V('b')),I(1),I(3)))),V('b'),V('next')))))
fn('path',[('l','RailLine')],'(list I64)',IF(lt(I(0),llen('I64',V('l.path'))),V('l.path'),C('segment',V('l.a'),V('l.b'),LS('I64'))))
fn('stops',[('l','RailLine')],'(list I64)',IF(lt(I(1),llen('I64',V('l.stops'))),V('l.stops'),LS('I64',V('l.a'),V('l.b'))))
fn('index',[('items','(list I64)'),('id','I64'),('i','I64')],'I64',IF(lt(V('i'),llen('I64',V('items'))),IF(eq(at('I64',V('items'),V('i')),V('id')),V('i'),C('index',V('items'),V('id'),add(V('i'),I(1)))),I(-1)))
fn('distance',[('l','RailLine'),('a','I64'),('b','I64')],'I64',LET([('p',C('path',V('l'))),('a0',C('index',V('p'),V('a'),I(0))),('b0',C('index',V('p'),V('b'),I(0)))],mx(sub(V('a0'),V('b0')),sub(V('b0'),V('a0')))))
fn('service-direction',[('l','RailLine')],'I64',IF(eq(V('l.from'),V('l.a')),I(1),IF(eq(V('l.from'),V('l.b')),I(-1),IF(eq(V('l.direction'),I(-1)),I(-1),I(1)))))
fn('next-stop',[('l','RailLine')],'I64',LET([('s',C('stops',V('l'))),('i',C('index',V('s'),V('l.from'),I(0)))],at('I64',V('s'),mx(I(0),mn(sub(llen('I64',V('s')),I(1)),add(V('i'),C('service-direction',V('l'))))))))
fn('ride',[('l','RailLine'),('a','I64'),('b','I64')],'I64',mx(I(1),div(add(C('distance',V('l'),V('a'),V('b')),I(3)),I(4))))
fn('queue-key',[('station','I64'),('direction','I64')],'I64',add(mul(V('station'),I(2)),IF(eq(V('direction'),I(1)),I(1),I(0))))
fn('travel-direction',[('l','RailLine'),('a','I64'),('b','I64')],'I64',IF(lt(C('index',C('stops',V('l')),V('a'),I(0)),C('index',C('stops',V('l')),V('b'),I(0))),I(1),I(-1)))
fn('platform',[('l','RailLine'),('station','I64'),('direction','I64')],'(list I64)',mget('I64 (list I64)',V('l.queues'),C('queue-key',V('station'),V('direction')),IF(eq(V('station'),V('l.a')),V('l.queueA'),IF(eq(V('station'),V('l.b')),V('l.queueB'),LS('I64')))))
fn('set-platform',[('l','RailLine'),('station','I64'),('direction','I64'),('queue','(list I64)')],'RailLine',PATCH('RailLine',V('l'),queues=mput('I64 (list I64)',V('l.queues'),C('queue-key',V('station'),V('direction')),V('queue')),queueA=IF(eq(V('station'),V('l.a')),V('queue'),V('l.queueA')),queueB=IF(eq(V('station'),V('l.b')),V('queue'),V('l.queueB'))))
fn('waiting-loop',[('l','RailLine'),('stops','(list I64)'),('i','I64')],'I64',IF(lt(V('i'),llen('I64',V('stops'))),LET([('id',at('I64',V('stops'),V('i')))],add(add(IF(eq(V('id'),V('l.b')),I(0),llen('I64',C('platform',V('l'),V('id'),I(1)))),IF(eq(V('id'),V('l.a')),I(0),llen('I64',C('platform',V('l'),V('id'),I(-1))))),C('waiting-loop',V('l'),V('stops'),add(V('i'),I(1))))),I(0)))
fn('waiting',[('l','RailLine')],'I64',C('waiting-loop',V('l'),C('stops',V('l')),I(0)))
fn('track-put',[('path','(list I64)'),('i','I64'),('tiles','Numbers')],'Numbers',IF(lt(V('i'),llen('I64',V('path'))),C('track-put',V('path'),add(V('i'),I(1)),put(V('tiles'),at('I64',V('path'),V('i')),I(2))),V('tiles')))
fn('keys',[('pairs','(list Pair)'),('i','I64'),('out','(list I64)')],'(list I64)',IF(lt(V('i'),llen('Pair',V('pairs'))),C('keys',V('pairs'),add(V('i'),I(1)),append('I64',V('out'),F(at('Pair',V('pairs'),V('i')),'key'))),V('out')))
fn('track-ids',[('t','Transit')],'(list I64)',C('keys',G('std::map-entries','I64 I64',V('t.tracks')),I(0),LS('I64')))
fn('path-slice',[('p','(list I64)'),('i','I64'),('end','I64'),('d','I64'),('out','(list I64)')],'(list I64)',LET([('next',append('I64',V('out'),at('I64',V('p'),V('i'))))],IF(eq(V('i'),V('end')),V('next'),C('path-slice',V('p'),add(V('i'),V('d')),V('end'),V('d'),V('next')))))
fn('leg',[('l','RailLine'),('a','I64'),('b','I64')],'(list I64)',LET([('p',C('path',V('l'))),('a0',C('index',V('p'),V('a'),I(0))),('b0',C('index',V('p'),V('b'),I(0)))],IF(AND(le(I(0),V('a0')),le(I(0),V('b0'))),C('path-slice',V('p'),V('a0'),V('b0'),IF(le(V('a0'),V('b0')),I(1),I(-1)),LS('I64')),LS('I64'))))
fn('shares',[('path','(list I64)'),('i','I64'),('occupied','Numbers')],'Bool',IF(lt(V('i'),llen('I64',V('path'))),OR(lt(I(0),get(V('occupied'),at('I64',V('path'),V('i')))),C('shares',V('path'),add(V('i'),I(1)),V('occupied'))),B(False)))
fn('blocked',[('t','Transit'),('l','RailLine'),('i','I64')],'Bool',IF(lt(V('i'),llen('I64',V('t.ids'))),LET([('other',mget('I64 RailLine',V('t.lines'),at('I64',V('t.ids'),V('i')),ZERO('RailLine')))],OR(AND(NOT(eq(V('l.id'),V('other.id'))),lt(V('other.elapsed'),V('other.duration')),C('shares',C('leg',V('l'),V('l.from'),C('next-stop',V('l'))),I(0),C('track-put',C('leg',V('other'),V('other.from'),V('other.to')),I(0),MP()))),C('blocked',V('t'),V('l'),add(V('i'),I(1))))),B(False)))
# Track construction follows an orthogonal polyline with a visible rounded bend.
fn('track-plan',[('city','City'),('path','(list I64)'),('i','I64'),('out','TrackBuild')],'TrackBuild',IF(lt(V('i'),llen('I64',V('path'))),LET([('id',at('I64',V('path'),V('i'))),('existing',lt(I(0),get(V('out.tiles'),V('id'))))],C('track-plan',V('city'),V('path'),add(V('i'),I(1)),PATCH('TrackBuild',V('out'),valid=AND(V('out.valid'),NOT(C('game::building',get(V('city.world.tiles'),V('id'))))),tiles=put(V('out.tiles'),V('id'),I(2)),cost=add(V('out.cost'),IF(V('existing'),I(0),IF(C('water',V('city'),V('id')),I(36),I(12))))))),V('out')))
fn('track-build',[('city','City'),('c','Command')],'Outcome',IF(AND(*[AND(le(I(0),V('c.'+k)),le(V('c.'+k),I(127))) for k in ['x','y','x2','y2']],OR(eq(V('c.kind'),I(0)),eq(V('c.kind'),I(1)))),LET([
 ('a',C('game::id',V('c.x'),V('c.y'))),('b',C('game::id',V('c.x2'),V('c.y2'))),('bend',IF(eq(V('c.kind'),I(0)),C('game::id',V('c.x2'),V('c.y')),C('game::id',V('c.x'),V('c.y2')))),
 ('path',C('append-path',C('segment',V('bend'),V('b'),LS('I64')),I(1),C('segment',V('a'),V('bend'),LS('I64'))))],
 IF(lt(I(128),llen('I64',V('path'))),R(city=V('city'),notice=T('Draw at most 128 track tiles at a time.')),LET([('p',C('track-plan',V('city'),V('path'),I(0),ZERO('TrackBuild',tiles=V('city.sim.transit.tracks'),valid=B(True))))],
 IF(OR(NOT(V('p.valid')),lt(I(2048),mlen('I64 I64',V('p.tiles')))),R(city=V('city'),notice=T('Track may cross roads and water, but not buildings. Limit: 2,048 track tiles.')),
 IF(lt(V('city.cash'),V('p.cost')),R(city=V('city'),notice=T('Track costs $12 per new tile, or $36 over water.')),
 R(city=PATCH('City',V('city'),cash=sub(V('city.cash'),V('p.cost')),world=PATCH('World',V('city.world'),version=add(V('city.world.version'),I(1))),sim=PATCH('Sim',V('city.sim'),transit=PATCH('Transit',V('city.sim.transit'),tracks=V('p.tiles')))),notice=T('Track built. Add stations on dry track beside walking access, then create a service.'))))))),
 R(city=V('city'),notice=T('Invalid track coordinates or bend direction.'))))
fn('station-build',[('city','City'),('c','Command')],'Outcome',IF(AND(le(I(0),V('c.x')),lt(V('c.x'),I(128)),le(I(0),V('c.y')),lt(V('c.y'),I(128))),LET([('id',C('game::id',V('c.x'),V('c.y')))],
 IF(AND(lt(I(0),get(V('city.sim.transit.tracks'),V('id'))),eq(get(V('city.world.tiles'),V('id')),I(0)),NOT(C('water',V('city'),V('id'))),C('access',V('city.world'),V('id'),I(0)),le(I(90),V('city.cash')),lt(llen('I64',V('city.world.ids')),I(8192))),
 R(city=PATCH('City',V('city'),cash=sub(V('city.cash'),I(90)),world=C('game::world',put(V('city.world.tiles'),V('id'),I(8)),V('city.world.signals'),add(V('city.world.version'),I(1))),sim=PATCH('Sim',V('city.sim'),lookup=MP())),notice=T('Station opened. Select stations in travel order to create a service.')),
 R(city=V('city'),notice=T('A $90 station needs empty dry track next to a road or footpath.')))),
 R(city=V('city'),notice=T('Invalid station coordinates.'))))
fn('track-route',[('t','Transit'),('a','I64'),('b','I64')],'Route',C('game::find-route',C('game::world',V('t.tracks'),MP(),I(1)),MP(),V('a'),V('b'),I(2)))
fn('service-pair',[('city','City'),('c','Command')],'Outcome',LET([('a',C('game::id',V('c.x'),V('c.y'))),('b',C('game::id',V('c.x2'),V('c.y2')))],
 IF(AND(*[AND(le(I(0),V('c.'+k)),le(V('c.'+k),I(127))) for k in ['x','y','x2','y2']],NOT(eq(V('a'),V('b'))),eq(get(V('city.world.tiles'),V('a')),I(8)),eq(get(V('city.world.tiles'),V('b')),I(8)),lt(llen('I64',V('city.sim.transit.ids')),I(4)),le(I(120),V('city.cash'))),
 LET([('r',C('track-route',V('city.sim.transit'),V('a'),V('b'))),('id',add(V('city.sim.transit.nextId'),I(1)))],
 IF(AND(le(I(0),V('r.cost')),le(llen('I64',V('r.path')),I(256))),
 LET([('l',ZERO('RailLine',id=V('id'),a=V('a'),b=V('b'),**{'from':V('a'),'to':V('a')},path=V('r.path'),stops=LS('I64',V('a'),V('b')),direction=I(1),dwell=I(3),capacity=I(16),cost=I(120),rideTicks=div(add(llen('I64',V('r.path')),I(2)),I(4))))],
 R(city=PATCH('City',V('city'),cash=sub(V('city.cash'),I(120)),world=PATCH('World',V('city.world'),version=add(V('city.world.version'),I(1))),sim=PATCH('Sim',V('city.sim'),transit=PATCH('Transit',setline(V('city.sim.transit'),V('l')),nextId=V('id'),ids=append('I64',V('city.sim.transit.ids'),V('id'))))),notice=T('Service created and suspended. Add more stops or enable departures.'))),
 R(city=V('city'),notice=T('Stations need connected track; a service route is limited to 256 tiles.')))),
 R(city=V('city'),notice=T('Select two different stations. A train costs $120; at most four services.')))))
fn('insert-stop',[('path','(list I64)'),('stops','(list I64)'),('station','I64'),('i','I64'),('added','Bool'),('out','(list I64)')],'(list I64)',IF(lt(V('i'),llen('I64',V('stops'))),LET([('id',at('I64',V('stops'),V('i'))),('before',AND(NOT(V('added')),lt(C('index',V('path'),V('station'),I(0)),C('index',V('path'),V('id'),I(0)))))],C('insert-stop',V('path'),V('stops'),V('station'),add(V('i'),I(1)),OR(V('added'),V('before')),append('I64',IF(V('before'),append('I64',V('out'),V('station')),V('out')),V('id')))),IF(V('added'),V('out'),append('I64',V('out'),V('station')))))
fn('add-stop',[('city','City'),('c','Command')],'Outcome',LET([('l',line(V('city.sim.transit'),V('c.x'))),('s',C('stops',V('l'))),('p',C('path',V('l'))),('id',V('c.y'))],
 IF(AND(V('city.paused'),lt(I(0),V('l.id')),NOT(V('l.enabled')),eq(llen('I64',V('l.passengers')),I(0)),eq(C('waiting',V('l')),I(0)),NOT(lt(V('l.elapsed'),V('l.duration'))),lt(llen('I64',V('s')),I(8)),le(I(0),V('id')),lt(V('id'),I(16384)),eq(get(V('city.world.tiles'),V('id')),I(8)),lt(C('index',V('s'),V('id'),I(0)),I(0))),
 LET([('inside',le(I(0),C('index',V('p'),V('id'),I(0)))),('r',IF(V('inside'),ZERO('Route',path=V('p')),C('track-route',V('city.sim.transit'),V('l.b'),V('id')))),('joined',IF(V('inside'),V('p'),C('append-path',V('r.path'),I(1),V('p')))),('s2',C('insert-stop',V('joined'),V('s'),V('id'),I(0),B(False),LS('I64')))],
 IF(AND(le(I(0),V('r.cost')),le(llen('I64',V('joined')),I(256)),OR(V('inside'),NOT(C('shares',V('r.path'),I(1),C('track-put',V('p'),I(0),MP()))))),
 R(city=PATCH('City',V('city'),world=PATCH('World',V('city.world'),version=add(V('city.world.version'),I(1))),sim=PATCH('Sim',V('city.sim'),lookup=MP(),transit=setline(V('city.sim.transit'),PATCH('RailLine',V('l'),b=IF(V('inside'),V('l.b'),V('id')),path=V('joined'),stops=V('s2'),rideTicks=div(add(llen('I64',V('joined')),I(2)),I(4)))))),notice=T('Stop added. Enable service when ready.')),
 R(city=V('city'),notice=T('Connect a new branch beyond the last stop, or choose a station already along the route.')))),
 R(city=V('city'),notice=T('Pause and suspend an empty train at a station before changing stops. Limit: eight stops per service.')))))

fn('create-service',[('city','City'),('c','Command')],'Outcome',IF(AND(*[AND(le(I(0),V('c.'+k)),le(V('c.'+k),I(127))) for k in ['x','y','x2','y2']]),C('service-pair',V('city'),V('c')),R(city=V('city'),notice=T('Invalid station coordinates.'))))
