"""Native reviewed demolition. Relocation is explicit, cancelled, and earns no income."""
from native import *
D=[]
def fn(n,p,r,b): D.append(FN(n,p,r,b))
fn('within',[('q','EditQuote'),('id','I64')],'Bool',AND(le(V('q.x'),C('game::x',V('id'))),le(C('game::x',V('id')),V('q.x2')),le(V('q.y'),C('game::y',V('id'))),le(C('game::y',V('id')),V('q.y2'))))
fn('selected',[('tiles','Numbers'),('id','I64')],'Bool',lt(I(0),get(V('tiles'),V('id'))))
fn('active',[('r','Resident')],'Bool',OR(eq(V('r.state'),I(1)),eq(V('r.state'),I(2)),eq(V('r.state'),I(4)),eq(V('r.state'),I(5)),eq(V('r.state'),I(6))))
fn('affected',[('selected','Numbers'),('rails','Numbers'),('t','Transit'),('r','Resident')],'Bool',OR(lt(I(0),get(V('rails'),F(C('rail::plan',V('t'),V('r.id')),'line'))),C('selected',V('selected'),V('r.cell')),AND(C('active',V('r')),C('selected',V('selected'),V('r.dest'))),AND(eq(V('r.state'),I(2)),lt(V('r.elapsed'),V('r.duration')),C('selected',V('selected'),V('r.from'))),AND(lt(I(0),V('r.exitKey')),C('selected',V('selected'),div(sub(V('r.exitKey'),I(1)),I(8))))))
fn('tiles',[('world','World'),('q','EditQuote'),('index','I64'),('r','Removal')],'Removal',IF(lt(V('index'),llen('I64',V('world.ids'))),LET([('id',at('I64',V('world.ids'),V('index'))),('kind',get(V('world.tiles'),V('id')))],C('tiles',V('world'),V('q'),add(V('index'),I(1)),IF(OR(C('within',V('q'),V('id')),C('selected',V('r.selected'),V('id'))),PATCH('Removal',V('r'),tiles=G('std::map-remove','I64 I64',V('r.tiles'),V('id')),signals=G('std::map-remove','I64 I64',V('r.signals'),V('id')),selected=put(V('r.selected'),V('id'),V('kind')),count=add(V('r.count'),I(1)),homes=add(V('r.homes'),IF(eq(V('kind'),I(3)),I(1),I(0))),refund=add(V('r.refund'),IF(eq(V('kind'),I(8)),I(45),div(C('game::price',V('kind')),I(2))))),V('r')))),V('r')))
fn('home',[('r','Resident'),('tick','I64')],'Resident',PATCH('Resident',V('r'),state=I(0),cell=V('r.home'),dest=V('r.home'),purpose=I(0),route=I(0),step=I(0),mode=I(0),wait=I(0),reason=I(0),exitKey=I(0),zone=I(0),mask=I(0),elapsed=I(0),duration=I(0),slot=I(0),ready=add(V('tick'),I(8)),**{'from':V('r.home'),'to':V('r.home')}))
fn('residents',[('sim','Sim'),('selected','Numbers'),('rails','Numbers'),('index','I64'),('out','Relocation')],'Relocation',IF(lt(V('index'),llen('I64',V('sim.ids'))),LET([('id',at('I64',V('sim.ids'),V('index'))),('r',C('game::agent',V('sim.agents'),V('id'))),('leaving',C('selected',V('selected'),V('r.home'))),('affected',C('affected',V('selected'),V('rails'),V('sim.transit'),V('r'))),('cancelled',AND(OR(V('leaving'),V('affected')),C('active',V('r'))))],C('residents',V('sim'),V('selected'),V('rails'),add(V('index'),I(1)),PATCH('Relocation',V('out'),agents=IF(V('leaving'),V('out.agents'),mput('I64 Resident',V('out.agents'),V('id'),IF(V('affected'),C('home',V('r'),V('sim.tick')),V('r')))),ids=IF(V('leaving'),V('out.ids'),append('I64',V('out.ids'),V('id'))),moveouts=add(V('out.moveouts'),IF(V('leaving'),I(1),I(0))),relocated=add(V('out.relocated'),IF(AND(NOT(V('leaving')),V('affected')),I(1),I(0))),cancelled=add(V('out.cancelled'),IF(V('cancelled'),I(1),I(0)))))),V('out')))
fn('track-tiles',[('city','City'),('q','EditQuote'),('pairs','(list Pair)'),('i','I64'),('r','Removal')],'Removal',IF(lt(V('i'),llen('Pair',V('pairs'))),LET([('id',F(at('Pair',V('pairs'),V('i')),'key'))],C('track-tiles',V('city'),V('q'),V('pairs'),add(V('i'),I(1)),IF(C('within',V('q'),V('id')),PATCH('Removal',V('r'),tracks=G('std::map-remove','I64 I64',V('r.tracks'),V('id')),count=add(V('r.count'),IF(eq(get(V('city.world.tiles'),V('id')),I(0)),I(1),I(0))),refund=add(V('r.refund'),IF(C('rail::water',V('city'),V('id')),I(18),I(6)))),V('r')))),V('r')))
fn('removal',[('city','City'),('q','EditQuote')],'Removal',C('tiles',V('city.world'),V('q'),I(0),C('track-tiles',V('city'),V('q'),G('std::map-entries','I64 I64',V('city.sim.transit.tracks')),I(0),C('railedit::selection',V('city.sim.transit'),V('q'),I(0),ZERO('Removal',tracks=V('city.sim.transit.tracks'),tiles=V('city.world.tiles'),signals=V('city.world.signals'))))))
fn('quote',[('city','City'),('command','Command'),('id','I64')],'EditQuote',LET([('q',ZERO('EditQuote',id=V('id'),version=V('city.world.version'),x=mn(V('command.x'),V('command.x2')),y=mn(V('command.y'),V('command.y2')),x2=mx(V('command.x'),V('command.x2')),y2=mx(V('command.y'),V('command.y2'))))],IF(AND(le(I(0),V('q.x')),le(I(0),V('q.y')),le(V('q.x2'),I(127)),le(V('q.y2'),I(127)),le(mul(add(sub(V('q.x2'),V('q.x')),I(1)),add(sub(V('q.y2'),V('q.y')),I(1))),I(256))),LET([('r',C('removal',V('city'),V('q'))),('people',C('residents',V('city.sim'),V('r.selected'),V('r.railIds'),I(0),ZERO('Relocation')))],PATCH('EditQuote',V('q'),tiles=V('r.count'),homes=V('r.homes'),moveouts=V('people.moveouts'),relocated=V('people.relocated'),cancelled=V('people.cancelled'),refund=V('r.refund'),rails=V('r.rails'),valid=lt(I(0),V('r.count')))),V('q'))))
fn('apply',[('city','City'),('q','EditQuote')],'Outcome',IF(AND(V('q.valid'),V('city.paused'),eq(V('q.version'),V('city.world.version'))),LET([('r',C('removal',V('city'),V('q'))),('people',C('residents',V('city.sim'),V('r.selected'),V('r.railIds'),I(0),ZERO('Relocation'))),('sim',PATCH('Sim',V('city.sim'),agents=V('people.agents'),ids=V('people.ids'),transit=PATCH('Transit',C('railedit::remove-transit',V('city.sim.transit'),V('r.railIds'),V('people.agents'),V('people.ids')),tracks=V('r.tracks')),population=sub(V('city.sim.population'),V('people.moveouts')),removed=add(V('city.sim.removed'),V('people.moveouts')),cancelled=add(V('city.sim.cancelled'),V('people.cancelled')))),('city2',C('traffic::replace-world',PATCH('City',V('city'),sim=V('sim')),V('r.tiles'),V('r.signals'),sub(I(0),V('r.refund')),sub(I(0),V('r.homes'))))],R(city=V('city2'),notice=T('Area removed. Salvage refunded; affected journeys were cancelled without income.'))),R(city=V('city'),notice=T('This review has expired. Select the area again.'))))
D.append(TEST('negative-removal-rejected',F(C('quote',ZERO('City'),R(op=T('review-remove'),x=I(-1),y=I(0),x2=I(1),y2=I(1),kind=I(0)),I(1)),'valid'),B(False)))
emit('removal','remove',D)
