from protocol import *
D=[]
def fn(n,p,r,b):D.append(FN(n,p,r,b))
fn('cell',[('city','City'),('id','I64')],'Cell',R(id=V('id'),kind=get(V('city.world.tiles'),V('id')),q=get(V('city.sim.q'),V('id')),walk=get(V('city.sim.walkq'),V('id')),flow=get(V('city.sim.flow'),V('id')),inside=get(V('city.sim.inside'),V('id')),junction=get(V('city.world.junctions'),V('id')),control=get(V('city.world.signals'),V('id'))))
fn('same',[('a','Cell'),('b','Cell')],'Bool',AND(*[eq(V('a.'+k),V('b.'+k)) for k in TYPES['Cell']]))
fn('detail',[('view','View')],'Bool',le(mul(V('view.w'),V('view.h')),I(1024)))
fn('picture-loop',[('city','City'),('view','View'),('old','Seen'),('index','I64'),('picture','Picture')],'Picture',IF(lt(V('index'),mul(V('view.w'),V('view.h'))),LET([('id',add(mul(V('view.layer'),I(16384)),C('game::id',add(V('view.x'),mod(V('index'),V('view.w'))),add(V('view.y'),div(V('index'),V('view.w')))))),('cell',C('cell',V('city'),V('id'))),('previous',mget('I64 Cell',V('old'),V('id'),ZERO('Cell',id=V('id')))),('same',C('same',V('cell'),V('previous')))],C('picture-loop',V('city'),V('view'),V('old'),add(V('index'),I(1)),R(seen=IF(lt(I(0),V('cell.kind')),mput('I64 Cell',V('picture.seen'),V('id'),V('cell')),V('picture.seen')),changed=IF(V('same'),V('picture.changed'),append('Cell',V('picture.changed'),V('cell')))))),V('picture')))
fn('picture',[('city','City'),('view','View'),('old','Seen')],'Picture',IF(C('detail',V('view')),C('picture-loop',V('city'),V('view'),V('old'),I(0),ZERO('Picture')),ZERO('Picture')))
fn('visible',[('view','View'),('cell','I64')],'Bool',AND(eq(C('roads::layer',V('cell')),V('view.layer')),le(V('view.x'),C('game::x',V('cell'))),lt(C('game::x',V('cell')),add(V('view.x'),V('view.w'))),le(V('view.y'),C('game::y',V('cell'))),lt(C('game::y',V('cell')),add(V('view.y'),V('view.h')))))

fn('heat',[('pairs','(list Pair)'),('index','I64'),('result','(list I64)')],'(list I64)',IF(AND(lt(V('index'),llen('Pair',V('pairs'))),lt(llen('I64',V('result')),I(2048))),LET([('p',at('Pair',V('pairs'),V('index')))],C('heat',V('pairs'),add(V('index'),I(1)),append('I64',V('result'),add(mul(V('p.key'),I(32)),mn(I(31),V('p.value')))))),V('result')))
fn('platforms',[('l','RailLine'),('stops','(list I64)'),('i','I64'),('out','(list RailPlatform)')],'(list RailPlatform)',IF(lt(V('i'),llen('I64',V('stops'))),LET([('id',at('I64',V('stops'),V('i')))],C('platforms',V('l'),V('stops'),add(V('i'),I(1)),append('RailPlatform',V('out'),R(station=V('id'),forward=IF(eq(V('id'),V('l.b')),I(0),llen('I64',C('railpath::platform',V('l'),V('id'),I(1)))),reverse=IF(eq(V('id'),V('l.a')),I(0),llen('I64',C('railpath::platform',V('l'),V('id'),I(-1)))))))),V('out')))
fn('rails',[('t','Transit'),('index','I64'),('out','(list RailView)')],'(list RailView)',IF(lt(V('index'),llen('I64',V('t.ids'))),LET([('l',C('rail::line',V('t'),at('I64',V('t.ids'),V('index'))))],C('rails',V('t'),add(V('index'),I(1)),append('RailView',V('out'),R(**{k:V('l.'+k) for k in TYPES['RailLine'] if k not in ['queueA','queueB','passengers','queues']},platforms=C('platforms',V('l'),C('railpath::stops',V('l')),I(0),LS('RailPlatform')),occupancy=llen('I64',V('l.passengers')),waitingA=llen('I64',V('l.queueA')),waitingB=llen('I64',V('l.queueB')),expense=C('rail::expense',V('l')))))),V('out')))
fn('rail-waiting',[('t','Transit'),('index','I64')],'I64',IF(lt(V('index'),llen('I64',V('t.ids'))),LET([('l',C('rail::line',V('t'),at('I64',V('t.ids'),V('index'))))],add(C('railpath::waiting',V('l')),C('rail-waiting',V('t'),add(V('index'),I(1))))),I(0)))
# Separate engine planning from infrastructure waits without changing either.
fn('planning-counts',[('agents','Residents'),('ids','(list I64)'),('index','I64'),('total','I64'),('long','I64')],'PlanningCounts',IF(lt(V('index'),llen('I64',V('ids'))),LET([('r',C('game::agent',V('agents'),at('I64',V('ids'),V('index')))),('pending',AND(eq(V('r.state'),I(1)),eq(V('r.reason'),I(8))))],C('planning-counts',V('agents'),V('ids'),add(V('index'),I(1)),add(V('total'),IF(V('pending'),I(1),I(0))),add(V('long'),IF(AND(V('pending'),le(I(8),V('r.wait'))),I(1),I(0))))),R(total=V('total'),long=V('long'))))
fn('stats',[('city','City')],'Stats',LET([('planning',C('planning-counts',V('city.sim.agents'),V('city.sim.ids'),I(0),I(0),I(0)))],R(planning=V('planning.total'),planningLong=V('planning.long'),**{'eco'+k[0].upper()+k[1:]:V('city.economy.'+k) for k in ECONOMY_FIELDS},wealthError=C('money::conservation',V('city')),**{k:V('city.sim.'+k) for k in 'tick requested arrived population visits workVisits shopVisits leisureVisits moving waiting disconnected walkTrips carTrips healthy cancelled'.split()},**{k:V('city.'+k) for k in 'cash level permits paused originX originY'.split()},railLines=llen('I64',V('city.sim.transit.ids')),railBoardings=V('city.sim.transit.boardings'),railCompleted=V('city.sim.transit.completed'),railSpent=V('city.sim.transit.spent'),railWaiting=C('rail-waiting',V('city.sim.transit'),I(0)),average=IF(lt(I(0),V('city.sim.arrived')),div(V('city.sim.totalDuration'),V('city.sim.arrived')),I(0)),growthTarget=C('traffic::growth-target',V('city.level')),growthCost=C('traffic::growth-cost',V('city.level')),progress=sub(V('city.sim.visits'),V('city.milestone')),growth=C('traffic::growth-ready',V('city')),version=V('city.world.version'),tiles=llen('I64',V('city.world.ids')),phase=C('game::phase',V('city.sim.tick')),routes=mlen('I64 Route',V('city.sim.routes')))))
fn('selected',[('city','City'),('cell','I64'),('index','I64')],'I64',IF(lt(V('index'),llen('I64',V('city.sim.ids'))),LET([('r',C('game::agent',V('city.sim.agents'),at('I64',V('city.sim.ids'),V('index'))))],IF(OR(eq(V('r.cell'),V('cell')),eq(V('r.home'),V('cell'))),V('r.id'),C('selected',V('city'),V('cell'),add(V('index'),I(1))))),I(-1)))
fn('view',[('command','Command')],'View',LET([('w',mn(I(128),mx(I(1),V('command.x2')))),('h',mn(I(128),mx(I(1),V('command.y2'))))],R(x=mx(I(0),mn(sub(I(128),V('w')),V('command.x'))),y=mx(I(0),mn(sub(I(128),V('h')),V('command.y'))),w=V('w'),h=V('h'),layer=IF(eq(V('command.kind'),I(1)),I(1),I(0)))))
fn('empty-state',[],'State',ZERO('State',city=C('town::initial'),view=R(x=I(49),y=I(54),w=I(30),h=I(20),layer=I(0)),saved=I(-1),mapVersion=I(-1),selection=I(-1)))
# Full static topology is sent only on a new version. Detailed deltas follow on the next callback.
fn('emit',[('state','State'),('reset','Bool'),('notice','Text'),('kind','std::SessionDecisionKind')],'Decision',LET([('shown',C('labbase::shown',V('state.city'),V('state.lab'))),('mapChanged',NOT(eq(V('state.mapVersion'),V('shown.world.version')))),('detail',C('detail',V('state.view'))),('picture',IF(V('mapChanged'),ZERO('Picture'),C('picture',V('shown'),V('state.view'),IF(V('reset'),MP('I64 Cell'),V('state.seen'))))),('street',IF(V('mapChanged'),ZERO('StreetSample'),C('actorview::sample',V('shown'),V('state.view')))),('seq',add(V('state.seq'),I(1))),('next',PATCH('State',V('state'),lab=PATCH('Lab',V('state.lab'),atlasSent=eq(V('state.lab.phase'),I(4))),seq=V('seq'),seen=V('picture.seen'),mapVersion=V('shown.world.version'))),('frame',R(river=IF(V('mapChanged'),C('terrain::spine',V('shown'),I(0),LS('I64')),LS('I64')),riverWidth=C('terrain::width',V('shown')),lab=C('labmetrics::report',V('state.city'),V('state.lab')),inspectFunds=get(V('shown.economy.wallets'),V('state.selection')),tracks=IF(V('mapChanged'),C('railpath::track-ids',V('shown.sim.transit')),LS('I64')),view=V('state.view'),persistent=B(True),seq=V('seq'),ack=V('state.ack'),reset=OR(V('reset'),V('mapChanged')),cells=V('picture.changed'),actors=V('street.actors'),streetWalkers=V('street.walking'),streetDrivers=V('street.driving'),overview=IF(V('mapChanged'),V('shown.world.overview'),LS('I64')),mapChanged=V('mapChanged'),heat=IF(OR(V('detail'),V('mapChanged')),LS('I64'),C('heat',G('std::map-entries','I64 I64',V('shown.sim.q')),I(0),LS('I64'))),stats=C('stats',V('shown')),notice=V('notice'),saved=V('state.saved'),status=V('state.status'),inspect=C('game::agent',V('shown.sim.agents'),V('state.selection')),detail=V('detail'),actorLimit=I(128),quote=IF(lt(I(0),V('state.lab.phase')),V('state.lab.quote'),V('state.quote')),management=V('state.management'),confirmation=V('state.confirmation'),undo=V('state.undo'),rails=C('rails',V('shown.sim.transit'),I(0),LS('RailView')),inspectRail=C('rail::plan',V('shown.sim.transit'),V('state.selection'))))],R(kind=V('kind'),state=some('State',V('next')),messages=LS('std::SessionOutbound',variant('std::SessionOutbound::text',C('std::bytes-to-text',G('std::json-encode','Frame',V('frame'))))),closing=none('std::SessionClose'),rejection=none('std::SessionReject'))))
fn('finish',[],'Decision',R(kind=variant('std::SessionDecisionKind::finish'),state=none('State'),messages=LS('std::SessionOutbound'),closing=none('std::SessionClose'),rejection=none('std::SessionReject')))
# Separate viewport/metric projections from the state-bearing frame encoder so
# each public declaration request stays inside the pinned authoring admission.
import re
stateful={'empty-state','emit','finish'}
projection=[];transport=[]
for definition in D:
 name=re.search(r'\(function create ([^ ]+)',definition)[1]
 if name in stateful:
  def qualify(m):
   n=m[1]
   return '(call '+('viewdata::'+n if n not in stateful and '::' not in n else n)
  definition=re.sub(r'\(call ([a-z][a-z:-]*)(?=[ )])',qualify,definition)
  transport.append(definition)
 else:projection.append(definition)
emit('viewdata','viewdata',projection)
emit('views','view',transport)
