import {createCityLab} from './lab.js';
import {TrafficMotion,actorPose} from './motion.js';
const trafficMotion=new TrafficMotion();
// Browser presentation and gestures only. lkjscript owns every city, rule, queue and tick.
const $=id=>document.getElementById(id),canvas=$('map');let ctx=canvas.getContext('2d');
const staticMapCanvas=document.createElement('canvas'),staticMapContext=staticMapCanvas.getContext('2d');let staticMapKey='',mapRevision=0;
const names=['Empty land','Local road','Avenue','Home','Workplace','Shop','Park','Footpath','Station'],prices=[0,8,24,70,140,110,90,4];
const recoveryStorageKey='flowgarden-city-v4';let tracks=new Set(),railBend=0,serviceStart=null,addStopLine=0,inspectFunds=0;let rails=[],previousRails=new Map(),inspectRailPlan=null;let cityToken='',ownerToken='',sessionStatus=0,actors=[],previousActors=new Map(),inspectResident=null,detail=true,storageError=false;
const randomHex=n=>Array.from(crypto.getRandomValues(new Uint8Array(n)),b=>b.toString(16).padStart(2,'0')).join('');
try{cityToken=localStorage.getItem(recoveryStorageKey)||randomHex(32);if(!/^[a-f0-9]{64}$/.test(cityToken))throw Error('Invalid recovery key');localStorage.setItem(recoveryStorageKey,cityToken)}catch(e){storageError=true}
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),reducedMotion=matchMedia('(prefers-reduced-motion: reduce)');
let ws,connected=false,commandId=0,sequence=0,reconnect,receivedAt=0,lastTick=-1,persistentSession=false,restoredCheckpoint=-1;
let keepaliveTimer=0,renewalTimer=0,renewalAck=0,renewalClose=false;
let cells=new Map(),stats={},serverView={x:0,y:0,w:30,h:20},viewPending=null,viewTimer=0,lastViewSent=0;
let cameraMotionUntil=0;
let width=1,height=1,dpr=1,initialized=false,tool=-2,selected=null,hover=null,draft=null,noticeTimer;
const camera={x:64,y:64,scale:25,angle:0,min:12,max:120,fit:25};
const pointers=new Map();let gesture=null,gestureSerial=0;
const history=[],sentCommands=[],frameTimes=[];
let preferences={grid:false,motion:false};try{preferences={...preferences,...JSON.parse(localStorage.getItem('traffic-city-preferences')||'{}')}}catch{}
let palette='',menuPage='home',menuWasRunning=false,menuHistory=false,firstCityFrame=true,lastFrame=null,review=null,removalBounds=null,removeRequest=0,removeWasRunning=false,reviewCamera=null,mutationPending=null,confirmKind='';
const cityLab=createCityLab({send,cancelGesture,setTool,toast,leaveMenu(){menuWasRunning=false;closeMenu()}});
const motionReduced=()=>reducedMotion.matches||preferences.motion;

function mapArea(){const top=height<500?104:width<=680?180:150;const bottom=Math.max(top+90,Math.min(height-25,document.querySelector('.bottom-ui').getBoundingClientRect().top-18));return{top,bottom,height:Math.max(90,bottom-top)}}
function origin(){const a=mapArea();return{x:width/2,y:(a.top+a.bottom)/2}}
function screenToWorld(p){const o=origin(),c=Math.cos(camera.angle),s=Math.sin(camera.angle),x=(p.x-o.x)/camera.scale,y=(p.y-o.y)/camera.scale;return{x:camera.x+c*x+s*y,y:camera.y-s*x+c*y}}
function worldToScreen(x,y){const o=origin(),c=Math.cos(camera.angle),s=Math.sin(camera.angle),dx=(x-camera.x)*camera.scale,dy=(y-camera.y)*camera.scale;return{x:o.x+c*dx-s*dy,y:o.y+s*dx+c*dy}}
function position(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function inside(p){return p.x>=0&&p.y>=0&&p.x<width&&p.y<height}
function tile(p){const w=screenToWorld(p);return{x:Math.floor(w.x),y:Math.floor(w.y)}}
function straighten(a,b){return Math.abs(b.x-a.x)>Math.abs(b.y-a.y)?{x:b.x,y:a.y}:{x:a.x,y:b.y}}
function visibleRect(){const a=mapArea();const corners=[{x:0,y:a.top},{x:width,y:a.top},{x:0,y:a.bottom},{x:width,y:a.bottom}].map(screenToWorld);const x=clamp(Math.floor(Math.min(...corners.map(p=>p.x)))-1,0,127),y=clamp(Math.floor(Math.min(...corners.map(p=>p.y)))-1,0,127);return{x,y,w:clamp(Math.ceil(Math.max(...corners.map(p=>p.x)))+1-x,1,128-x),h:clamp(Math.ceil(Math.max(...corners.map(p=>p.y)))+1-y,1,128-y)}}
function cameraChanged(){cameraMotionUntil=performance.now()+120;if(camera.scale<=Math.min(width,height)/128){camera.x=64;camera.y=64}camera.x=clamp(camera.x,0,128);camera.y=clamp(camera.y,0,128);$('zoom-label').textContent=(camera.scale/camera.fit).toFixed(1)+'×';scheduleView()}
function anchorZoom(scale,p,anchor=screenToWorld(p)){camera.scale=clamp(scale,camera.min,camera.max);const after=screenToWorld(p);camera.x+=anchor.x-after.x;camera.y+=anchor.y-after.y;cameraChanged()}
function fitCity(){cancelGesture();const ids=[...cells.keys()];const xs=ids.map(id=>id%128),ys=ids.map(id=>Math.floor(id/128));const minX=ids.length?Math.min(...xs):3,maxX=ids.length?Math.max(...xs):24,minY=ids.length?Math.min(...ys):5,maxY=ids.length?Math.max(...ys):15;camera.x=(minX+maxX+1)/2;camera.y=(minY+maxY+1)/2;const w=maxX-minX+2,h=maxY-minY+3;camera.scale=clamp(Math.min((width-50)/(camera.angle?h:w),mapArea().height/(camera.angle?w:h)),camera.min,camera.max);selected=null;$('inspector').hidden=true;cameraChanged()}
function resize(){const r=canvas.getBoundingClientRect();if(!r.width||!r.height)return;const oldFit=camera.fit,ratio=camera.scale/oldFit;cancelGesture();width=r.width;height=r.height;dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);camera.angle=height>width*1.15?-Math.PI/2:0;
 const a=camera.angle?height:width,b=camera.angle?width:height;const min=Math.max(1,Math.min(width,height)/144);camera.min=min;
 const usableW=width-50,usableH=mapArea().height;camera.fit=Math.max(min,Math.min(usableW/(camera.angle?13:24),usableH/(camera.angle?24:13)));camera.max=Math.max(camera.fit*5,96);camera.scale=initialized?clamp(camera.fit*ratio,min,camera.max):camera.fit;initialized=true;cameraChanged();}
new ResizeObserver(resize).observe(canvas);
function send(op,fields={}){if(!connected||ws.readyState!==WebSocket.OPEN){toast('Wait for the city connection before editing.');return 0}const id=++commandId,action={op,x:0,y:0,x2:0,y2:0,kind:0,...fields};ws.send(JSON.stringify({id,action,token:op==='resume'?cityToken:'',owner:op==='resume'?ownerToken:''}));sentCommands.push({id,...action});if(sentCommands.length>200)sentCommands.shift();return id}
function scheduleView(){clearTimeout(viewTimer);viewTimer=setTimeout(syncView,Math.max(0,160-(performance.now()-lastViewSent)))}
function syncView(force=false){if(!connected||viewPending)return;const r=visibleRect();const covered=(r.w*r.h<=1024)===(serverView.w*serverView.h<=1024)&&r.x>=serverView.x&&r.y>=serverView.y&&r.x+r.w<=serverView.x+serverView.w&&r.y+r.h<=serverView.y+serverView.h;
 if(covered&&!force)return;const id=send('view',{x:r.x,y:r.y,x2:r.w,y2:r.h});if(id){viewPending={id,rect:r};lastViewSent=performance.now()}}
// Native sessions are bounded. Keep an observed city connected, and rotate a
// long session only after a native save acknowledgement, before its hard limit.
function scheduleRenewal(delay=25*60*1000){clearTimeout(renewalTimer);renewalTimer=setTimeout(()=>{if(connected&&sessionStatus===1&&!cityLab.active&&!mutationPending&&!gesture&&!document.querySelector('#removal[open],#menu[open]'))renewalAck=send('save');else if(connected)scheduleRenewal(5000)},delay)}
function startConnectionTimers(){clearInterval(keepaliveTimer);keepaliveTimer=setInterval(()=>{if(connected&&sessionStatus===1)syncView(true)},60000);scheduleRenewal()}
function stopConnectionTimers(){clearInterval(keepaliveTimer);clearTimeout(renewalTimer);renewalAck=0}
function connect(){clearTimeout(reconnect);if(storageError){$('connection').textContent='Storage unavailable';toast('Browser storage is unavailable or the city key is invalid. Enable local storage before playing; no city has been replaced.',30000);return}const endpoint=new URL('/live',location.href);endpoint.protocol=location.protocol==='https:'?'wss:':'ws:';const port=new URLSearchParams(location.search).get('session_port');if(port!==null){if(!/^\d{1,5}$/.test(port)||Number(port)<1||Number(port)>65535){toast('Invalid session port.');return}endpoint.port=String(Number(port))}
 ownerToken=randomHex(16);ws=new WebSocket(endpoint);ws.onopen=()=>{connected=true;commandId=0;sequence=0;sessionStatus=0;viewPending=null;cancelGesture();$('connection').textContent='Resuming…';$('connection').classList.remove('offline');send('resume');startConnectionTimers()};
 ws.onmessage=e=>{const f=JSON.parse(e.data);if(f.seq<=sequence)return;sequence=f.seq;commandId=Math.max(commandId,f.ack);persistentSession=true;sessionStatus=f.status;detail=f.detail;if(f.stats.tick!==lastTick){receivedAt=performance.now();lastTick=f.stats.tick;previousRails=new Map(rails.map(l=>[l.id,l]))}previousActors=new Map(actors.map(a=>[a.id,a]));actors=f.actors||[];inspectResident=f.inspect;rails=f.rails||[];inspectFunds=f.inspectFunds||0;inspectRailPlan=f.inspectRail;
 if(f.mapChanged){tracks=new Set(f.tracks||[]);mapRevision++;cells=new Map(f.overview.map(v=>{const id=Math.floor(v/16);return[id,{id,kind:v%16,q:0,walk:0,flow:0,inside:0,junction:0,control:0}]}))}else if(f.reset){for(const c of cells.values()){c.q=0;c.walk=0;c.flow=0;c.inside=0}}
 for(const c of f.cells){if(c.kind)cells.set(c.id,c);else cells.delete(c.id)}if(!detail){for(const c of cells.values())c.q=0;for(const v of f.heat||[]){const c=cells.get(Math.floor(v/32));if(c)c.q=v%32}}
 trafficMotion.receive(f,performance.now(),cells);stats=f.stats;if(firstCityFrame&&f.status===1&&f.mapChanged){firstCityFrame=false;fitCity()}if(f.view)serverView=f.view;if(viewPending&&f.ack>=viewPending.id){serverView=f.view||viewPending.rect;viewPending=null}history.push({tick:stats.tick,backlog:stats.requested-stats.arrived,bytes:e.data.length});if(history.length>300)history.shift();update(f);if(selected!==null)inspect(selected,false);scheduleView();if(renewalAck&&f.ack>=renewalAck){renewalAck=0;if(f.status===1&&f.saved===f.stats.tick){renewalClose=true;ws.close(1000,'saved city connection renewal')}else scheduleRenewal(60000)}};
 ws.onclose=()=>{const delay=renewalClose?250:2500;renewalClose=false;stopConnectionTimers();connected=false;cityLab.offline();abandonPending();viewPending=null;cancelGesture();$('connection').textContent='Offline';$('connection').classList.add('offline');if(sessionStatus!==2){toast('Reconnecting to your saved city…',6000);reconnect=setTimeout(connect,delay)}};ws.onerror=()=>toast('City connection unavailable. Your saved city is retained.',6000);
}
function toast(message,duration=3500){if(!message)return;clearTimeout(noticeTimer);$('notice').textContent=message;$('notice').classList.add('visible');noticeTimer=setTimeout(()=>{$('notice').classList.remove('visible')},duration)}
function update(f){$('cash').textContent='$'+stats.cash.toLocaleString();$('served').textContent=stats.population+' people';$('backlog').textContent=stats.waiting.toLocaleString();$('arrived').textContent=stats.visits.toLocaleString();$('disconnected').textContent=stats.disconnected.toLocaleString();$('cycle').textContent=(stats.paused?'PLANNING':'IN MOTION')+' · '+(detail?'CYCLE '+stats.tick:'CITY OVERVIEW');$('queue-stat').classList.toggle('congested',stats.waiting>stats.population/4);$('play').disabled=sessionStatus!==1;$('play').setAttribute('aria-label',stats.paused?'Start traffic':'Pause traffic');$('play-icon').innerHTML=stats.paused?'<svg viewBox="0 0 20 20"><path d="M6 3l11 7-11 7z"/></svg>':'<svg viewBox="0 0 20 20"><path d="M4 3h4v14H4zM12 3h4v14h-4z"/></svg>';$('play-label').textContent=stats.paused?'Start':'Pause';$('play').classList.toggle('running',!stats.paused&&sessionStatus===1);document.querySelector('.live-dot').classList.toggle('running',!stats.paused&&sessionStatus===1);
 const level=String(stats.level).padStart(2,'0'),target=stats.growthTarget;$('level').textContent=level;$('chapter').textContent=level;$('mission-title').textContent='ROOM TO GROW';$('mission-short').textContent=stats.growth?'Ready to expand.':`${stats.population} / ${target} people · ${stats.progress} / ${target} visits`;$('target-text').textContent=stats.healthy>=24?'✓ steady':'View goal →';$('progress').style.width=Math.min(100,stats.progress/target*100,stats.population/target*100)+'%';$('grow').disabled=!stats.growth;$('grow').hidden=!stats.growth;$('grow').innerHTML=`Expand district <span>$${stats.growthCost} →</span>`;$('goal-title').textContent='Make room for more';$('mission-copy').textContent=`Reach ${target} residents and ${target} completed visits in this district. Keep long waits below a quarter of the population, with nobody disconnected, for 24 cycles.`;$('growth-note').textContent=`Expansion costs $${stats.growthCost}. The next population, visits and funding requirements double.`;$('permits').textContent=stats.permits+' home permits';$('travel-summary').textContent=`${stats.workVisits} work · ${stats.shopVisits} shopping · ${stats.leisureVisits} leisure visits. ${stats.walkTrips} walking / ${stats.carTrips} driving choices · ${stats.railBoardings||0} rail boardings. Rail operation: $${stats.railSpent||0}. Average completed trip: ${stats.average} cycles.`;
 $('save').disabled=sessionStatus!==1;$('save').textContent='Save now';$('saved').textContent=f.saved>=0?`Saved · cycle ${f.saved}`:'Not saved';$('connection').textContent=sessionStatus===1?(f.saved<stats.tick?'● Live · saving…':'● Saved'):sessionStatus===2?'Another tab is active':sessionStatus===0?'Resuming…':'Recovery needed';$('resume').hidden=sessionStatus===1||sessionStatus===0;$('session-note').textContent='Changes save automatically. Reopen in this browser to resume. Clearing browser data loses this city’s recovery key.';
 if(f.notice&&f.status!==0)toast(f.notice,sessionStatus===1?4000:15000);updateInterface(f);cityLab.receive(f);
}
function setTool(n){if(n>=0&&cityLab.active&&cityLab.phase!==1){toast('Choose Edit plan before changing this experiment.');return}cancelGesture();tool=n;hover=null;canvas.dataset.mode=n===-2?'move':'build';if(n===-2||n===0)showPalette('');if(n>=8)showPalette('rail');if(n!==10)serviceStart=null;if(n!==11)addStopLine=0;$('inspector').hidden=true;for(const b of document.querySelectorAll('[data-tool]')){const on=Number(b.dataset.tool)===n;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',String(on))}const touch=matchMedia('(pointer: coarse)').matches;$('hint').textContent=n===-2?(touch?'Drag to explore · pinch to zoom':'Drag to explore · scroll to zoom'):n===0?'Drag a rectangle · release to review':n===8?'Drag track · diagonal drags make a bend':n===9?'Tap an empty track beside a road or path':n===10?'Tap the first station, then the last station':n===11?'Tap a station to add it to this suspended service':n>2&&n!==7?'Tap to place · two fingers move':'Drag to draw · two fingers move'}
$('rail-bend').onclick=()=>{railBend=1-railBend;$('rail-bend').textContent=railBend?'Bend: down, then across ↕':'Bend: across, then down ↔'};
for(const b of document.querySelectorAll('[data-tool]'))b.onclick=()=>setTool(Number(b.dataset.tool));
for(const b of document.querySelectorAll('button[data-palette]'))b.onclick=()=>{const next=palette===b.dataset.palette?'':b.dataset.palette;showPalette(next);if(next)setTool(next==='roads'?1:3);else setTool(-2)};
function showPalette(name){palette=name;document.body.dataset.palette=name;$('palette').hidden=!name;$('roads-palette').hidden=name!=='roads';$('places-palette').hidden=name!=='places';$('rail-palette').hidden=name!=='rail';$('palette-title').textContent=name==='roads'?'ROADS & PATHS · DRAW A LINE':name==='rail'?'RAIL · TRACK, STATIONS & SERVICES':'EVERYDAY PLACES · TAP A TILE';for(const b of document.querySelectorAll('button[data-palette]'))b.setAttribute('aria-expanded',String(b.dataset.palette===name));cameraChanged();}
$('palette-close').onclick=()=>setTool(-2);
$('play').onclick=()=>send('set-running',{kind:stats.paused?1:0});$('grow').onclick=()=>send('grow');$('save').onclick=()=>send('save');$('fit').onclick=fitCity;$('zoom-in').onclick=()=>{cancelGesture();anchorZoom(camera.scale*1.3,origin())};$('zoom-out').onclick=()=>{cancelGesture();anchorZoom(camera.scale/1.3,origin())};$('inspect-close').onclick=()=>{selected=null;$('inspector').hidden=true};
$('goal-open').onclick=()=>{cancelGesture();$('goal').showModal()};$('queue-stat').onclick=()=>{$('goal-open').click()};
$('help-open').onclick=()=>{$('help').showModal()};for(const b of document.querySelectorAll('[data-close]'))b.onclick=()=>$(b.dataset.close).close();
function showMenuPage(name){menuPage=name;for(const page of ['home','preferences','manage','examples','confirm'])$('menu-'+page).hidden=page!==name;}
function openMenu(){if($('menu').open)return;cancelGesture();setTool(-2);menuWasRunning=!stats.paused&&!cityLab.active;showMenuPage('home');$('menu').showModal();$('continue').focus();if(sessionStatus===1)send('set-running',{kind:0});if(!menuHistory){window.history.pushState({trafficCityMenu:true},'');menuHistory=true}}
function clearReview(){if(connected&&sessionStatus===1)send('cancel-review');confirmKind='';review=null;removalBounds=null;removeRequest=0;}
function closeMenu(fromHistory=false){if(!$('menu').open||mutationPending)return;clearReview();$('menu').close();if(menuWasRunning&&sessionStatus===1)send('set-running',{kind:1});menuWasRunning=false;$('menu-open').focus();if(menuHistory){menuHistory=false;if(!fromHistory)window.history.back()}}
$('menu-open').onclick=openMenu;$('menu-close').onclick=()=>closeMenu();$('continue').onclick=()=>closeMenu();
$('examples-open').onclick=()=>{showMenuPage('examples');document.querySelector('[data-scenario]').focus()};for(const b of document.querySelectorAll('[data-scenario]'))b.onclick=()=>reviewScenario(Number(b.dataset.scenario));
$('preferences-open').onclick=()=>{showMenuPage('preferences');$('grid-setting').focus()};$('manage-open').onclick=()=>{showMenuPage('manage');$('new-city').focus()};for(const b of document.querySelectorAll('[data-menu-back]'))b.onclick=()=>{showMenuPage('home');$('continue').focus()};
function cancelCityReview(){const sample=confirmKind.startsWith('scenario-')?Number(confirmKind.slice(9)):0;clearReview();mutationPending=null;showMenuPage(sample?'examples':'manage');(sample?document.querySelector(`[data-scenario="${sample}"]`):$('new-city')).focus()}
$('city-cancel').onclick=cancelCityReview;$('confirm-back').onclick=cancelCityReview;
function reviewCity(kind){if(sessionStatus!==1)return;confirmKind=kind;mutationPending=null;showMenuPage('confirm');$('confirm-title').textContent=kind==='reset'?'Start a new city?':'Restore your previous city?';$('confirm-copy').textContent=kind==='reset'?'Your current city becomes the recoverable backup. A new district begins in the middle of the map. Any older backup is replaced.':'Your previous city will replace this one. This uses the backup once; progress in your current city will be discarded.';$('city-confirm').textContent=kind==='reset'?'Start new city':'Restore city';$('city-cancel').textContent='Keep current city';$('confirm-status').textContent='Preparing your saved city…';$('city-confirm').disabled=true;$('city-cancel').focus();send('review-'+kind)}
function reviewScenario(id){if(sessionStatus!==1)return;confirmKind='scenario-'+id;mutationPending=null;showMenuPage('confirm');$('confirm-title').textContent='Load '+['','Garden City','Crossing Challenge','Willow Metro'][id]+'?';$('confirm-copy').textContent='This creates your own playable copy. Your current city becomes the recoverable backup, replacing any older backup.';$('city-confirm').textContent='Load city';$('city-cancel').textContent='Keep current city';$('confirm-status').textContent='Preparing your saved city…';$('city-confirm').disabled=true;$('city-cancel').focus();send('review-scenario',{kind:id})}
$('new-city').onclick=()=>reviewCity('reset');$('restore-city').onclick=()=>reviewCity('restore');
$('city-confirm').onclick=()=>{if(!lastFrame||!confirmKind||mutationPending)return;const id=send(confirmKind.startsWith('scenario-')?'load-scenario':confirmKind==='reset'?'reset-city':'restore-city',{x:lastFrame.confirmation,kind:confirmKind.startsWith('scenario-')?Number(confirmKind.slice(9)):0});if(id){mutationPending={id,type:confirmKind};$('city-confirm').disabled=true;$('city-cancel').disabled=true;$('confirm-back').disabled=true;$('confirm-status').textContent='Saving city change…'}};
$('menu').addEventListener('cancel',e=>{e.preventDefault();if(mutationPending)return;if(menuPage==='confirm')cancelCityReview();else if(menuPage!=='home'){showMenuPage('home');$('continue').focus()}else closeMenu()});
window.addEventListener('popstate',()=>{if(menuHistory){menuHistory=false;closeMenu(true)}});
$('grid-setting').checked=preferences.grid;$('motion-setting').checked=preferences.motion;for(const [id,key]of [['grid-setting','grid'],['motion-setting','motion']])$(id).onchange=()=>{preferences[key]=$(id).checked;try{localStorage.setItem('traffic-city-preferences',JSON.stringify(preferences))}catch{toast('This preference cannot be saved on this device.')}};
function cancelRemoval(){if(mutationPending)return;if(reviewCamera){Object.assign(camera,reviewCamera);reviewCamera=null;cameraChanged()}clearReview();if($('removal').open)$('removal').close();if(removeWasRunning&&sessionStatus===1)send('set-running',{kind:1});removeWasRunning=false;canvas.focus()}
$('remove-cancel').onclick=cancelRemoval;$('removal').addEventListener('cancel',e=>{e.preventDefault();cancelRemoval()});
$('remove-confirm').onclick=()=>{if(!review?.valid||mutationPending)return;const id=send('apply-remove',{x:review.id});if(id){mutationPending={id,type:'remove'};$('remove-confirm').disabled=true;$('remove-cancel').disabled=true}};
function abandonPending(){if(reviewCamera){Object.assign(camera,reviewCamera);reviewCamera=null;cameraChanged()}removeRequest=0;removalBounds=null;review=null;mutationPending=null;confirmKind='';if($('removal').open)$('removal').close();$('remove-confirm').disabled=false;$('remove-cancel').disabled=false;$('city-cancel').disabled=false;$('confirm-back').disabled=false;if(menuPage==='confirm'){$('city-confirm').disabled=true;$('confirm-status').textContent='Connection interrupted. Reconnect, then review this action again.'}}
function focusRemoval(original){const selectedLines=rails.filter(l=>railIntersects(l,original));const xs=[original.x,original.x2,...selectedLines.flatMap(l=>[l.a%128,l.b%128])],ys=[original.y,original.y2,...selectedLines.flatMap(l=>[Math.floor(l.a/128),Math.floor(l.b/128)])];const q={x:Math.min(...xs),x2:Math.max(...xs),y:Math.min(...ys),y2:Math.max(...ys)};reviewCamera={...camera};const sheet=$('removal').getBoundingClientRect(),area=mapArea();const mobile=width<=680;const target=mobile?{x:width/2,y:(area.top+sheet.top-18)/2}:{x:Math.min(width/2,(sheet.left-20)/2),y:(area.top+area.bottom)/2};const availableW=mobile?width-32:sheet.left-45,availableH=mobile?Math.max(80,sheet.top-area.top-30):area.height;const w=q.x2-q.x+2,h=q.y2-q.y+2;camera.scale=clamp(Math.min(camera.scale,availableW/(camera.angle?h:w),availableH/(camera.angle?w:h)),camera.min,camera.max);const anchor=screenToWorld(target);camera.x+=(q.x+q.x2+1)/2-anchor.x;camera.y+=(q.y+q.y2+1)/2-anchor.y;cameraChanged();}
function updateInterface(f){lastFrame=f;if($('finance').open)updateFinances();$('menu-district').textContent='WILLOW · DISTRICT '+String(stats.level).padStart(2,'0');$('menu-summary').textContent=`${stats.population} residents · ${stats.visits} everyday visits`;const savedText=f.saved>=0?`Saved at cycle ${f.saved}`:'Not saved yet';$('menu-saved').textContent=sessionStatus===1?savedText:sessionStatus===2?'Another tab is active. Resume here to continue.':'Connecting to your city…';$('restore-city').disabled=sessionStatus!==1||!f.undo;$('restore-caption').textContent=f.undo?'Return to your previous city →':'No previous city yet';$('new-city').disabled=sessionStatus!==1;$('cancelled-summary').textContent=`${stats.cancelled||0} journeys were cancelled by confirmed demolition. These are counted separately from completed visits.`;
 if(menuPage==='confirm'&&!mutationPending){const expected=confirmKind.startsWith('scenario-')?10+Number(confirmKind.slice(9)):confirmKind==='reset'?1:2;$('city-confirm').disabled=sessionStatus!==1||f.management!==expected||!f.confirmation;$('confirm-status').textContent=$('city-confirm').disabled?'This review is unavailable. Go back and try again.':'Your current city is saved. Nothing changes until you confirm.'}
 if(removeRequest&&f.ack>=removeRequest){const requested=removeRequest;removeRequest=0;if(f.quote?.valid&&f.quote.id===requested&&sessionStatus===1){review=f.quote;const q=review;removalBounds={start:{x:q.x,y:q.y},end:{x:q.x2,y:q.y2},kind:0};$('removal-size').textContent=`${q.x2-q.x+1} × ${q.y2-q.y+1} selection · ${q.tiles} built ${q.tiles===1?'tile':'tiles'}`;$('removal-details').innerHTML=`<dt>Salvage refund</dt><dd>+$${q.refund}</dd>${q.rails?`<dt>Services cancelled</dt><dd>${q.rails}</dd>`:''}<dt>Residents moving out</dt><dd>${q.moveouts}</dd><dt>Residents returning home</dt><dd>${q.relocated}</dd><dt>Journeys cancelled</dt><dd>${q.cancelled}</dd><dt>Home permits returned</dt><dd>${q.homes}</dd>`;$('remove-confirm').disabled=false;$('remove-cancel').disabled=false;$('removal').showModal();focusRemoval(q);$('remove-cancel').focus()}else{removalBounds=null;removeWasRunning=false}}
 if(mutationPending&&f.ack>=mutationPending.id){const pending=mutationPending;mutationPending=null;$('city-cancel').disabled=false;$('confirm-back').disabled=false;$('remove-confirm').disabled=false;$('remove-cancel').disabled=false;if(pending.type==='remove'){reviewCamera=null;review=null;removalBounds=null;if($('removal').open)$('removal').close();removeWasRunning=false;canvas.focus()}else{confirmKind='';menuWasRunning=false;showMenuPage('home');if(sessionStatus===1){fitCity();$('continue').focus()}}}
}
// A second pointer irrevocably cancels this stroke. Building requires a fresh gesture.
function cancelGesture(){gesture=null;draft=null;hover=null;const ids=[...pointers.keys()];pointers.clear();canvas.dataset.gesture='';for(const id of ids){try{if(canvas.hasPointerCapture(id))canvas.releasePointerCapture(id)}catch{}}}
function beginPinch(){const [a,b]=[...pointers.values()],mid={x:(a.x+b.x)/2,y:(a.y+b.y)/2};draft=null;hover=null;gesture={kind:'pinch',anchor:screenToWorld(mid),distance:Math.max(1,Math.hypot(a.x-b.x,a.y-b.y)),scale:camera.scale,blocked:true};canvas.dataset.gesture='pinch'}
canvas.addEventListener('pointerdown',e=>{if(e.pointerType==='mouse'&&![0,1,2].includes(e.button))return;e.preventDefault();canvas.focus({preventScroll:true});const p=position(e);pointers.set(e.pointerId,{...p,type:e.pointerType});canvas.setPointerCapture(e.pointerId);if(pointers.size>=2){beginPinch();return}const pan=tool===-2||e.button===1||e.button===2||e.shiftKey;gesture={kind:pan?'pan':'build',id:e.pointerId,start:p,camera:{x:camera.x,y:camera.y},moved:false,blocked:false,serial:++gestureSerial};canvas.dataset.gesture=gesture.kind;if(!pan){draft={start:tile(p),end:tile(p),kind:tool,cancelled:false};hover=draft.end}});
canvas.addEventListener('pointermove',e=>{const p=position(e);if(!pointers.has(e.pointerId)){if(e.pointerType==='mouse'&&inside(p)&&tool!==-2)hover=tile(p);return}e.preventDefault();pointers.set(e.pointerId,{...p,type:e.pointerType});if(!gesture)return;
 if(pointers.size>=2){if(gesture.kind!=='pinch')beginPinch();const[a,b]=[...pointers.values()],mid={x:(a.x+b.x)/2,y:(a.y+b.y)/2};anchorZoom(gesture.scale*Math.hypot(a.x-b.x,a.y-b.y)/gesture.distance,mid,gesture.anchor);return}
 if(gesture.id!==e.pointerId)return;const dx=p.x-gesture.start.x,dy=p.y-gesture.start.y;if(Math.hypot(dx,dy)>5)gesture.moved=true;
 if(gesture.kind==='pan'){const c=Math.cos(camera.angle),s=Math.sin(camera.angle);camera.x=gesture.camera.x-(c*dx+s*dy)/camera.scale;camera.y=gesture.camera.y-(-s*dx+c*dy)/camera.scale;cameraChanged()}
 else if(gesture.kind==='build'&&draft){if(!inside(p)){draft.cancelled=true;hover=null}else if(!draft.cancelled){draft.end=tool===0?tile(p):tool===8?tile(p):(tool===1||tool===2||tool===7)?straighten(draft.start,tile(p)):draft.start;hover=draft.end}}});
function endPointer(e,cancelled=false){if(!pointers.has(e.pointerId))return;const p=position(e),old=gesture;if(cancelled){cancelGesture();return}pointers.delete(e.pointerId);try{if(canvas.hasPointerCapture(e.pointerId))canvas.releasePointerCapture(e.pointerId)}catch{}
 if(pointers.size>=2){beginPinch();return}if(pointers.size===1){const[id,a]=[...pointers.entries()][0];draft=null;gesture={kind:'pan',id,start:{x:a.x,y:a.y},camera:{x:camera.x,y:camera.y},moved:true,blocked:true};canvas.dataset.gesture='pan';return}
 if(old?.kind==='build'&&draft&&!draft.cancelled&&!old.blocked&&inside(p)){const start=draft.start,end=tool===0?tile(p):tool===8?tile(p):(tool===1||tool===2||tool===7)?straighten(start,tile(p)):start;if(tool===0){removeWasRunning=!stats.paused;removalBounds={start,end,kind:0};removeRequest=send('review-remove',{x:start.x,y:start.y,x2:end.x,y2:end.y,kind:0})}else if(tool===8)send('build-track',{x:start.x,y:start.y,x2:end.x,y2:end.y,kind:railBend});else if(tool===9)send('build-station',{x:start.x,y:start.y});else if(tool===10){if(cells.get(start.x+start.y*128)?.kind!==8)toast('Choose a station on your track.');else if(!serviceStart){serviceStart=start;$('hint').textContent=`Start: ${start.x}, ${start.y} · tap the last station · Esc cancels`;toast('Now tap the last station.')}else{const first={...serviceStart};send('create-service',{x:first.x,y:first.y,x2:start.x,y2:start.y});setTool(-2);inspect(first.x+first.y*128,true)}}else if(tool===11){send('rail-stop',{x:addStopLine,y:start.x+start.y*128});setTool(-2)}else send('build',{x:start.x,y:start.y,x2:end.x,y2:end.y,kind:draft.kind})}else if(old?.kind==='pan'&&!old.moved&&!old.blocked&&inside(p)){const at=tile(p);inspect(at.x+at.y*128,true)}
 gesture=null;draft=null;hover=null;canvas.dataset.gesture='';scheduleView();}
canvas.addEventListener('pointerup',e=>endPointer(e));canvas.addEventListener('pointercancel',e=>endPointer(e,true));canvas.addEventListener('lostpointercapture',e=>{if(pointers.has(e.pointerId))cancelGesture()});canvas.addEventListener('pointerleave',()=>{hover=null;if(draft)draft.cancelled=true});canvas.addEventListener('contextmenu',e=>e.preventDefault());
canvas.addEventListener('wheel',e=>{e.preventDefault();cancelGesture();const delta=e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?height:1);anchorZoom(camera.scale*Math.exp(-clamp(delta,-250,250)*.0025),position(e))},{passive:false});
window.addEventListener('blur',cancelGesture);document.addEventListener('visibilitychange',()=>{if(document.hidden)cancelGesture()});window.addEventListener('pagehide',cancelGesture);
window.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]'))return;if(e.key==='Escape'){cancelGesture();selected=null;$('inspector').hidden=true;setTool(-2);return}if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;if(e.code==='Space'&&e.target.tagName!=='BUTTON'){e.preventDefault();cancelGesture();send('set-running',{kind:stats.paused?1:0})}else if(e.key==='+'||e.key==='='){$('zoom-in').click()}else if(e.key==='-'){$('zoom-out').click()}else if(e.key.toLowerCase()==='f'){fitCity()}else if(e.key.startsWith('Arrow')){const v={ArrowLeft:[-75,0],ArrowRight:[75,0],ArrowUp:[0,-75],ArrowDown:[0,75]}[e.key];if(!v)return;e.preventDefault();cancelGesture();const c=Math.cos(camera.angle),s=Math.sin(camera.angle);camera.x+=(c*v[0]+s*v[1])/camera.scale;camera.y+=(-s*v[0]+c*v[1])/camera.scale;cameraChanged()}});
function inspect(id,open){selected=id;const c=cells.get(id),rail=railAt(id),x=id%128,y=Math.floor(id/128);if(open){$('inspector').hidden=false;send('inspect',{x,y})}$('inspect-title').textContent=(c?names[c.kind]:'Open land')+` · ${x}, ${y}`;if(rail&&(!c||c.kind===8)){$('inspect-title').textContent=`Shuttle ${rail.id}${c?.kind===8?' · station '+((rail.stops||[rail.a,rail.b]).indexOf(id)+1):''}`;$('inspect-body').textContent='Walk to the station, wait for a seat, ride, then walk to the destination. Work pays wages; purchases and fares move money through the city.';$('inspect-details').innerHTML=railDetails(rail);return}if(c?.kind===8&&!rail){$('inspect-body').textContent='A station ready for service. Use Rail → Service to connect it to another station.';$('inspect-details').innerHTML='';return}if(!c){$('inspect-body').textContent='Homes add eight people; workplaces offer sixteen jobs. Put useful destinations near homes and connect them.';$('inspect-details').innerHTML='';return}let reason=c.kind===7?'A walking-only shortcut. Cars must use roads.':c.kind===3?'Eight permanent residents live here. Their jobs and destinations determine where they travel.':c.kind===4?'Sixteen jobs. Residents keep their work assignment until you change the city.':c.kind===5?'Residents spend their savings here; part of each purchase becomes city tax. Nearby shops can replace long car trips with short walks.':c.kind===6?'A local place to relax, then return home.':c.junction?'Vehicles yield, obey signals and reserve space beyond this junction.':'Each approach lane stores three cars. Full receiving lanes push queues upstream.';$('inspect-body').textContent=reason;
 const controls=['All-way stop','Timed signal','Priority E–W','Priority N–S'];let html=`<dl><dt>Cars / people walking</dt><dd>${c.q} / ${c.walk||0}</dd><dt>At destination</dt><dd>${c.inside||0}</dd></dl>`;if(c.junction)html+=`<p class="small">${controls[c.control||0]} · ${stats.phase===-1?'all red':stats.phase===0?'E–W green':'N–S green'}</p><div class="junction-controls">${controls.map((n,i)=>`<button data-signal="${i}" ${c.control===i?'disabled':''}>${n}</button>`).join('')}</div><p class="small">Change control · $40</p>`;
 const r=inspectResident;if(r&&r.id>0&&(r.home===id||r.cell===id||r.dest===id)){const reasons=['Travelling','No connected route','Waiting behind another car','No space ahead','Yielding or red signal','Conflicting movement','Picking up car','Parking','Planning a shared route','Missing destination','Waiting for a train','Riding the shuttle'];const purposes=['At home','Work','Shopping','Leisure','Returning home'];html+=`<div class="resident-card"><b>Resident ${r.id} · ${purposes[r.purpose]||'At home'}</b><p>${r.state===0?'Resting at home':r.state===3?'At their destination':reasons[r.reason]||'Travelling'} · ${r.mode===2?'driving':r.mode===1?'walking':r.mode===3?(r.state===6?'on rail':'walking + rail'):'choosing transport'}</p><dl><dt>Walk / drive estimate</dt><dd>${r.etaWalk<0?'—':r.etaWalk} / ${r.etaCar<0?'—':r.etaCar}</dd>${inspectRailPlan?.line?`<dt>Rail journey estimate</dt><dd>${inspectRailPlan.eta} cycles</dd>`:''}<dt>Household savings</dt><dd>$${inspectFunds}</dd><dt>Last journey</dt><dd>${r.lastTime} cycles</dd><dt>Waiting</dt><dd>${r.wait} cycles</dd></dl></div>`}if(rail)html+=`<div class="rail-card">${railDetails(rail)}</div>`;$('inspect-details').innerHTML=html;
}
// Presentation of the native orthogonal track stroke; never mutates game state.
function trackPreviewPath(a,b,bend=railBend){const corner=bend?{x:a.x,y:b.y}:{x:b.x,y:a.y},out=[{...a}];let p={...a};for(const end of[corner,b]){while((p.x!==end.x||p.y!==end.y)&&out.length<128){p={x:p.x+Math.sign(end.x-p.x),y:p.y+Math.sign(end.y-p.y)};out.push(p)}}return out}
function railPath(l){if(l.path?.length)return l.path;const out=[],dx=Math.sign(l.b%128-l.a%128),dy=Math.sign(Math.floor(l.b/128)-Math.floor(l.a/128));let p=l.a;for(let i=0;i<129;i++){out.push(p);if(p===l.b)break;p+=dx+dy*128}return out}
function railIntersects(l,q){return railPath(l).some(id=>id%128>=q.x&&id%128<=q.x2&&Math.floor(id/128)>=q.y&&Math.floor(id/128)<=q.y2)}
function railAt(id){return rails.find(l=>railPath(l).includes(id))}
function railDetails(l){const status=l.status===1?'In motion':!l.enabled?'Suspended':l.status===2?'Waiting for funds':l.status===4?'Waiting for clear track':'At station';return `<dl><dt>Service ${l.id}</dt><dd>${status}</dd><dt>On this train</dt><dd>${l.occupancy} / ${l.capacity}</dd><dt>Stations / boardings</dt><dd>${(l.stops||[l.a,l.b]).length} / ${l.boardings}</dd>${(l.platforms||[]).map((p,i)=>`<dt>Station ${i+1} · ${p.station%128}, ${Math.floor(p.station/128)}</dt><dd>${p.forward+p.reverse} waiting</dd>`).join('')}<dt>Next leg cost</dt><dd>$${l.expense}</dd><dt>Operating costs so far</dt><dd>$${l.spent}</dd></dl><button class="rail-service" data-rail-service="${l.id}">${l.enabled?'Suspend service':'Resume service'}</button><button class="rail-service" data-rail-stop="${l.id}" ${l.enabled||l.occupancy||l.status===1?'disabled':''}>Add a station to service</button><p class="small">Pause traffic and suspend an empty service before adding stops. Add an existing station on this route, or extend track beyond its last stop. Paid legs finish; shared sections wait until clear.</p>`}
const railGeometryCache=new Map();
function railGeometry(l){const path=railPath(l),key=path.join(',');if(railGeometryCache.has(key))return railGeometryCache.get(key);const points=path.map(id=>({x:id%128+.5,y:Math.floor(id/128)+.5})),out=[];const push=(p,index)=>out.push({...p,index});if(points.length)push(points[0],0);for(let i=1;i<points.length-1;i++){const a=points[i-1],p=points[i],b=points[i+1],ux=p.x-a.x,uy=p.y-a.y,vx=b.x-p.x,vy=b.y-p.y;if(ux===vx&&uy===vy){push(p,i);continue}const radius=.34,start={x:p.x-ux*radius,y:p.y-uy*radius},end={x:p.x+vx*radius,y:p.y+vy*radius};push(start,i-radius);for(let k=1;k<=12;k++){const t=k/12,u=1-t;push({x:u*u*start.x+2*u*t*p.x+t*t*end.x,y:u*u*start.y+2*u*t*p.y+t*t*end.y},i-radius+2*radius*t)}}if(points.length>1)push(points.at(-1),points.length-1);if(railGeometryCache.size>32)railGeometryCache.clear();railGeometryCache.set(key,out);return out}
function railProgress(l){const path=railPath(l),a=Math.max(0,path.indexOf(l.from)),b=Math.max(0,path.indexOf(l.to));return a+(b-a)*(l.duration?clamp(l.elapsed/l.duration,0,1):1)}
function railPose(l,index){const points=railGeometry(l);if(points.length<2)return{x:l.a%128+.5,y:Math.floor(l.a/128)+.5,angle:0};let i=1;while(i<points.length-1&&points[i].index<index)i++;const a=points[i-1],b=points[i],t=clamp((index-a.index)/(b.index-a.index||1),0,1);return{x:a.x+(b.x-a.x)*t,y:a.y+(b.y-a.y)*t,angle:Math.atan2(b.y-a.y,b.x-a.x)+(l.direction<0?Math.PI:0)}}
function drawRails(now){const mix=stats.paused||motionReduced()?1:clamp((now-receivedAt)/500,0,1);let bounds=review;if(!bounds&&tool===0&&draft&&!draft.cancelled)bounds={x:Math.min(draft.start.x,draft.end.x),y:Math.min(draft.start.y,draft.end.y),x2:Math.max(draft.start.x,draft.end.x),y2:Math.max(draft.start.y,draft.end.y)};
 const colors=['#6f7194','#b18b53','#528b8a','#a7736c'];ctx.lineCap='round';ctx.lineJoin='round';const assigned=new Set(rails.flatMap(railPath));ctx.strokeStyle='#96978e';ctx.lineWidth=.12;ctx.beginPath();for(const id of tracks){if(assigned.has(id))continue;const x=id%128+.5,y=Math.floor(id/128)+.5;ctx.moveTo(x-.04,y);ctx.lineTo(x+.04,y);for(const d of[1,128])if(tracks.has(id+d)&&Math.abs((id+d)%128-id%128)<=1){ctx.moveTo(x,y);ctx.lineTo((id+d)%128+.5,Math.floor((id+d)/128)+.5)}}ctx.stroke();
 for(const l of rails){const points=railGeometry(l),color=colors[(l.id-1)%4],highlight=bounds&&railIntersects(l,bounds);for(const [width,color2]of[[.33,'#33443624'],[highlight?.37:.25,highlight?'#c26543':'#e7e4d7'],[.10,color]]){ctx.strokeStyle=color2;ctx.lineWidth=width;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke()}}
 const stationIds=new Set([...cells.values()].filter(c=>c.kind===8).map(c=>c.id));for(const id of stationIds){const l=rails.find(l=>(l.stops||[l.a,l.b]).includes(id)),color=l?colors[(l.id-1)%4]:'#8b9587',x=id%128+.5,y=Math.floor(id/128)+.5,waiting=rails.reduce((sum,r)=>sum+(r.platforms||[]).filter(p=>p.station===id).reduce((n,p)=>n+p.forward+p.reverse,0),0),label=l?String((l.stops||[l.a,l.b]).indexOf(id)+1):'S';pathRound(x-.44,y-.42,.88,.84,.13,'#eeeada');pathRound(x-.34,y-.25,.68,.5,.07,color);pathRound(x-.24,y-.15,.48,.30,.03,'#f1f1dc');if(camera.scale>=18){ctx.save();ctx.translate(x,y);ctx.rotate(-camera.angle);ctx.fillStyle=color;ctx.font='700 .21px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(label,0,0);if(waiting){pathRound(.15,-.53,.50,.28,.1,'#bd724e');ctx.fillStyle='#fff7e5';ctx.font='700 .19px system-ui';ctx.fillText(String(waiting),.40,-.39)}ctx.restore()}}
 for(const l of rails){const old=previousRails.get(l.id),same=old&&railPath(old).join(',')===railPath(l).join(','),progress=railProgress(l),before=same?railProgress(old):progress,pos=railPose(l,before+(progress-before)*mix),color=colors[(l.id-1)%4];ctx.save();ctx.translate(pos.x,pos.y);ctx.rotate(pos.angle);pathRound(-.43,-.18,.88,.38,.10,'#30483930');pathRound(-.46,-.22,.88,.36,.10,l.enabled||l.status===1?'#faf0d3':'#c8cebf');ctx.strokeStyle=color;ctx.lineWidth=.035;ctx.beginPath();ctx.roundRect(-.46,-.22,.88,.36,.10);ctx.stroke();for(const offset of[-.30,-.05,.20])pathRound(offset,-.13,.16,.16,.025,color);ctx.restore()}
}

function pathRound(x,y,w,h,r,fill){ctx.fillStyle=fill;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
function neighbors(c){return[c.id+1,c.id+128].map(id=>cells.get(id)).filter(n=>n&&Math.abs(n.id%128-c.id%128)<=1)}
function roadWidth(c){return c.kind===2?.74:.48}
function drawRoads(visible){ctx.lineCap='round';ctx.lineJoin='round';for(const pass of [0,1])for(const kind of [1,2]){ctx.strokeStyle=pass?'#5e766e':'#d6ddce';ctx.lineWidth=(kind===2?.74:.48)+(pass?0:.15);ctx.beginPath();for(const c of visible){if(c.kind!==kind)continue;const x=c.id%128+.5,y=Math.floor(c.id/128)+.5;ctx.moveTo(x-.01,y);ctx.lineTo(x+.01,y);for(const id of [c.id-1,c.id+1,c.id-128,c.id+128]){const n=cells.get(id);if(n&&Math.abs(n.id%128-c.id%128)<=1){ctx.moveTo(x,y);ctx.lineTo((x+id%128+.5)/2,(y+Math.floor(id/128)+.5)/2)}}}ctx.stroke()}
 ctx.strokeStyle='#b9c9b96e';ctx.lineWidth=.035;ctx.setLineDash([.16,.16]);ctx.beginPath();for(const c of visible)if(c.kind===2){const x=c.id%128+.5,y=Math.floor(c.id/128)+.5;for(const n of neighbors(c)){ctx.moveTo(x,y);ctx.lineTo(n.id%128+.5,Math.floor(n.id/128)+.5)}}ctx.stroke();ctx.setLineDash([]);
 }
function drawRoadQueues(visible){for(const c of visible){if(c.kind>2)continue;const x=c.id%128+.5,y=Math.floor(c.id/128)+.5,storage=c.kind===1?6:12;if(c.q>=storage*.6){ctx.strokeStyle=c.q>=storage?'#cf6b44':'#d5a85b';ctx.lineWidth=roadWidth(c)*.6;ctx.beginPath();ctx.moveTo(x-.34,y);ctx.lineTo(x+.34,y);ctx.stroke()}}
}
function drawBuilding(c){const x=c.id%128+.5,y=Math.floor(c.id/128)+.5;for(const id of [c.id-1,c.id+1,c.id-128,c.id+128])if(cells.has(id)&&Math.abs(id%128-c.id%128)<=1){ctx.strokeStyle='#a9b9a6';ctx.lineWidth=.15;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo((x+id%128+.5)/2,(y+Math.floor(id/128)+.5)/2);ctx.stroke()}
 if(c.kind===6){pathRound(x-.47,y-.47,.94,.94,.20,'#c0d3ad');for(const [dx,dy,r] of [[-.2,-.15,.19],[.19,.17,.22],[.17,-.2,.14]]){ctx.fillStyle='#6d9367';ctx.beginPath();ctx.arc(x+dx,y+dy,r,0,Math.PI*2);ctx.fill()}pathRound(x-.29,y+.23,.23,.07,.015,'#b68c61');return}if(c.kind===5){pathRound(x-.46,y-.46,.92,.92,.16,'#eee0c1');pathRound(x-.34,y-.28,.68,.55,.04,'#e2bc70');pathRound(x-.37,y+.10,.74,.18,.02,'#bc765b');for(let i=0;i<4;i++)pathRound(x-.35+i*.18,y+.10,.08,.18,.01,'#f5e4ba');return}
 pathRound(x-.49,y-.49,.98,.98,.18,c.kind===3?'#e3dfcf':'#dbe6de');pathRound(x-.29+.065,y-.31+.09,.62,.64,.08,'#274b3c18');if(c.kind===3){pathRound(x-.3,y-.31,.6,.62,.055,'#d6a18a');ctx.fillStyle='#bc7c65';ctx.beginPath();ctx.moveTo(x-.31,y-.32);ctx.lineTo(x+.31,y-.32);ctx.lineTo(x+.12,y+.32);ctx.lineTo(x-.31,y+.32);ctx.fill();ctx.strokeStyle='#f0c5aa';ctx.lineWidth=.035;ctx.beginPath();ctx.moveTo(x,y-.28);ctx.lineTo(x,y+.28);ctx.stroke();pathRound(x+.17,y-.12,.09,.17,.02,'#f1d8c2');pathRound(x-.18,y-.16,.08,.1,.01,'#f8ecd8')}else{pathRound(x-.36,y-.35,.72,.7,.045,'#63888e');pathRound(x-.3,y-.29,.6,.16,.02,'#aac2bb');for(let i=0;i<3;i++)pathRound(x-.27+i*.2,y-.01,.12,.25,.018,'#d6e1cb');pathRound(x-.39,y+.28,.78,.075,.01,'#416b73')}
}
function actorPosition(a){return actorPose(a,cells)}
function drawResidents(now){for(const a of trafficMotion.sample(now,motionReduced())){ctx.save();ctx.translate(a.x,a.y);ctx.rotate(a.angle);if(a.mode!==2){ctx.fillStyle=['#466957','#be7e58','#826f99'][a.id%3];ctx.beginPath();ctx.arc(0,0,.05,0,Math.PI*2);ctx.fill()}else{pathRound(-.08,-.0325,.16,.065,.019,['#f8e8bb','#cf7d61','#89b2af','#e7b961'][a.id%4]);pathRound(-.014,-.026,.043,.052,.010,'#405a58');ctx.fillStyle='#fff4cf';ctx.fillRect(.057,-.027,.018,.011);ctx.fillRect(.057,.016,.018,.011)}ctx.restore()}}
function drawFootpaths(visible){ctx.strokeStyle='#baa886';ctx.lineWidth=.16;ctx.setLineDash([.12,.06]);for(const c of visible){if(c.kind!==7)continue;const x=c.id%128+.5,y=Math.floor(c.id/128)+.5;ctx.beginPath();ctx.moveTo(x-.05,y);ctx.lineTo(x+.05,y);for(const id of [c.id-1,c.id+1,c.id-128,c.id+128])if(cells.has(id)&&Math.abs(id%128-c.id%128)<=1){ctx.moveTo(x,y);ctx.lineTo((x+id%128+.5)/2,(y+Math.floor(id/128)+.5)/2)}ctx.stroke()}ctx.setLineDash([])}
// Rendering bounds include the whole canvas, including beneath translucent HUD.
// Query existing tiles by visible grid position instead of drawing the whole city.
function renderCells(){const corners=[{x:0,y:0},{x:width,y:0},{x:0,y:height},{x:width,y:height}].map(screenToWorld),x0=clamp(Math.floor(Math.min(...corners.map(p=>p.x)))-1,0,127),x1=clamp(Math.ceil(Math.max(...corners.map(p=>p.x)))+1,0,127),y0=clamp(Math.floor(Math.min(...corners.map(p=>p.y)))-1,0,127),y1=clamp(Math.ceil(Math.max(...corners.map(p=>p.y)))+1,0,127),visible=[];for(let y=y0;y<=y1;y++)for(let x=x0;x<=x1;x++){const cell=cells.get(x+y*128);if(cell)visible.push(cell)}return visible}
function drawOverview(visible){const colors=['','#5e766e','#5e766e','#c9967e','#63888e','#dab36b','#88a779','#baa886','#6f7194'];for(let kind=1;kind<=8;kind++){ctx.fillStyle=colors[kind];ctx.beginPath();for(const c of visible){if(c.kind!==kind)continue;const x=c.id%128,y=Math.floor(c.id/128),inset=kind===1?.26:kind===2?.13:kind===7?.42:.13;ctx.rect(x+inset,y+inset,1-inset*2,1-inset*2);if(kind<=2||kind===7){for(const [dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){const next=cells.get(c.id+dx+dy*128);if(!next||x+dx<0||x+dx>127)continue;if(dx)ctx.rect(x+(dx>0?.5:0),y+inset,.5,1-2*inset);else ctx.rect(x+inset,y+(dy>0?.5:0),1-2*inset,.5)}}}ctx.fill()}for(const c of visible){if(c.kind>2||c.q<(c.kind===1?4:8))continue;ctx.fillStyle=c.q>=(c.kind===1?6:12)?'#cf6b44':'#d5a85b';ctx.fillRect(c.id%128+.12,Math.floor(c.id/128)+.37,.76,.26)}}
// Cache only stationary road/building paint. Queues, people, trains, water and
// selection overlays still use the current native frame on every browser draw.
function drawStaticMap(visible){const o=origin(),key=[width,height,dpr,camera.x,camera.y,camera.scale,camera.angle,o.x,o.y,stats.version,mapRevision].join(':');if(key!==staticMapKey){staticMapCanvas.width=canvas.width;staticMapCanvas.height=canvas.height;const main=ctx;try{staticMapContext.setTransform(main.getTransform());ctx=staticMapContext;drawRoads(visible);drawFootpaths(visible);for(const c of visible)if(c.kind>=3&&c.kind<=6)drawBuilding(c);staticMapKey=key}finally{ctx=main}}ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.drawImage(staticMapCanvas,0,0);ctx.restore()}
function drawTerrain(now){const ox=stats.originX||0,oy=stats.originY||0,riverX=ox+14;ctx.fillStyle='#edf0e8';ctx.fillRect(0,0,width,height);const o=origin();ctx.save();ctx.translate(o.x,o.y);ctx.rotate(camera.angle);ctx.scale(camera.scale,camera.scale);ctx.translate(-camera.x,-camera.y);ctx.fillStyle='#e6e9dc';ctx.fillRect(0,0,128,128);
 // A quiet continuous ground keeps roads readable at every zoom level.
 const r=visibleRect();
 ctx.fillStyle='#b4d3cf';ctx.fillRect(riverX,0,2,128);ctx.fillStyle='#d0e3d9';ctx.fillRect(riverX-.13,0,.13,128);ctx.fillRect(riverX+2,0,.13,128);ctx.strokeStyle='#d7e8df8c';ctx.lineWidth=.026;for(let y=Math.floor((r.y-2)/1.4)*1.4;y<r.y+r.h+2;y+=1.4){const f=motionReduced()?0:(now*.000035)%1.4;ctx.beginPath();ctx.moveTo(riverX+.4,y+f);ctx.lineTo(riverX+.9,y+f);ctx.moveTo(riverX+1.4,y+.55+f);ctx.lineTo(riverX+1.7,y+.55+f);ctx.stroke()}
 for(const row of [oy+5,oy+10]){ctx.fillStyle='#e1e4cd';ctx.fillRect(riverX-.25,row+.14,2.5,.72);ctx.strokeStyle='#a8bdaaaa';ctx.lineWidth=.035;ctx.setLineDash([.14,.15]);ctx.strokeRect(riverX-.25,row+.14,2.5,.72);ctx.setLineDash([])}
 if((tool!==-2||preferences.grid)&&camera.scale>=15){ctx.strokeStyle='#778a7127';ctx.lineWidth=.018;ctx.beginPath();for(let x=r.x;x<=r.x+r.w;x++){ctx.moveTo(x,r.y);ctx.lineTo(x,r.y+r.h)}for(let y=r.y;y<=r.y+r.h;y++){ctx.moveTo(r.x,y);ctx.lineTo(r.x+r.w,y)}ctx.stroke()}
 const visible=renderCells();if(detail&&(visible.length<=512||performance.now()>=cameraMotionUntil)){drawStaticMap(visible);drawRoadQueues(visible)}else drawOverview(visible);
 drawResidents(now);drawRails(now);
 if(selected!==null){const x=selected%128,y=Math.floor(selected/128);ctx.strokeStyle='#2e816b';ctx.lineWidth=.06;ctx.beginPath();ctx.roundRect(x-.04,y-.04,1.08,1.08,.13);ctx.stroke()}
 const preview=removalBounds||(draft&&!draft.cancelled?draft:(hover&&tool!==-2?{start:hover,end:hover,kind:tool}:null));if(preview){const a=preview.start,b=preview.kind===0?preview.end:preview.kind===8?preview.end:(preview.kind===1||preview.kind===2||preview.kind===7)?straighten(a,preview.end):a,x=Math.min(a.x,b.x),y=Math.min(a.y,b.y),w=Math.abs(a.x-b.x)+1,h=Math.abs(a.y-b.y)+1;ctx.fillStyle=preview.kind===0?'#d77c534c':'#2d967851';ctx.strokeStyle=preview.kind===0?'#c26543':'#297d62';ctx.lineWidth=.065;if(preview.kind===8){const path=trackPreviewPath(a,b);for(const p of path)ctx.fillRect(p.x+.06,p.y+.06,.88,.88);ctx.lineWidth=.14;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();path.forEach((p,i)=>i?ctx.lineTo(p.x+.5,p.y+.5):ctx.moveTo(p.x+.5,p.y+.5));ctx.stroke()}else{ctx.fillRect(x,y,w,h);ctx.strokeRect(x+.025,y+.025,w-.05,h-.05)}}if(serviceStart&&tool===10){ctx.strokeStyle='#297d62';ctx.lineWidth=.09;ctx.beginPath();ctx.roundRect(serviceStart.x-.1,serviceStart.y-.1,1.2,1.2,.22);ctx.stroke()}ctx.restore();return preview;
}
function drawLabel(text,p,color='#607c70',size=10){ctx.fillStyle=color;ctx.font=`600 ${size}px ui-sans-serif,system-ui,sans-serif`;ctx.textAlign='center';ctx.fillText(text,p.x,p.y)}
function draw(now){const start=performance.now();ctx.setTransform(dpr,0,0,dpr,0,0);const preview=drawTerrain(now);const river=worldToScreen((stats.originX||0)+15,(stats.originY||0)+16.4);if(river.x>85&&river.x<width-85&&river.y>170&&river.y<height-250){ctx.save();ctx.translate(river.x,river.y);ctx.rotate(camera.angle+Math.PI/2);drawLabel('W I L L O W   R I V E R',{x:0,y:0},'#689b96',Math.max(8,Math.min(11,camera.scale*.3)));ctx.restore();}
 const congested=[...cells.values()].filter(c=>c.q>(c.kind===1?5:c.kind===2?20:8)).sort((a,b)=>b.q-a.q);const badges=[];for(const c of congested){if(badges.length===3)break;const p=worldToScreen(c.id%128+.5,Math.floor(c.id/128)+.5);if(p.x<8||p.x>width-8||p.y<70||p.y>height-100||badges.some(b=>Math.hypot(p.x-b.x,p.y-b.y)<Math.max(55,camera.scale*1.4)))continue;badges.push(p);const label=c.q>999?'999+':String(c.q),w=label.length*6+15;pathRound(p.x-w/2,p.y-camera.scale*.7-16,w,19,9,'#ce6b48');drawLabel(label,{x:p.x,y:p.y-camera.scale*.7-3},'#fff7e8',10)}
 if(preview){const a=preview.start,b=preview.end,n=preview.kind===0?(Math.abs(b.x-a.x)+1)*(Math.abs(b.y-a.y)+1):Math.abs(b.x-a.x)+Math.abs(b.y-a.y)+1;const p=worldToScreen((a.x+b.x)/2+.5,(a.y+b.y)/2+.5);const text=preview.kind===0?`${Math.abs(b.x-a.x)+1} × ${Math.abs(b.y-a.y)+1} · ${review?'reviewing':removeRequest?'preparing review':'release to review'}`:preview.kind===8?`${n} track tiles · up to $${n*12} + bridges`:`${n} ${n===1?'tile':'tiles'} · release to build`;ctx.font='600 10px system-ui';const w=ctx.measureText(text).width+20;pathRound(clamp(p.x-w/2,8,width-w-8),clamp(p.y-46,145,height-220),w,25,12,'#23483df0');drawLabel(text,{x:clamp(p.x,w/2+8,width-w/2-8),y:clamp(p.y-46,145,height-220)+16},'#fffcec',10)}
 frameTimes.push(performance.now()-start);if(frameTimes.length>180)frameTimes.shift();requestAnimationFrame(draw)}
// Read-only instrumentation binds browser input assertions to actual camera and server frames.
window.__flowgarden={get lab(){return cityLab.report},get renderedActors(){return trafficMotion.rendered.map(a=>({...a}))},get motionTime(){return trafficMotion.time},get stats(){return stats},get rails(){return rails.map(l=>({...l}))},get actors(){return actors.map(a=>({...a}))},get sessionStatus(){return sessionStatus},get detail(){return detail},get cells(){return[...cells.values()]},get view(){return{...serverView}},get camera(){return{...camera}},get gesture(){return gesture?{kind:gesture.kind,blocked:gesture.blocked}:null},get pointerCount(){return pointers.size},get draft(){return draft?{...draft}:null},get sequence(){return sequence},get tool(){return tool},get trackPreview(){return draft?.kind===8?trackPreviewPath(draft.start,draft.end).map(p=>({...p})):[]},get serviceStart(){return serviceStart?{...serviceStart}:null},get review(){return review?{...review}:null},get menuPage(){return menuPage},worldToScreen,screenToWorld,history,sentCommands,frameTimes};
setTool(-2);connect();requestAnimationFrame(draw);

$('inspect-details').addEventListener('click',e=>{const add=e.target.closest('[data-rail-stop]');if(add){const id=Number(add.dataset.railStop);setTool(11);addStopLine=id;toast('Tap the station to add. Traffic must be paused and this service empty and suspended.');return}const service=e.target.closest('[data-rail-service]');if(service){const l=rails.find(l=>l.id===Number(service.dataset.railService));if(l)send('rail-service',{x:l.id,kind:l.enabled?0:1});return}const b=e.target.closest('[data-signal]');if(b&&selected!==null)send('signal',{x:selected%128,y:Math.floor(selected/128),kind:Number(b.dataset.signal)})});
$('resume').onclick=()=>{ownerToken=randomHex(16);if(connected)send('resume');else connect()};

function updateFinances(){const s=stats,m=n=>'$'+(n||0).toLocaleString(),net=(s.ecoLastTaxes||0)+(s.ecoLastFares||0)-(s.ecoLastOperating||0);$('finance-details').innerHTML=`<dl class="finance-ledger"><dt>City funds</dt><dd>${m(s.cash)}</dd><dt>Resident savings</dt><dd>${m(s.ecoHouseholds)}</dd><dt>Business savings</dt><dd>${m(s.ecoBusinesses)}</dd></dl><h3>Last 64-cycle period</h3><dl class="finance-ledger"><dt>Taxes / fares</dt><dd>${m(s.ecoLastTaxes)} / ${m(s.ecoLastFares)}</dd><dt>Operation / upkeep</dt><dd>−${m(s.ecoLastOperating)}</dd><dt>Municipal balance</dt><dd>${net>=0?'+':'−'}${m(Math.abs(net))}</dd><dt>Unpaid upkeep</dt><dd>${m(s.ecoUpkeepDue)}</dd></dl><p class="small">This period so far: ${m(s.ecoPeriodTaxes)} taxes, ${m(s.ecoPeriodFares)} fares and ${m(s.ecoPeriodOperating)} costs. Since this ledger began: ${m(s.ecoExports)} work revenue, ${m(s.ecoWages)} wages, ${m(s.ecoSales)} local spending.</p>`}
$('finance-open').onclick=()=>{updateFinances();$('finance').showModal()};
