import {updateFinances} from './finances.js';
import {connections,entranceLinks,roadHeatSegments,riverPoints,waterAt,drawRiver,isRoad,layerOf,gridY,roadTool,roadKind,undergroundQuote} from './geometry.js';
import {createCityLab} from './lab.js';
import {CommandQueue,mapEdit,cityMutation} from './commands.js';
import {createLineManager,lineState,lineEditable,railColors} from './lines.js';
import {TrafficMotion,actorPose,pedestrianSize,streetCaption,TileIndex,railPath,railGeometry,railProgress,railPose,railPresentation} from './motion.js';
const trafficMotion=new TrafficMotion(),tileIndex=new TileIndex();
tileIndex.rebuild(new Map());let railPaint=railPresentation([],[]),frameArea=null,drawCount=0;
// Browser presentation and gestures only. lkjscript owns every city, rule, queue and tick.
const $=id=>document.getElementById(id),canvas=$('map');let ctx=canvas.getContext('2d');
const staticMapCanvas=document.createElement('canvas'),staticMapContext=staticMapCanvas.getContext('2d');let staticMapKey='',mapRevision=0;
const names=['Empty land','Local road','Avenue','Home','Workplace','Shop','Park','Footpath','Station','One-way east','One-way south','One-way west','One-way north','Tunnel portal'],prices=[0,8,24,70,140,110,90,4,90,12,12,12,12,60];
const recoveryStorageKey='flowgarden-city-v4';let tracks=new Set(),railBend=0,serviceStart=null,addStopLine=0,inspectFunds=0;let rails=[],inspectRailPlan=null;let cityToken='',ownerToken='',sessionStatus=0,actors=[],inspectResident=null,detail=true,storageError=false;
const randomHex=n=>Array.from(crypto.getRandomValues(new Uint8Array(n)),b=>b.toString(16).padStart(2,'0')).join('');
try{cityToken=localStorage.getItem(recoveryStorageKey)||randomHex(32);if(!/^[a-f0-9]{64}$/.test(cityToken))throw Error('Invalid recovery key');localStorage.setItem(recoveryStorageKey,cityToken)}catch(e){storageError=true}
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),reducedMotion=matchMedia('(prefers-reduced-motion: reduce)');
let ws,connected=false,commandId=0,sequence=0,reconnect,persistentSession=false,restoredCheckpoint=-1;
let keepaliveTimer=0,renewalTimer=0,renewalAck=0,renewalClose=false;
let river=[],riverWidth=6;
let layer=0,onewayDirection=0,tunnelMode=false;
let cells=new Map(),stats={},serverView={x:0,y:0,w:30,h:20,layer:0},viewPending=null,viewTimer=0,lastViewSent=0;
let cameraMotionUntil=0;
let width=1,height=1,dpr=1,initialized=false,tool=-2,selected=null,hover=null,draft=null,noticeTimer;
const camera={x:64,y:64,scale:25,angle:0,min:12,max:120,fit:25};
const pointers=new Map();let gesture=null,gestureSerial=0;
const history=[],sentCommands=[],frameTimes=[];
let preferences={grid:false,motion:false};try{preferences={...preferences,...JSON.parse(localStorage.getItem('traffic-city-preferences')||'{}')}}catch{}
let palette='',menuPage='home',menuWasRunning=false,menuHistory=false,firstCityFrame=true,lastFrame=null,review=null,removalBounds=null,removeRequest=0,removeWasRunning=false,reviewCamera=null,mutationPending=null,confirmKind='';
const cityLab=createCityLab({send,cancelGesture,setTool,toast,focusHome(id){setLayer(0);cancelGesture();camera.x=id%128+.5;camera.y=gridY(id)+.5;cameraChanged();inspect(id,true);$('inspect-title').focus({preventScroll:true})},leaveMenu(){menuWasRunning=false;closeMenu()}});
const commandQueue=new CommandQueue(item=>{const{id,...action}=item;ws.send(JSON.stringify({id,action,token:action.op==='resume'?cityToken:'',owner:action.op==='resume'?ownerToken:''}))},{changed:updateDelivery});
const lineManager=createLineManager({getLines:()=>rails,getStations:()=>[...cells.values()].filter(c=>c.kind===8).map(c=>c.id),getStatus:()=>sessionStatus,getPaused:()=>stats.paused,getPending:()=>commandQueue.items,send,addStop:beginAddStop,focusStation(id){setLayer(0);camera.x=id%128+.5;camera.y=gridY(id)+.5;cameraChanged();inspect(id,true)},beginService(){setTool(10)},onOpen(){cancelGesture();setTool(-2)}});
$('lines-open').onclick=()=>lineManager.show();
function beginAddStop(id){setTool(11);addStopLine=id;toast('Choose an existing station. Only this stopped, empty line changes.');}
function updateDelivery(){const n=commandQueue.items.filter(c=>cityMutation(c.op)).length;const status=$('edit-delivery');status.hidden=!n;status.textContent=n?`${n} ${n===1?'change':'changes'} awaiting the city server…`:'';}
const motionReduced=()=>reducedMotion.matches||preferences.motion;

function mapArea(){if(frameArea)return frameArea;const top=height<500?104:width<=680?180:150;const bottom=Math.max(top+90,Math.min(height-25,document.querySelector('.bottom-ui').getBoundingClientRect().top-18));return{top,bottom,height:Math.max(90,bottom-top)}}
function origin(){const a=mapArea();return{x:width/2,y:(a.top+a.bottom)/2}}
function screenToWorld(p){const o=origin(),c=Math.cos(camera.angle),s=Math.sin(camera.angle),x=(p.x-o.x)/camera.scale,y=(p.y-o.y)/camera.scale;return{x:camera.x+c*x+s*y,y:camera.y-s*x+c*y}}
function worldToScreen(x,y){const o=origin(),c=Math.cos(camera.angle),s=Math.sin(camera.angle),dx=(x-camera.x)*camera.scale,dy=(y-camera.y)*camera.scale;return{x:o.x+c*dx-s*dy,y:o.y+s*dx+c*dy}}
function position(e){const r=canvas.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}}
function inside(p){return p.x>=0&&p.y>=0&&p.x<width&&p.y<height}
function tile(p){const w=screenToWorld(p);return{x:Math.floor(w.x),y:Math.floor(w.y)}}
function straighten(a,b){return Math.abs(b.x-a.x)>Math.abs(b.y-a.y)?{x:b.x,y:a.y}:{x:a.x,y:b.y}}
function visibleRect(){const a=mapArea();const corners=[{x:0,y:a.top},{x:width,y:a.top},{x:0,y:a.bottom},{x:width,y:a.bottom}].map(screenToWorld);const x=clamp(Math.floor(Math.min(...corners.map(p=>p.x)))-1,0,127),y=clamp(Math.floor(Math.min(...corners.map(p=>p.y)))-1,0,127);return{x,y,w:clamp(Math.ceil(Math.max(...corners.map(p=>p.x)))+1-x,1,128-x),h:clamp(Math.ceil(Math.max(...corners.map(p=>p.y)))+1-y,1,128-y)}}
function cameraChanged(){cameraMotionUntil=performance.now()+120;if(camera.scale<=Math.min(width,height)/128){camera.x=64;camera.y=64}camera.x=clamp(camera.x,0,128);camera.y=clamp(camera.y,0,128);$('zoom-label').textContent=(camera.scale/camera.fit).toFixed(1)+'×';scheduleView()}
function anchorZoom(scale,p,anchor=screenToWorld(p)){camera.scale=clamp(scale,camera.min,camera.max);const after=screenToWorld(p);camera.x+=anchor.x-after.x;camera.y+=anchor.y-after.y;cameraChanged()}
function fitCity(){cancelGesture();let ids=[...cells.keys()].filter(id=>layerOf(id)===layer);if(!ids.length)ids=[...cells.keys()].filter(id=>layerOf(id)===0);const xs=ids.map(id=>id%128),ys=ids.map(id=>gridY(id));const minX=ids.length?Math.min(...xs):3,maxX=ids.length?Math.max(...xs):24,minY=ids.length?Math.min(...ys):5,maxY=ids.length?Math.max(...ys):15;camera.x=(minX+maxX+1)/2;camera.y=(minY+maxY+1)/2;const w=maxX-minX+2,h=maxY-minY+3;camera.scale=clamp(Math.min((width-50)/(camera.angle?h:w),mapArea().height/(camera.angle?w:h)),camera.min,camera.max);selected=null;$('inspector').hidden=true;cameraChanged()}
function resize(){const r=canvas.getBoundingClientRect();if(!r.width||!r.height)return;const oldFit=camera.fit,ratio=camera.scale/oldFit;cancelGesture();width=r.width;height=r.height;dpr=Math.min(devicePixelRatio||1,2);canvas.width=Math.round(width*dpr);canvas.height=Math.round(height*dpr);camera.angle=height>width*1.15?-Math.PI/2:0;
 const a=camera.angle?height:width,b=camera.angle?width:height;const min=Math.max(1,Math.min(width,height)/144);camera.min=min;
 const usableW=width-50,usableH=mapArea().height;camera.fit=Math.max(min,Math.min(usableW/(camera.angle?13:24),usableH/(camera.angle?24:13)));camera.max=Math.max(camera.fit*5,96);camera.scale=initialized?clamp(camera.fit*ratio,min,camera.max):camera.fit;initialized=true;cameraChanged();}
new ResizeObserver(resize).observe(canvas);
function send(op,fields={}){if(!connected||ws.readyState!==WebSocket.OPEN){toast('Wait for the city connection before editing.');return 0}if(!['resume','view','inspect'].includes(op)&&sessionStatus!==1){toast('Resume your city before editing.');return 0}const action={op,x:0,y:0,x2:0,y2:0,kind:0,...fields};let id;try{id=commandQueue.enqueue(action)}catch{toast('The connection interrupted this change. Reconnect and check the saved city before repeating it.',15000);ws.close();return 0}if(!id){toast('The edit queue is full. This stroke was not sent; wait for pending changes to finish.',8000);return 0}commandId=id;sentCommands.push({id,...action});if(sentCommands.length>200)sentCommands.shift();return id}
function scheduleView(){clearTimeout(viewTimer);viewTimer=setTimeout(syncView,Math.max(0,160-(performance.now()-lastViewSent)))}
function syncView(force=false){if(!connected||viewPending)return;const r=visibleRect();const covered=(r.w*r.h<=1024)===(serverView.w*serverView.h<=1024)&&r.x>=serverView.x&&r.y>=serverView.y&&r.x+r.w<=serverView.x+serverView.w&&r.y+r.h<=serverView.y+serverView.h;
 if(covered&&!force&&layer===serverView.layer&&r.x===serverView.x&&r.y===serverView.y&&r.w===serverView.w&&r.h===serverView.h)return;const id=send('view',{x:r.x,y:r.y,x2:r.w,y2:r.h,kind:layer});if(id){viewPending={id,rect:{...r,layer}};lastViewSent=performance.now()}}
// Native sessions are bounded. Keep an observed city connected, and rotate a
// long session only after a native save acknowledgement, before its hard limit.
function scheduleRenewal(delay=25*60*1000){clearTimeout(renewalTimer);renewalTimer=setTimeout(()=>{if(connected&&sessionStatus===1&&!cityLab.active&&!mutationPending&&!gesture&&!document.querySelector('#removal[open],#menu[open]'))renewalAck=send('save');else if(connected)scheduleRenewal(5000)},delay)}
function startConnectionTimers(){clearInterval(keepaliveTimer);keepaliveTimer=setInterval(()=>{if(connected&&sessionStatus===1)syncView(true)},60000);scheduleRenewal()}
function stopConnectionTimers(){clearInterval(keepaliveTimer);clearTimeout(renewalTimer);renewalAck=0}
function connect(){clearTimeout(reconnect);if(storageError){$('connection').textContent='Storage unavailable';toast('Browser storage is unavailable or the city key is invalid. Enable local storage before playing; no city has been replaced.',30000);return}const endpoint=new URL('/live',location.href);endpoint.protocol=location.protocol==='https:'?'wss:':'ws:';const port=new URLSearchParams(location.search).get('session_port');if(port!==null){if(!/^\d{1,5}$/.test(port)||Number(port)<1||Number(port)>65535){toast('Invalid session port.');return}endpoint.port=String(Number(port))}
 ownerToken=randomHex(16);ws=new WebSocket(endpoint);ws.onopen=()=>{connected=true;commandId=0;sequence=0;sessionStatus=0;commandQueue.reset();viewPending=null;cancelGesture();$('connection').textContent='Resuming…';$('connection').classList.remove('offline');send('resume');startConnectionTimers()};
 ws.onmessage=e=>{const f=JSON.parse(e.data);if(f.seq<=sequence)return;sequence=f.seq;try{commandQueue.acknowledge(f.ack)}catch{toast('The city connection lost command order. Reconnecting without replaying uncertain edits.',15000);ws.close(1002,'command order');return}commandId=Math.max(commandId,f.ack);persistentSession=true;sessionStatus=f.status;detail=f.detail;actors=f.actors||[];inspectResident=f.inspect;rails=f.rails||[];inspectFunds=f.inspectFunds||0;inspectRailPlan=f.inspectRail;
 if(f.mapChanged){river=riverPoints(f.river||[]);riverWidth=f.riverWidth||6;tracks=new Set(f.tracks||[]);mapRevision++;cells=new Map(f.overview.map(v=>{const id=Math.floor(v/16);return[id,{id,kind:v%16,q:0,walk:0,flow:0,inside:0,junction:0,control:0}]}))}else if(f.reset){for(const c of cells.values()){c.q=0;c.walk=0;c.flow=0;c.inside=0}}
 for(const c of f.cells){if(c.kind)cells.set(c.id,c);else cells.delete(c.id)}if(!detail){for(const c of cells.values())c.q=0;for(const v of f.heat||[]){const c=cells.get(Math.floor(v/32));if(c)c.q=v%32}}
 tileIndex.rebuild(cells);railPaint=railPresentation(tileIndex.stations,rails);trafficMotion.receive(f,performance.now(),cells);stats=f.stats;if(firstCityFrame&&f.status===1&&f.mapChanged){firstCityFrame=false;fitCity()}if(f.view)serverView=f.view;if(viewPending&&f.ack>=viewPending.id){serverView=f.view||viewPending.rect;viewPending=null}history.push({tick:stats.tick,backlog:stats.requested-stats.arrived,bytes:e.data.length});if(history.length>300)history.shift();update(f);if(selected!==null)inspect(selected,false);scheduleView();if(renewalAck&&f.ack>=renewalAck){renewalAck=0;if(f.status===1&&f.saved===f.stats.tick){renewalClose=true;ws.close(1000,'saved city connection renewal')}else scheduleRenewal(60000)}lineManager.render();if(f.status===1||f.status===0)commandQueue.flush()};
 ws.onclose=()=>{const delay=renewalClose?250:2500;renewalClose=false;stopConnectionTimers();connected=false;const abandoned=commandQueue.reset().filter(c=>cityMutation(c.op));cityLab.offline();abandonPending();viewPending=null;cancelGesture();$('connection').textContent='Offline';$('connection').classList.add('offline');if(sessionStatus!==2){toast('Reconnecting to your saved city…',6000);reconnect=setTimeout(connect,delay)}if(abandoned.length)toast(`${abandoned.length} pending changes lost their connection. Unsent changes were not applied; check the saved city before repeating an unacknowledged change.`,20000)};ws.onerror=()=>toast('City connection unavailable. Your saved city is retained.',6000);
}
function toast(message,duration=3500){if(!message)return;clearTimeout(noticeTimer);$('notice').textContent=message;$('notice').classList.add('visible');noticeTimer=setTimeout(()=>{$('notice').classList.remove('visible')},duration)}
function update(f){const street=streetCaption((f.view?.layer||0)===layer?f:{mapChanged:true});$('street-counts').textContent=street.counts;$('street-sample').textContent=street.sample;$('cash').textContent='$'+stats.cash.toLocaleString();$('served').textContent=stats.population+' people';$('backlog').textContent=stats.waiting.toLocaleString();$('wait-total').textContent=stats.waiting.toLocaleString();$('wait-planning').textContent=(stats.planningLong||0).toLocaleString();$('wait-other').textContent=(stats.waiting-(stats.planningLong||0)).toLocaleString();$('planning-total').textContent=(stats.planning||0).toLocaleString();$('queue-stat').title=`${stats.waiting} long waits, including ${stats.planningLong||0} computing routes. ${stats.planning||0} total route-planning requests. Open the breakdown.`;$('arrived').textContent=stats.visits.toLocaleString();$('disconnected').textContent=stats.disconnected.toLocaleString();$('cycle').textContent=(stats.paused?'PLANNING':'IN MOTION')+' · '+(detail?'CYCLE '+stats.tick:'CITY OVERVIEW');$('queue-stat').classList.toggle('congested',stats.waiting>stats.population/4);$('play').disabled=sessionStatus!==1;$('play').setAttribute('aria-label',stats.paused?'Start traffic':'Pause traffic');$('play-icon').innerHTML=stats.paused?'<svg viewBox="0 0 20 20"><path d="M6 3l11 7-11 7z"/></svg>':'<svg viewBox="0 0 20 20"><path d="M4 3h4v14H4zM12 3h4v14h-4z"/></svg>';$('play-label').textContent=stats.paused?'Start':'Pause';$('play').classList.toggle('running',!stats.paused&&sessionStatus===1);document.querySelector('.live-dot').classList.toggle('running',!stats.paused&&sessionStatus===1);
 const level=String(stats.level).padStart(2,'0'),target=stats.growthTarget;$('level').textContent=level;$('chapter').textContent=level;$('mission-title').textContent='ROOM TO GROW';$('mission-short').textContent=stats.growth?'Ready to expand.':`${stats.population} / ${target} people · ${stats.progress} / ${target} visits`;$('target-text').textContent=stats.healthy>=24?'✓ steady':'View goal →';$('progress').style.width=Math.min(100,stats.progress/target*100,stats.population/target*100)+'%';$('grow').disabled=!stats.growth;$('grow').hidden=!stats.growth;$('grow').innerHTML=`Expand district <span>$${stats.growthCost} →</span>`;$('goal-title').textContent='Make room for more';$('mission-copy').textContent=`Reach ${target} residents and ${target} completed visits in this district. Keep long waits below a quarter of the population, with nobody disconnected, for 24 cycles.`;$('growth-note').textContent=`Expansion costs $${stats.growthCost}. The next population, visits and funding requirements double.`;$('permits').textContent=stats.permits+' home permits';$('travel-summary').textContent=`${stats.workVisits} work · ${stats.shopVisits} shopping · ${stats.leisureVisits} leisure visits. ${stats.walkTrips} walking / ${stats.carTrips} driving choices · ${stats.railBoardings||0} rail boardings. Rail operation: $${stats.railSpent||0}. Average completed trip: ${stats.average} cycles.`;
 $('save').disabled=sessionStatus!==1;$('save').textContent='Save now';$('saved').textContent=f.saved>=0?`Saved · cycle ${f.saved}`:'Not saved';$('connection').textContent=sessionStatus===1?(f.saved<stats.tick?'● Live · saving…':'● Saved'):sessionStatus===2?'Another tab is active':sessionStatus===0?'Resuming…':'Recovery needed';$('resume').hidden=sessionStatus===1||sessionStatus===0;$('session-note').textContent='Changes save automatically. Reopen in this browser to resume. Clearing browser data loses this city’s recovery key.';
 if(f.notice&&f.status!==0)toast(f.notice,sessionStatus===1?4000:15000);updateInterface(f);cityLab.receive(f);
}
function setTool(n){if(n>=0&&cityLab.active&&cityLab.phase!==1){toast('Choose Edit plan before changing this experiment.');return}cancelGesture();tool=n;hover=null;canvas.dataset.mode=n===-2?'move':'build';if(n===-2||n===0)showPalette('');if(n>=8&&n<=11){if(layer)setLayer(0);showPalette('rail')}if(n>=20){showPalette('roads')}if(n>=3&&n<=6&&layer)setLayer(0);if(n===22&&layer)setLayer(0);if(n!==10)serviceStart=null;if(n!==11)addStopLine=0;$('inspector').hidden=true;for(const b of document.querySelectorAll('[data-tool]')){const on=Number(b.dataset.tool)===n;b.classList.toggle('selected',on);b.setAttribute('aria-pressed',String(on))}const touch=matchMedia('(pointer: coarse)').matches;$('hint').textContent=n===-2?(touch?'Drag to explore · pinch to zoom':'Drag to explore · scroll to zoom'):n===0?`Remove ${layer?'underground':'ground'} only · release to review`:n===20?'Choose arrow direction · R rotates · walkers use both directions':n===22?'Tap above an existing tunnel to add a dry-land portal':n===8?'Drag track · diagonal drags make a bend':n===9?'Tap an empty track beside a road or path':n===10?'Tap the first station, then the last station':n===11?'Tap a station to add it to this suspended service':n>2&&n!==7?'Tap to place · two fingers move':layer?'Draw underground · connect to a portal':tunnelMode?'Draw a tunnel · dry entrances at both ends':'Drag bank to bank for a bridge · two fingers move';updateRoadOptions()}
function updateRoadOptions(){
 $('road-options').hidden=palette!=='roads';$('tunnel-mode').disabled=layer===1||tool===22;$('tunnel-mode').setAttribute('aria-pressed',String(tunnelMode&&layer===0));$('tunnel-mode').textContent=layer?'Underground network':tunnelMode?'Tunnel + two entrances':'Surface construction';$('oneway-direction').disabled=tool!==20;
 for(const [n,normal,under]of [[1,'$8 land · $32 bridge','$48 / tile'],[2,'$24 land · $72 bridge','$72 / tile'],[7,'$4 land · $16 bridge','$24 / tile'],[20,'$12 land · $48 bridge','$60 / tile']])document.querySelector(`#roads-palette [data-tool="${n}"] small`).textContent=layer||tunnelMode?under:normal;
 $('road-depth-note').textContent=tool===22?'$60 · dry land above an existing underground road or path.':layer?'Only the underground layer changes. Add a portal on the ground to connect it.':tunnelMode?'At least 3 tiles. Two dry-land entrances cost $60 each; all underground tiles are included in the preview.':'One-way cars need a return route; walkers go both ways. Tunnels leave the ground above their interior untouched.';
}
function setLayer(next){if(next===layer)return;if(review||removeRequest||mutationPending){toast('Finish or cancel the removal review before switching layers.');return}cancelGesture();layer=next;selected=null;$('inspector').hidden=true;staticMapKey='';trafficMotion.visible=false;trafficMotion.rendered=[];for(const b of document.querySelectorAll('[data-layer]'))b.setAttribute('aria-pressed',String(Number(b.dataset.layer)===layer));document.body.dataset.layer=String(layer);if(layer&&tool>=3&&tool<=11&&tool!==7||layer&&tool===22){tool=-2;setTool(-2)}updateRoadOptions();scheduleView()}
for(const b of document.querySelectorAll('[data-layer]'))b.onclick=()=>setLayer(Number(b.dataset.layer));
$('tunnel-mode').onclick=()=>{cancelGesture();tunnelMode=!tunnelMode;updateRoadOptions();if(roadTool(tool))setTool(tool)};
$('oneway-direction').onchange=()=>{cancelGesture();onewayDirection=Number($('oneway-direction').value)};
$('rail-bend').onclick=()=>{railBend=1-railBend;$('rail-bend').textContent=railBend?'Bend: down, then across ↕':'Bend: across, then down ↔'};
for(const b of document.querySelectorAll('[data-tool]'))b.onclick=()=>setTool(Number(b.dataset.tool));
for(const b of document.querySelectorAll('button[data-palette]'))b.onclick=()=>{const next=palette===b.dataset.palette?'':b.dataset.palette;showPalette(next);if(next)setTool(next==='roads'?1:3);else setTool(-2)};
function showPalette(name){palette=name;document.body.dataset.palette=name;$('palette').hidden=!name;$('roads-palette').hidden=name!=='roads';$('places-palette').hidden=name!=='places';$('rail-palette').hidden=name!=='rail';$('palette-title').textContent=name==='roads'?'ROADS & PATHS · DRAW A LINE':name==='rail'?'RAIL · TRACK, STATIONS & SERVICES':'EVERYDAY PLACES · TAP A TILE';for(const b of document.querySelectorAll('button[data-palette]'))b.setAttribute('aria-expanded',String(b.dataset.palette===name));updateRoadOptions();cameraChanged();}
$('palette-close').onclick=()=>setTool(-2);
$('play').onclick=()=>send('set-running',{kind:stats.paused?1:0});$('grow').onclick=()=>send('grow');$('save').onclick=()=>send('save');$('fit').onclick=fitCity;$('zoom-in').onclick=()=>{cancelGesture();anchorZoom(camera.scale*1.3,origin())};$('zoom-out').onclick=()=>{cancelGesture();anchorZoom(camera.scale/1.3,origin())};$('inspect-close').onclick=closeInspector;
function closeInspector(){selected=null;$('inspector').hidden=true;if(cityLab.atlas.active)$('atlas-home-select').focus()}
$('goal-open').onclick=()=>{cancelGesture();$('goal').showModal()};$('queue-stat').onclick=()=>{$('goal-open').click()};
$('help-open').onclick=()=>{$('help').showModal()};for(const b of document.querySelectorAll('[data-close]'))b.onclick=()=>$(b.dataset.close).close();
function showMenuPage(name){menuPage=name;for(const page of ['home','preferences','manage','examples','confirm'])$('menu-'+page).hidden=page!==name;}
function openMenu(){if($('menu').open)return;cancelGesture();setTool(-2);menuWasRunning=!stats.paused&&!cityLab.active;showMenuPage('home');$('menu').showModal();$('continue').focus();if(!menuHistory){window.history.pushState({trafficCityMenu:true},'');menuHistory=true}}
function clearReview(){if(connected&&sessionStatus===1)send('cancel-review');confirmKind='';review=null;removalBounds=null;removeRequest=0;}
function closeMenu(fromHistory=false){if(!$('menu').open||mutationPending)return;clearReview();$('menu').close();if(menuWasRunning&&stats.paused&&sessionStatus===1)send('set-running',{kind:1});menuWasRunning=false;$('menu-open').focus();if(menuHistory){menuHistory=false;if(!fromHistory)window.history.back()}}
$('menu-open').onclick=openMenu;$('menu-close').onclick=()=>closeMenu();$('continue').onclick=()=>closeMenu();
$('examples-open').onclick=()=>{showMenuPage('examples');document.querySelector('[data-scenario]').focus()};for(const b of document.querySelectorAll('[data-scenario]'))b.onclick=()=>reviewScenario(Number(b.dataset.scenario));
$('preferences-open').onclick=()=>{showMenuPage('preferences');$('grid-setting').focus()};$('manage-open').onclick=()=>{showMenuPage('manage');$('new-city').focus()};for(const b of document.querySelectorAll('[data-menu-back]'))b.onclick=()=>{showMenuPage('home');$('continue').focus()};
function cancelCityReview(){const sample=confirmKind.startsWith('scenario-')?Number(confirmKind.slice(9)):0;clearReview();mutationPending=null;showMenuPage(sample?'examples':'manage');(sample?document.querySelector(`[data-scenario="${sample}"]`):$('new-city')).focus()}
$('city-cancel').onclick=cancelCityReview;$('confirm-back').onclick=cancelCityReview;
function reviewCity(kind){if(sessionStatus!==1)return;confirmKind=kind;mutationPending=null;showMenuPage('confirm');$('confirm-title').textContent=kind==='reset'?'Start a new city?':'Restore your previous city?';$('confirm-copy').textContent=kind==='reset'?'Your current city becomes the recoverable backup. A new district begins in the middle of the map. Any older backup is replaced.':'Your previous city will replace this one. This uses the backup once; progress in your current city will be discarded.';$('city-confirm').textContent=kind==='reset'?'Start new city':'Restore city';$('city-cancel').textContent='Keep current city';$('confirm-status').textContent='Preparing your saved city…';$('city-confirm').disabled=true;$('city-cancel').focus();send('review-'+kind)}
function reviewScenario(id){if(sessionStatus!==1)return;confirmKind='scenario-'+id;mutationPending=null;showMenuPage('confirm');$('confirm-title').textContent='Load '+['','Garden City','Crossing Challenge','Willow Metro','River Boroughs','Twinbank Region','Commuter Boroughs'][id]+'?';$('confirm-copy').textContent='This creates your own playable copy. Your current city becomes the recoverable backup, replacing any older backup.';$('city-confirm').textContent='Load city';$('city-cancel').textContent='Keep current city';$('confirm-status').textContent='Preparing your saved city…';$('city-confirm').disabled=true;$('city-cancel').focus();send('review-scenario',{kind:id})}
$('new-city').onclick=()=>reviewCity('reset');$('restore-city').onclick=()=>reviewCity('restore');
$('city-confirm').onclick=()=>{if(!lastFrame||!confirmKind||mutationPending)return;const id=send(confirmKind.startsWith('scenario-')?'load-scenario':confirmKind==='reset'?'reset-city':'restore-city',{x:lastFrame.confirmation,kind:confirmKind.startsWith('scenario-')?Number(confirmKind.slice(9)):0});if(id){mutationPending={id,type:confirmKind};$('city-confirm').disabled=true;$('city-cancel').disabled=true;$('confirm-back').disabled=true;$('confirm-status').textContent='Saving city change…'}};
$('menu').addEventListener('cancel',e=>{e.preventDefault();if(mutationPending)return;if(menuPage==='confirm')cancelCityReview();else if(menuPage!=='home'){showMenuPage('home');$('continue').focus()}else closeMenu()});
window.addEventListener('popstate',()=>{if(menuHistory){menuHistory=false;closeMenu(true)}});
$('grid-setting').checked=preferences.grid;$('motion-setting').checked=preferences.motion;for(const [id,key]of [['grid-setting','grid'],['motion-setting','motion']])$(id).onchange=()=>{preferences[key]=$(id).checked;try{localStorage.setItem('traffic-city-preferences',JSON.stringify(preferences))}catch{toast('This preference cannot be saved on this device.')}};
function cancelRemoval(){if(mutationPending)return;if(reviewCamera){Object.assign(camera,reviewCamera);reviewCamera=null;cameraChanged()}clearReview();if($('removal').open)$('removal').close();if(removeWasRunning&&stats.paused&&sessionStatus===1)send('set-running',{kind:1});removeWasRunning=false;canvas.focus()}
$('remove-cancel').onclick=cancelRemoval;$('removal').addEventListener('cancel',e=>{e.preventDefault();cancelRemoval()});
$('remove-confirm').onclick=()=>{if(!review?.valid||mutationPending)return;const id=send('apply-remove',{x:review.id});if(id){mutationPending={id,type:'remove'};$('remove-confirm').disabled=true;$('remove-cancel').disabled=true}};
function abandonPending(){if(reviewCamera){Object.assign(camera,reviewCamera);reviewCamera=null;cameraChanged()}removeRequest=0;removalBounds=null;review=null;mutationPending=null;confirmKind='';if($('removal').open)$('removal').close();$('remove-confirm').disabled=false;$('remove-cancel').disabled=false;$('city-cancel').disabled=false;$('confirm-back').disabled=false;if(menuPage==='confirm'){$('city-confirm').disabled=true;$('confirm-status').textContent='Connection interrupted. Reconnect, then review this action again.'}}
function focusRemoval(original){const selectedLines=(original.layer?[]:rails).filter(l=>railIntersects(l,original));const xs=[original.x,original.x2,...selectedLines.flatMap(l=>[l.a%128,l.b%128])],ys=[original.y,original.y2,...selectedLines.flatMap(l=>[gridY(l.a),gridY(l.b)])];const q={x:Math.min(...xs),x2:Math.max(...xs),y:Math.min(...ys),y2:Math.max(...ys)};reviewCamera={...camera};const sheet=$('removal').getBoundingClientRect(),area=mapArea();const mobile=width<=680;const target=mobile?{x:width/2,y:(area.top+sheet.top-18)/2}:{x:Math.min(width/2,(sheet.left-20)/2),y:(area.top+area.bottom)/2};const availableW=mobile?width-32:sheet.left-45,availableH=mobile?Math.max(80,sheet.top-area.top-30):area.height;const w=q.x2-q.x+2,h=q.y2-q.y+2;camera.scale=clamp(Math.min(camera.scale,availableW/(camera.angle?h:w),availableH/(camera.angle?w:h)),camera.min,camera.max);const anchor=screenToWorld(target);camera.x+=(q.x+q.x2+1)/2-anchor.x;camera.y+=(q.y+q.y2+1)/2-anchor.y;cameraChanged();}
function updateInterface(f){lastFrame=f;if($('finance').open)updateFinances(stats);$('menu-district').textContent='WILLOW · DISTRICT '+String(stats.level).padStart(2,'0');$('menu-summary').textContent=`${stats.population} residents · ${stats.visits} everyday visits`;const savedText=f.saved>=0?`Saved at cycle ${f.saved}`:'Not saved yet';$('menu-saved').textContent=sessionStatus===1?savedText:sessionStatus===2?'Another tab is active. Resume here to continue.':'Connecting to your city…';$('restore-city').disabled=sessionStatus!==1||!f.undo;$('restore-caption').textContent=f.undo?'Return to your previous city →':'No previous city yet';$('new-city').disabled=sessionStatus!==1;$('cancelled-summary').textContent=`${stats.cancelled||0} journeys were cancelled by confirmed demolition. These are counted separately from completed visits.`;
 if(menuPage==='confirm'&&!mutationPending){const expected=confirmKind.startsWith('scenario-')?10+Number(confirmKind.slice(9)):confirmKind==='reset'?1:2;$('city-confirm').disabled=sessionStatus!==1||f.management!==expected||!f.confirmation;$('confirm-status').textContent=$('city-confirm').disabled?'This review is unavailable. Go back and try again.':'Your current city is saved. Nothing changes until you confirm.'}
 if(removeRequest&&f.ack>=removeRequest){const requested=removeRequest;removeRequest=0;if(f.quote?.valid&&f.quote.id===requested&&sessionStatus===1){review=f.quote;const q=review;removalBounds={start:{x:q.x,y:q.y},end:{x:q.x2,y:q.y2},kind:0};$('removal-size').textContent=`${q.layer?'Underground':'Ground'} · ${q.x2-q.x+1} × ${q.y2-q.y+1} selection · ${q.tiles} built ${q.tiles===1?'tile':'tiles'}`;$('removal-mode').textContent=stats.paused?'REVIEW AREA · CITY PAUSED':'REVIEW AREA · CITY STILL RUNNING';$('removal-estimate').textContent=stats.paused?'Counts for the current paused city.':'Movement continues. People and journey counts are a preview; confirmation recalculates who is affected.';$('removal-details').innerHTML=`<dt>Salvage refund</dt><dd>+$${q.refund}</dd>${q.rails?`<dt>Services cancelled</dt><dd>${q.rails}</dd>`:''}<dt>Residents moving out</dt><dd>${q.moveouts}</dd><dt>Residents returning home</dt><dd>${q.relocated}</dd><dt>Journeys cancelled</dt><dd>${q.cancelled}</dd><dt>Home permits returned</dt><dd>${q.homes}</dd>`;$('remove-confirm').disabled=false;$('remove-cancel').disabled=false;$('removal').showModal();focusRemoval(q);$('remove-cancel').focus()}else{removalBounds=null;removeWasRunning=false}}
 if(mutationPending&&f.ack>=mutationPending.id){const pending=mutationPending;mutationPending=null;$('city-cancel').disabled=false;$('confirm-back').disabled=false;$('remove-confirm').disabled=false;$('remove-cancel').disabled=false;if(pending.type==='remove'){reviewCamera=null;review=null;removalBounds=null;if($('removal').open)$('removal').close();if(removeWasRunning&&stats.paused&&sessionStatus===1)send('set-running',{kind:1});removeWasRunning=false;canvas.focus()}else{confirmKind='';menuWasRunning=false;showMenuPage('home');if(sessionStatus===1){fitCity();$('continue').focus()}}}
}
// A second pointer irrevocably cancels this stroke. Building requires a fresh gesture.
function cancelGesture(){gesture=null;draft=null;hover=null;const ids=[...pointers.keys()];pointers.clear();canvas.dataset.gesture='';for(const id of ids){try{if(canvas.hasPointerCapture(id))canvas.releasePointerCapture(id)}catch{}}}
function beginPinch(){const [a,b]=[...pointers.values()],mid={x:(a.x+b.x)/2,y:(a.y+b.y)/2};draft=null;hover=null;gesture={kind:'pinch',anchor:screenToWorld(mid),distance:Math.max(1,Math.hypot(a.x-b.x,a.y-b.y)),scale:camera.scale,blocked:true};canvas.dataset.gesture='pinch'}
canvas.addEventListener('pointerdown',e=>{if(tool===0&&(removeRequest||review||mutationPending)){toast('Finish or cancel the current removal review first.');return}if(e.pointerType==='mouse'&&![0,1,2].includes(e.button))return;e.preventDefault();canvas.focus({preventScroll:true});const p=position(e);pointers.set(e.pointerId,{...p,type:e.pointerType});canvas.setPointerCapture(e.pointerId);if(pointers.size>=2){beginPinch();return}const pan=tool===-2||e.button===1||e.button===2||e.shiftKey;gesture={kind:pan?'pan':'build',id:e.pointerId,start:p,camera:{x:camera.x,y:camera.y},moved:false,blocked:false,serial:++gestureSerial};canvas.dataset.gesture=gesture.kind;if(!pan){draft={start:tile(p),end:tile(p),kind:tool,cancelled:false};hover=draft.end}});
canvas.addEventListener('pointermove',e=>{const p=position(e);if(!pointers.has(e.pointerId)){if(e.pointerType==='mouse'&&inside(p)&&tool!==-2)hover=tile(p);return}e.preventDefault();pointers.set(e.pointerId,{...p,type:e.pointerType});if(!gesture)return;
 if(pointers.size>=2){if(gesture.kind!=='pinch')beginPinch();const[a,b]=[...pointers.values()],mid={x:(a.x+b.x)/2,y:(a.y+b.y)/2};anchorZoom(gesture.scale*Math.hypot(a.x-b.x,a.y-b.y)/gesture.distance,mid,gesture.anchor);return}
 if(gesture.id!==e.pointerId)return;const dx=p.x-gesture.start.x,dy=p.y-gesture.start.y;if(Math.hypot(dx,dy)>5)gesture.moved=true;
 if(gesture.kind==='pan'){const c=Math.cos(camera.angle),s=Math.sin(camera.angle);camera.x=gesture.camera.x-(c*dx+s*dy)/camera.scale;camera.y=gesture.camera.y-(-s*dx+c*dy)/camera.scale;cameraChanged()}
 else if(gesture.kind==='build'&&draft){if(!inside(p)){draft.cancelled=true;hover=null}else if(!draft.cancelled){draft.end=tool===0?tile(p):tool===8?tile(p):roadTool(tool)?straighten(draft.start,tile(p)):draft.start;hover=draft.end}}});
function endPointer(e,cancelled=false){if(!pointers.has(e.pointerId))return;const p=position(e),old=gesture,stroke=draft?{...draft,start:{...draft.start},end:{...draft.end}}:null;if(cancelled){cancelGesture();return}pointers.delete(e.pointerId); // The browser releases capture after pointerup; consume the stroke first.
 if(pointers.size>=2){beginPinch();return}if(pointers.size===1){const[id,a]=[...pointers.entries()][0];draft=null;gesture={kind:'pan',id,start:{x:a.x,y:a.y},camera:{x:camera.x,y:camera.y},moved:true,blocked:true};canvas.dataset.gesture='pan';return}
 if(old?.kind==='build'&&stroke&&!stroke.cancelled&&!old.blocked&&inside(p)){const start=stroke.start,end=tool===0?tile(p):tool===8?tile(p):roadTool(tool)?straighten(start,tile(p)):start;if(tool===0){removeWasRunning=!stats.paused;removalBounds={start,end,kind:0};removeRequest=send('review-remove',{x:start.x,y:start.y,x2:end.x,y2:end.y,kind:layer})}else if(tool===8)send('build-track',{x:start.x,y:start.y,x2:end.x,y2:end.y,kind:railBend});else if(tool===9)send('build-station',{x:start.x,y:start.y});else if(tool===10){if(cells.get(start.x+start.y*128)?.kind!==8)toast('Choose a station on your track.');else if(!serviceStart){serviceStart=start;$('hint').textContent=`Start: ${start.x}, ${start.y} · tap the last station · Esc cancels`;toast('Now tap the last station.')}else{const first={...serviceStart};send('create-service',{x:first.x,y:first.y,x2:start.x,y2:start.y});setTool(-2);inspect(first.x+first.y*128,true)}}else if(tool===11){send('rail-stop',{x:addStopLine,y:start.x+start.y*128});setTool(-2)}else if(tool===22)send('build-portal',{x:start.x,y:start.y});else send(roadTool(tool)?layer?'build-underground':tunnelMode?'build-tunnel':'build':'build',{x:start.x,y:start.y,x2:end.x,y2:end.y,kind:roadKind(stroke.kind,onewayDirection)})}else if(old?.kind==='pan'&&!old.moved&&!old.blocked&&inside(p)){const at=tile(p);inspect((layer===0?cityLab.pickAtlas(p,worldToScreen,camera.scale):null)??(at.x+at.y*128+layer*16384),true)}
 gesture=null;draft=null;hover=null;canvas.dataset.gesture='';scheduleView();}
canvas.addEventListener('pointerup',e=>endPointer(e));canvas.addEventListener('pointercancel',e=>endPointer(e,true));canvas.addEventListener('lostpointercapture',e=>{if(pointers.has(e.pointerId))cancelGesture()});canvas.addEventListener('pointerleave',()=>{hover=null;if(draft)draft.cancelled=true});canvas.addEventListener('contextmenu',e=>e.preventDefault());
canvas.addEventListener('wheel',e=>{e.preventDefault();cancelGesture();const delta=e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?height:1);anchorZoom(camera.scale*Math.exp(-clamp(delta,-250,250)*.0025),position(e))},{passive:false});
window.addEventListener('blur',cancelGesture);document.addEventListener('visibilitychange',()=>{if(document.hidden)cancelGesture()});window.addEventListener('pagehide',cancelGesture);
window.addEventListener('keydown',e=>{if(document.querySelector('dialog[open]'))return;if(e.key==='Escape'){if(lineManager.open){lineManager.close();return}cancelGesture();closeInspector();setTool(-2);return}if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;if(e.code==='Space'&&e.target.tagName!=='BUTTON'){e.preventDefault();cancelGesture();send('set-running',{kind:stats.paused?1:0})}else if(e.key==='+'||e.key==='='){$('zoom-in').click()}else if(e.key==='-'){$('zoom-out').click()}else if(e.key.toLowerCase()==='r'&&tool===20){onewayDirection=(onewayDirection+1)%4;$('oneway-direction').value=String(onewayDirection);cancelGesture()}else if(e.key.toLowerCase()==='u'){setLayer(1-layer)}else if(e.key.toLowerCase()==='f'){fitCity()}else if(e.key.startsWith('Arrow')){const v={ArrowLeft:[-75,0],ArrowRight:[75,0],ArrowUp:[0,-75],ArrowDown:[0,75]}[e.key];if(!v)return;e.preventDefault();cancelGesture();const c=Math.cos(camera.angle),s=Math.sin(camera.angle);camera.x+=(c*v[0]+s*v[1])/camera.scale;camera.y+=(-s*v[0]+c*v[1])/camera.scale;cameraChanged()}});
function inspect(id,open){selected=id;if(layer===0&&cityLab.inspectAtlas(id,open))return;const c=cells.get(id),rail=layer===0?railAt(id):null,x=id%128,y=gridY(id);if(open){$('inspector').hidden=false;send('inspect',{x,y,x2:layer})}$('inspect-title').textContent=(c?names[c.kind]:'Open land')+` · ${x}, ${y}`;if(rail&&(!c||c.kind===8)){$('inspect-title').textContent=`Shuttle ${rail.id}${c?.kind===8?' · station '+((rail.stops||[rail.a,rail.b]).indexOf(id)+1):''}`;$('inspect-body').textContent='Walk to the station, wait for a seat, ride, then walk to the destination. Work pays wages; purchases and fares move money through the city.';$('inspect-details').innerHTML=railDetails(rail);return}if(c?.kind===8&&!rail){$('inspect-body').textContent='A station ready for service. Use Rail → Service to connect it to another station.';$('inspect-details').innerHTML='';return}if(!c){$('inspect-body').textContent='Homes add eight people; workplaces offer sixteen jobs. Put useful destinations near homes and connect them.';$('inspect-details').innerHTML='';return}let reason=c.kind===13||layer===1&&cells.get(id%16384)?.kind===13?'A shared all-way stop joins the two layers. Cars reserve the portal before entering.':c.kind>=9&&c.kind<=12?'Cars follow the arrow; walkers travel both ways. The road must be clear before changing its direction.':c.kind===7?'A walking-only shortcut. Cars must use roads.':c.kind===3?'Eight permanent residents live here. Their jobs and destinations determine where they travel.':c.kind===4?'Sixteen jobs. Residents keep their work assignment until you change the city.':c.kind===5?'Residents spend their savings here; part of each purchase becomes city tax. Nearby shops can replace long car trips with short walks.':c.kind===6?'A local place to relax, then return home.':c.junction?'Vehicles yield, obey signals and reserve space beyond this junction.':'Each approach lane stores three cars. Full receiving lanes push queues upstream.';$('inspect-body').textContent=reason;
 const controls=['Yield · flowing turns','Timed signal','Priority E–W','Priority N–S'];let html=`<dl><dt>Cars / people walking</dt><dd>${c.q} / ${c.walk||0}</dd><dt>At destination</dt><dd>${c.inside||0}</dd></dl>`;if(c.junction&&c.kind!==13&&cells.get(id%16384)?.kind!==13)html+=`<p class="small">${controls[c.control||0]} · ${stats.phase===-1?'all red':stats.phase===0?'E–W green':'N–S green'}</p><div class="junction-controls">${controls.map((n,i)=>`<button data-signal="${i}" ${c.control===i?'disabled':''}>${n}</button>`).join('')}</div><p class="small">Change control · $40</p>`;
 const r=inspectResident;if(r&&r.id>0&&(r.home===id||r.cell===id||r.dest===id)){const reasons=['Travelling','No connected route','Waiting behind another car','No space ahead','Yielding or red signal','Conflicting movement','Picking up car','Parking','Planning a shared route','Missing destination','Waiting for a train','Riding the shuttle'];const purposes=['At home','Work','Shopping','Leisure','Returning home'];html+=`<div class="resident-card"><b>Resident ${r.id} · ${purposes[r.purpose]||'At home'}</b><p>${r.state===0?'Resting at home':r.state===3?'At their destination':reasons[r.reason]||'Travelling'} · ${r.mode===2?'driving':r.mode===1?'walking':r.mode===3?(r.state===6?'on rail':'walking + rail'):'choosing transport'}</p><dl><dt>Walk / drive estimate</dt><dd>${r.etaWalk<0?'—':r.etaWalk} / ${r.etaCar<0?'—':r.etaCar}</dd>${inspectRailPlan?.line?`<dt>Rail journey estimate</dt><dd>${inspectRailPlan.eta} cycles</dd>`:''}<dt>Household savings</dt><dd>$${inspectFunds}</dd><dt>Last journey</dt><dd>${r.lastTime} cycles</dd><dt>Waiting</dt><dd>${r.wait} cycles</dd></dl></div>`}if(rail)html+=`<div class="rail-card">${railDetails(rail)}</div>`;$('inspect-details').innerHTML=html;
}
// Presentation of the native orthogonal track stroke; never mutates game state.
function trackPreviewPath(a,b,bend=railBend){const corner=bend?{x:a.x,y:b.y}:{x:b.x,y:a.y},out=[{...a}];let p={...a};for(const end of[corner,b]){while((p.x!==end.x||p.y!==end.y)&&out.length<128){p={x:p.x+Math.sign(end.x-p.x),y:p.y+Math.sign(end.y-p.y)};out.push(p)}}return out}

function railIntersects(l,q){return railPath(l).some(id=>id%128>=q.x&&id%128<=q.x2&&gridY(id)>=q.y&&gridY(id)<=q.y2)}
function railAt(id){return rails.find(l=>railPath(l).includes(id))}
function railDetails(l){const state=lineState(l,stats.paused);return `<p><b>${state.label}</b></p><p class="small">${state.detail}</p><dl><dt>Line ${l.id} · on train</dt><dd>${l.occupancy} / ${l.capacity}</dd><dt>Stops / boardings</dt><dd>${(l.stops||[l.a,l.b]).length} / ${l.boardings}</dd><dt>Next leg / spent</dt><dd>$${l.expense} / $${l.spent}</dd></dl><button class="rail-service" data-open-lines="${l.id}">Manage line and stops</button><button class="rail-service" data-rail-service="${l.id}">${l.enabled?'Stop at next station':'Start departures'}</button><button class="rail-service" data-rail-stop="${l.id}" ${lineEditable(l)?'':'disabled'}>Add a stop</button>`}

function drawRails(now){let bounds=review;if(!bounds&&tool===0&&draft&&!draft.cancelled)bounds={x:Math.min(draft.start.x,draft.end.x),y:Math.min(draft.start.y,draft.end.y),x2:Math.max(draft.start.x,draft.end.x),y2:Math.max(draft.start.y,draft.end.y)};
 const colors=railColors;ctx.lineCap='round';ctx.lineJoin='round';const assigned=railPaint.assigned;ctx.strokeStyle='#96978e';ctx.lineWidth=.12;ctx.beginPath();for(const id of tracks){if(assigned.has(id))continue;const x=id%128+.5,y=gridY(id)+.5;ctx.moveTo(x-.04,y);ctx.lineTo(x+.04,y);for(const d of[1,128])if(tracks.has(id+d)&&Math.abs((id+d)%128-id%128)<=1){ctx.moveTo(x,y);ctx.lineTo((id+d)%128+.5,Math.floor((id+d)/128)+.5)}}ctx.stroke();
 for(const l of rails){const points=railGeometry(l),color=colors[(l.id-1)%colors.length],highlight=bounds&&railIntersects(l,bounds);for(const [width,color2]of[[.33,'#33443624'],[highlight?.37:.25,highlight?'#c26543':'#e7e4d7'],[.10,color]]){ctx.strokeStyle=color2;ctx.lineWidth=width;ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.stroke()}}
 for(const {id,line:l,waiting,label} of railPaint.stations){const color=l?colors[(l.id-1)%colors.length]:'#8b9587',x=id%128+.5,y=gridY(id)+.5;pathRound(x-.44,y-.42,.88,.84,.13,'#eeeada');pathRound(x-.34,y-.25,.68,.5,.07,color);pathRound(x-.24,y-.15,.48,.30,.03,'#f1f1dc');drawEntrances({id,kind:8});if(camera.scale>=18){ctx.save();ctx.translate(x,y);ctx.rotate(-camera.angle);ctx.fillStyle=color;ctx.font='700 .21px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(label,0,0);if(waiting){pathRound(.15,-.53,.50,.28,.1,'#bd724e');ctx.fillStyle='#fff7e5';ctx.font='700 .19px system-ui';ctx.fillText(String(waiting),.40,-.39)}ctx.restore()}}
 for(const {current:l,previous:old,mix} of trafficMotion.sampleRails(now,motionReduced())){const same=old&&railPath(old).join(',')===railPath(l).join(','),progress=railProgress(l),before=same?railProgress(old):progress,pos=railPose(l,before+(progress-before)*mix),color=colors[(l.id-1)%colors.length];ctx.save();ctx.translate(pos.x,pos.y);ctx.rotate(pos.angle);pathRound(-.43,-.18,.88,.38,.10,'#30483930');pathRound(-.46,-.22,.88,.36,.10,l.enabled||l.status===1?'#faf0d3':'#c8cebf');ctx.strokeStyle=color;ctx.lineWidth=.035;ctx.beginPath();ctx.roundRect(-.46,-.22,.88,.36,.10);ctx.stroke();for(const offset of[-.30,-.05,.20])pathRound(offset,-.13,.16,.16,.025,color);ctx.restore()}
}

function pathRound(x,y,w,h,r,fill){ctx.fillStyle=fill;ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
function neighbors(c){return connections(c,cells).filter(a=>a.dir<2).map(a=>a.next)}
function roadWidth(c){return c.kind===2?.74:.48}
function drawRoads(visible){ctx.lineCap='round';ctx.lineJoin='round';for(const pass of [0,1])for(const kind of [1,2,9,10,11,12,13]){ctx.strokeStyle=pass?'#5e766e':'#d6ddce';ctx.lineWidth=(kind===2?.74:.48)+(pass?0:.15);ctx.beginPath();for(const c of visible){if(c.kind!==kind)continue;const x=c.id%128+.5,y=gridY(c.id)+.5;ctx.moveTo(x-.01,y);ctx.lineTo(x+.01,y);for(const id of [c.id-1,c.id+1,c.id-128,c.id+128]){const n=cells.get(id);if(n&&layerOf(n.id)===layerOf(c.id)&&Math.abs(n.id%128-c.id%128)+Math.abs(gridY(n.id)-gridY(c.id))===1){ctx.moveTo(x,y);ctx.lineTo((x+id%128+.5)/2,(y+gridY(id)+.5)/2)}}}ctx.stroke()}
 ctx.strokeStyle='#b9c9b96e';ctx.lineWidth=.035;ctx.setLineDash([.16,.16]);ctx.beginPath();for(const c of visible)if(c.kind===2){const x=c.id%128+.5,y=gridY(c.id)+.5;for(const n of neighbors(c)){ctx.moveTo(x,y);ctx.lineTo(n.id%128+.5,gridY(n.id)+.5)}}ctx.stroke();ctx.setLineDash([]);
 }
function drawRoadMarkings(visible){ctx.save();for(const c of visible){const x=c.id%128+.5,y=gridY(c.id)+.5;if(c.kind>=9&&c.kind<=12){ctx.save();ctx.translate(x,y);ctx.rotate((c.kind-9)*Math.PI/2);ctx.strokeStyle='#f3ead0';ctx.lineWidth=.045;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(-.15,0);ctx.lineTo(.15,0);ctx.moveTo(.035,-.1);ctx.lineTo(.15,0);ctx.lineTo(.035,.1);ctx.stroke();ctx.restore()}if(c.kind===13||layer===1&&cells.get(c.id%16384)?.kind===13){ctx.fillStyle='#23494d';ctx.strokeStyle='#dcceaa';ctx.lineWidth=.06;ctx.beginPath();ctx.roundRect(x-.25,y-.25,.5,.5,.1);ctx.fill();ctx.stroke();ctx.strokeStyle='#f5eed8';ctx.lineWidth=.04;ctx.beginPath();for(let i=-1;i<=1;i++){ctx.moveTo(x-.12,y+i*.1);ctx.lineTo(x+.12,y+i*.1)}ctx.stroke()}}ctx.restore()}
function drawRoadQueues(visible){ctx.save();ctx.lineCap='round';ctx.lineJoin='round';for(const c of visible){if(!isRoad(c.kind))continue;const storage=c.kind===2?12:6;if(c.q<storage*.6)continue;ctx.strokeStyle=c.q>=storage?'#cb694b':'#d6a65b';ctx.lineWidth=roadWidth(c)*.62;const arms=roadHeatSegments(c,cells);ctx.beginPath();if(!arms.length){const x=c.id%128+.5,y=gridY(c.id)+.5;ctx.moveTo(x,y);ctx.lineTo(x+.001,y)}for(const [a,b]of arms){ctx.moveTo(a.x,a.y);ctx.lineTo(b.x,b.y)}ctx.stroke()}ctx.restore()}
function drawBridgeDecks(visible){ctx.save();ctx.lineCap='butt';ctx.lineJoin='round';for(const c of visible){if(!(isRoad(c.kind)||c.kind===7)||!waterAt(river,riverWidth,c.id))continue;const x=c.id%128+.5,y=gridY(c.id)+.5,w=c.kind===7?.38:roadWidth(c)+.24,arms=connections(c,cells).filter(a=>isRoad(a.next.kind)||a.next.kind===7);ctx.strokeStyle='#f1ebd9';ctx.lineWidth=w;ctx.beginPath();if(!arms.length){ctx.moveTo(x-.5,y);ctx.lineTo(x+.5,y)}for(const {d}of arms){ctx.moveTo(x,y);ctx.lineTo(x+d[0]*.55,y+d[1]*.55)}ctx.stroke();ctx.strokeStyle='#8b9f99';ctx.lineWidth=.045;ctx.beginPath();for(const {d}of arms)for(const side of [-1,1]){const nx=-d[1]*(w/2-.015)*side,ny=d[0]*(w/2-.015)*side;ctx.moveTo(x+nx,y+ny);ctx.lineTo(x+d[0]*.51+nx,y+d[1]*.51+ny)}ctx.stroke()}ctx.restore()}
function drawEntrances(c){ctx.save();for(const {door,edge,dir}of entranceLinks(c,cells)){ctx.strokeStyle=c.kind===6?'#c1ad88':'#ddd1b8';ctx.lineWidth=.17;ctx.lineCap='butt';ctx.beginPath();ctx.moveTo(door.x,door.y);ctx.lineTo(edge.x,edge.y);ctx.stroke();const d=[[1,0],[0,1],[-1,0],[0,-1]][dir];ctx.strokeStyle='#3c655d';ctx.lineWidth=.055;ctx.beginPath();ctx.moveTo(door.x-d[1]*.075,door.y+d[0]*.075);ctx.lineTo(door.x+d[1]*.075,door.y-d[0]*.075);ctx.stroke()}ctx.restore()}
function drawBuilding(c){const x=c.id%128+.5,y=gridY(c.id)+.5;
 if(c.kind===6){pathRound(x-.47,y-.47,.94,.94,.20,'#c0d3ad');for(const [dx,dy,r] of [[-.2,-.15,.19],[.19,.17,.22],[.17,-.2,.14]]){ctx.fillStyle='#6d9367';ctx.beginPath();ctx.arc(x+dx,y+dy,r,0,Math.PI*2);ctx.fill()}pathRound(x-.29,y+.23,.23,.07,.015,'#b68c61');drawEntrances(c);return}if(c.kind===5){pathRound(x-.46,y-.46,.92,.92,.16,'#eee0c1');pathRound(x-.34,y-.28,.68,.55,.04,'#e2bc70');pathRound(x-.37,y+.10,.74,.18,.02,'#bc765b');for(let i=0;i<4;i++)pathRound(x-.35+i*.18,y+.10,.08,.18,.01,'#f5e4ba');drawEntrances(c);return}
 pathRound(x-.49,y-.49,.98,.98,.18,c.kind===3?'#e3dfcf':'#dbe6de');pathRound(x-.29+.065,y-.31+.09,.62,.64,.08,'#274b3c18');if(c.kind===3){pathRound(x-.3,y-.31,.6,.62,.055,'#d6a18a');ctx.fillStyle='#bc7c65';ctx.beginPath();ctx.moveTo(x-.31,y-.32);ctx.lineTo(x+.31,y-.32);ctx.lineTo(x+.12,y+.32);ctx.lineTo(x-.31,y+.32);ctx.fill();ctx.strokeStyle='#f0c5aa';ctx.lineWidth=.035;ctx.beginPath();ctx.moveTo(x,y-.28);ctx.lineTo(x,y+.28);ctx.stroke();pathRound(x+.17,y-.12,.09,.17,.02,'#f1d8c2');pathRound(x-.18,y-.16,.08,.1,.01,'#f8ecd8')}else{pathRound(x-.36,y-.35,.72,.7,.045,'#63888e');pathRound(x-.3,y-.29,.6,.16,.02,'#aac2bb');for(let i=0;i<3;i++)pathRound(x-.27+i*.2,y-.01,.12,.25,.018,'#d6e1cb');pathRound(x-.39,y+.28,.78,.075,.01,'#416b73')}
 drawEntrances(c);
}
function actorPosition(a){return actorPose(a,cells)}
function drawResidents(now){const glyph=pedestrianSize(camera.scale);for(const a of trafficMotion.sample(now,motionReduced())){if(layerOf(a.from)!==layer&&layerOf(a.to)!==layer)continue;ctx.save();ctx.translate(a.x,a.y);ctx.rotate(a.angle);if(a.mode!==2){
 // One solid circle at every zoom; retain the minimum screen-space size.
 ctx.fillStyle=['#466957','#be7e58','#826f99'][a.id%3];ctx.beginPath();ctx.arc(0,0,glyph.radius,0,Math.PI*2);ctx.fill();
 }else{pathRound(-.08,-.0325,.16,.065,.019,['#f8e8bb','#cf7d61','#89b2af','#e7b961'][a.id%4]);pathRound(-.014,-.026,.043,.052,.010,'#405a58');ctx.fillStyle='#fff4cf';ctx.fillRect(.057,-.027,.018,.011);ctx.fillRect(.057,.016,.018,.011)}ctx.restore()}}
function drawFootpaths(visible){ctx.strokeStyle='#baa886';ctx.lineWidth=.16;ctx.setLineDash([.12,.06]);for(const c of visible){if(c.kind!==7)continue;const x=c.id%128+.5,y=gridY(c.id)+.5;ctx.beginPath();ctx.moveTo(x-.05,y);ctx.lineTo(x+.05,y);for(const id of [c.id-1,c.id+1,c.id-128,c.id+128])if(cells.has(id)&&layerOf(id)===layerOf(c.id)&&Math.abs(id%128-c.id%128)+Math.abs(gridY(id)-gridY(c.id))===1){ctx.moveTo(x,y);ctx.lineTo((x+id%128+.5)/2,(y+gridY(id)+.5)/2)}ctx.stroke()}ctx.setLineDash([])}
// Rendering bounds include the whole canvas, including beneath translucent HUD.
// Reuse a chunk query until the rectangle or native cell references change.
function renderCells(){const corners=[{x:0,y:0},{x:width,y:0},{x:0,y:height},{x:width,y:height}].map(screenToWorld),x0=clamp(Math.floor(Math.min(...corners.map(p=>p.x)))-1,0,127),x1=clamp(Math.ceil(Math.max(...corners.map(p=>p.x)))+1,0,127),y0=clamp(Math.floor(Math.min(...corners.map(p=>p.y)))-1,0,127),y1=clamp(Math.ceil(Math.max(...corners.map(p=>p.y)))+1,0,127);return tileIndex.query(layer,x0,y0,x1,y1)}
function drawOverview(visible){const colors=['','#5e766e','#5e766e','#c9967e','#63888e','#dab36b','#88a779','#baa886','#6f7194','#5e766e','#5e766e','#5e766e','#5e766e','#406f7a'];for(let kind=1;kind<=13;kind++){ctx.fillStyle=colors[kind];ctx.beginPath();for(const c of visible){if(c.kind!==kind)continue;const x=c.id%128,y=gridY(c.id),inset=isRoad(kind)&&kind!==2?.26:kind===2?.13:kind===7?.42:.13;ctx.rect(x+inset,y+inset,1-inset*2,1-inset*2);if(isRoad(kind)||kind===7){for(const [dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){const next=cells.get(c.id+dx+dy*128);if(!next||x+dx<0||x+dx>127||y+dy<0||y+dy>127)continue;if(dx)ctx.rect(x+(dx>0?.5:0),y+inset,.5,1-2*inset);else ctx.rect(x+inset,y+(dy>0?.5:0),1-2*inset,.5)}}}ctx.fill()}}
// Cache only stationary road/building paint. Queues, people, trains, water and
// selection overlays still use the current native frame on every browser draw.
function drawStaticMap(visible,detailed=true){const o=origin(),key=[width,height,dpr,camera.x,camera.y,camera.scale,camera.angle,o.x,o.y,stats.version,mapRevision,layer,detailed].join(':');if(key!==staticMapKey){staticMapCanvas.width=canvas.width;staticMapCanvas.height=canvas.height;const main=ctx;try{staticMapContext.setTransform(main.getTransform());ctx=staticMapContext;drawBridgeDecks(visible);if(detailed){drawRoads(visible);drawFootpaths(visible);drawRoadMarkings(visible);for(const c of visible)if(c.kind>=3&&c.kind<=6)drawBuilding(c)}else drawOverview(visible);staticMapKey=key}finally{ctx=main}}ctx.save();ctx.setTransform(1,0,0,1,0,0);ctx.drawImage(staticMapCanvas,0,0);ctx.restore()}
function drawTerrain(now){const ox=stats.originX||0,oy=stats.originY||0,riverX=ox+14;ctx.fillStyle='#edf0e8';ctx.fillRect(0,0,width,height);const o=origin();ctx.save();ctx.translate(o.x,o.y);ctx.rotate(camera.angle);ctx.scale(camera.scale,camera.scale);ctx.translate(-camera.x,-camera.y);ctx.fillStyle=layer?'#d3dcd4':'#e6e9dc';ctx.fillRect(0,0,128,128);
 // A quiet continuous ground keeps roads readable at every zoom level.
 const r=visibleRect();
 if(layer===0)drawRiver(ctx,river,riverWidth);
 if((tool!==-2||preferences.grid)&&camera.scale>=15){ctx.strokeStyle='#778a7127';ctx.lineWidth=.018;ctx.beginPath();for(let x=r.x;x<=r.x+r.w;x++){ctx.moveTo(x,r.y);ctx.lineTo(x,r.y+r.h)}for(let y=r.y;y<=r.y+r.h;y++){ctx.moveTo(r.x,y);ctx.lineTo(r.x+r.w,y)}ctx.stroke()}
 const visible=renderCells(),moving=performance.now()<cameraMotionUntil,detailed=detail&&(visible.length<=512||!moving);if(moving&&!detailed){drawBridgeDecks(visible);drawOverview(visible)}else drawStaticMap(visible,detailed);drawRoadQueues(visible);
 drawResidents(now);if(layer===0)drawRails(now);
 if(selected!==null){const x=selected%128,y=gridY(selected);ctx.strokeStyle='#2e816b';ctx.lineWidth=.06;ctx.beginPath();ctx.roundRect(x-.04,y-.04,1.08,1.08,.13);ctx.stroke()}
 const preview=removalBounds||(draft&&!draft.cancelled?draft:(hover&&tool!==-2?{start:hover,end:hover,kind:tool}:null));if(preview){const a=preview.start,b=preview.kind===0?preview.end:preview.kind===8?preview.end:roadTool(preview.kind)?straighten(a,preview.end):a,x=Math.min(a.x,b.x),y=Math.min(a.y,b.y),w=Math.abs(a.x-b.x)+1,h=Math.abs(a.y-b.y)+1;ctx.fillStyle=preview.kind===0?'#d77c534c':'#2d967851';ctx.strokeStyle=preview.kind===0?'#c26543':'#297d62';ctx.lineWidth=.065;if(preview.kind===8){const path=trackPreviewPath(a,b);for(const p of path)ctx.fillRect(p.x+.06,p.y+.06,.88,.88);ctx.lineWidth=.14;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();path.forEach((p,i)=>i?ctx.lineTo(p.x+.5,p.y+.5):ctx.moveTo(p.x+.5,p.y+.5));ctx.stroke()}else{ctx.fillRect(x,y,w,h);ctx.strokeRect(x+.025,y+.025,w-.05,h-.05)}}if(serviceStart&&tool===10){ctx.strokeStyle='#297d62';ctx.lineWidth=.09;ctx.beginPath();ctx.roundRect(serviceStart.x-.1,serviceStart.y-.1,1.2,1.2,.22);ctx.stroke()}ctx.restore();return preview;
}
function surfaceQuote(a,b,kind){let cost=0,wet=0,unbuiltWater=false,count=0;for(let y=Math.min(a.y,b.y);y<=Math.max(a.y,b.y);y++)for(let x=Math.min(a.x,b.x);x<=Math.max(a.x,b.x);x++){const id=x+y*128,water=waterAt(river,riverWidth,id),old=cells.get(id)?.kind||0;count++;if(water){wet++;if(!(isRoad(old)||old===7))unbuiltWater=true}if(old!==kind)cost+=water?(kind===1?32:kind===2?72:kind>=9&&kind<=12?48:16):prices[kind]}return{tiles:count,cost,water:wet,invalid:unbuiltWater&&(waterAt(river,riverWidth,a.x+a.y*128)||waterAt(river,riverWidth,b.x+b.y*128))}}
function drawLabel(text,p,color='#607c70',size=10){ctx.fillStyle=color;ctx.font=`600 ${size}px ui-sans-serif,system-ui,sans-serif`;ctx.textAlign='center';ctx.fillText(text,p.x,p.y)}
function drawPendingCommands(){for(const c of commandQueue.items){if(!mapEdit(c.op))continue;const depth=c.op==='build-underground'?1:c.op==='review-remove'?c.kind:0;if(depth!==layer)continue;const line=['build','build-underground','build-tunnel','build-track','review-remove'].includes(c.op),x2=line?c.x2:c.x,y2=line?c.y2:c.y;const x=Math.min(c.x,x2),y=Math.min(c.y,y2),w=Math.abs(x2-c.x)+1,h=Math.abs(y2-c.y)+1;const points=[[x,y],[x+w,y],[x+w,y+h],[x,y+h]].map(([x,y])=>worldToScreen(x,y));ctx.save();ctx.strokeStyle='#bd724e';ctx.fillStyle='#bd724e22';ctx.lineWidth=2;ctx.setLineDash([5,4]);ctx.beginPath();points.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();}}
function draw(now){const start=performance.now();frameArea=mapArea();drawCount++;ctx.setTransform(dpr,0,0,dpr,0,0);const preview=drawTerrain(now);drawPendingCommands();const river=worldToScreen((stats.originX||0)+15,(stats.originY||0)+16.4);if(layer===0&&river.x>85&&river.x<width-85&&river.y>170&&river.y<height-250){ctx.save();ctx.translate(river.x,river.y);ctx.rotate(camera.angle+Math.PI/2);drawLabel('W I L L O W   R I V E R',{x:0,y:0},'#689b96',Math.max(8,Math.min(11,camera.scale*.3)));ctx.restore();}
 const congested=tileIndex.hot[layer];const badges=[];for(const c of congested){if(badges.length===3)break;const p=worldToScreen(c.id%128+.5,gridY(c.id)+.5);if(p.x<8||p.x>width-8||p.y<70||p.y>height-100||badges.some(b=>Math.hypot(p.x-b.x,p.y-b.y)<Math.max(55,camera.scale*1.4)))continue;badges.push(p);const label=c.q>999?'999+':String(c.q),w=label.length*6+15;pathRound(p.x-w/2,p.y-camera.scale*.7-16,w,19,9,'#ce6b48');drawLabel(label,{x:p.x,y:p.y-camera.scale*.7-3},'#fff7e8',10)}
 if(layer===0)cityLab.drawAtlas(ctx,worldToScreen,camera.scale,width,height);
 if(preview){const a=preview.start,b=preview.end,n=preview.kind===0?(Math.abs(b.x-a.x)+1)*(Math.abs(b.y-a.y)+1):Math.abs(b.x-a.x)+Math.abs(b.y-a.y)+1;const p=worldToScreen((a.x+b.x)/2+.5,(a.y+b.y)/2+.5);const surface=roadTool(preview.kind),end=surface?straighten(a,b):b,kind=roadKind(preview.kind,onewayDirection),under=surface&&(layer===1||tunnelMode),quote=surface?(under?undergroundQuote(cells,a,end,kind,layer===0):surfaceQuote(a,end,kind)):null;const text=preview.kind===0?`${Math.abs(b.x-a.x)+1} × ${Math.abs(b.y-a.y)+1} · ${review?'reviewing':removeRequest?'preparing review':'release to review'}`:preview.kind===8?`${n} track tiles · up to $${n*12} + bridges`:quote?`${quote.tiles} tiles · $${quote.cost}${under?' · underground':quote.water?' · bridge':''}${quote.invalid?under?' · at least 3 tiles':' · reach both banks':' · release to build'}`:`${n} ${n===1?'tile':'tiles'} · release to build`;ctx.font='600 10px system-ui';const w=ctx.measureText(text).width+20;pathRound(clamp(p.x-w/2,8,width-w-8),clamp(p.y-46,145,height-220),w,25,12,'#23483df0');drawLabel(text,{x:clamp(p.x,w/2+8,width-w/2-8),y:clamp(p.y-46,145,height-220)+16},'#fffcec',10)}
 frameArea=null;frameTimes.push(performance.now()-start);if(frameTimes.length>180)frameTimes.shift();requestAnimationFrame(draw)}
// Read-only instrumentation binds browser input assertions to actual camera and server frames.
window.__flowgarden={get renderMetrics(){return{draws:drawCount,indexRebuilds:tileIndex.revision,queries:tileIndex.queryCount,visitedCells:tileIndex.visits}},get pendingCommands(){return commandQueue.items},get layer(){return layer},get tunnelMode(){return tunnelMode},get onewayDirection(){return onewayDirection},get river(){return river.map(p=>({...p}))},get riverWidth(){return riverWidth},surfaceQuote,get atlas(){return cityLab.atlas},get lab(){return cityLab.report},get street(){return{walking:lastFrame?.streetWalkers||0,driving:lastFrame?.streetDrivers||0,shown:actors.length}},get renderedActors(){return trafficMotion.rendered.map(a=>({...a}))},get motionTime(){return trafficMotion.time},get motionMetrics(){return trafficMotion.diagnostics},get stats(){return stats},get rails(){return rails.map(l=>({...l}))},get actors(){return actors.map(a=>({...a}))},get sessionStatus(){return sessionStatus},get detail(){return detail},get cells(){return[...cells.values()]},get view(){return{...serverView}},get camera(){return{...camera}},get gesture(){return gesture?{kind:gesture.kind,blocked:gesture.blocked}:null},get pointerCount(){return pointers.size},get draft(){return draft?{...draft}:null},get sequence(){return sequence},get tool(){return tool},get trackPreview(){return draft?.kind===8?trackPreviewPath(draft.start,draft.end).map(p=>({...p})):[]},get serviceStart(){return serviceStart?{...serviceStart}:null},get review(){return review?{...review}:null},get menuPage(){return menuPage},worldToScreen,screenToWorld,history,sentCommands,frameTimes};
setTool(-2);connect();requestAnimationFrame(draw);

$('inspect-details').addEventListener('click',e=>{const manage=e.target.closest('[data-open-lines]');if(manage){lineManager.show(Number(manage.dataset.openLines));return}const add=e.target.closest('[data-rail-stop]');if(add){beginAddStop(Number(add.dataset.railStop));return}const service=e.target.closest('[data-rail-service]');if(service){const l=rails.find(l=>l.id===Number(service.dataset.railService));if(l)send('rail-service',{x:l.id,kind:l.enabled?0:1});return}const b=e.target.closest('[data-signal]');if(b&&selected!==null)send(layer?'signal-underground':'signal',{x:selected%128,y:gridY(selected),kind:Number(b.dataset.signal)})});
$('resume').onclick=()=>{ownerToken=randomHex(16);if(connected)send('resume');else connect()};


$('finance-open').onclick=()=>{updateFinances(stats);$('finance').showModal()};
